namespace ERPChess
{
    using ERPChess.Properties;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class frmHelp : Form
    {
        private IContainer components;
        private TabControl tabControl1;
        private TabPage tabPage1;
        private TabPage tabPage2;
        private TabPage tabPage3;
        private TabPage tabPage4;
        private Panel panel1;
        private GroupBox groupBox2;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label16;
        private Label label17;
        private Label label18;
        private Label label19;
        private Label label20;
        private Label label21;
        private Label label22;
        private Label label23;
        private Label label24;
        private Label label25;
        private Label label26;
        private Label label27;
        private Label label28;
        private GroupBox groupBox1;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label45;
        private Label label46;
        private Label label47;
        private Label label48;
        private GroupBox groupBox3;
        private Label label49;
        private Label label50;
        private Label label51;
        private Label label52;
        private GroupBox groupBox4;
        private Label label78;
        private Label label79;
        private Label label80;
        private Label label81;
        private Label label82;
        private Label label83;
        private Label label84;
        private Label label85;
        private Label label86;
        private Label label87;
        private Label label73;
        private Label label74;
        private Label label75;
        private Label label76;
        private Label label77;
        private Label label53;
        private Label label54;
        private Label label55;
        private Label label56;
        private Label label57;
        private Label label58;
        private Label label59;
        private Label label60;
        private Label label61;
        private Label label62;
        private Label label63;
        private Label label64;
        private Label label65;
        private Label label66;
        private Label label67;
        private Label label68;
        private Label label69;
        private Label label70;
        private Label label71;
        private Label label72;
        private Button button1;
        private GroupBox groupBox5;
        private Label label29;
        private Label label31;
        private Label label32;
        private Label label88;
        private Label label90;
        private Label label91;
        private Label label92;
        private Label label94;
        private Label label95;
        private Label label97;
        private Label label98;
        private Label label99;
        private GroupBox groupBox6;
        private Label label30;
        private Label label89;
        private Label label93;
        private Label label96;
        private Label label100;
        private Label label101;
        private Label label102;
        private Label label103;
        private Label label104;
        private Label label105;
        private Label label106;
        private Label label107;
        private Label label108;
        private Label label109;
        private Label label110;
        private Label label111;
        private Label label112;
        private Label label113;
        private Label label114;
        private Label label115;
        private GroupBox groupBox7;
        private Label label117;
        private Label label122;
        private Label label123;
        private Label label124;
        private Label label125;
        private Label label126;
        private Label label127;
        private Label label128;
        private Label label129;
        private Label label130;
        private Label label131;
        private Label label132;
        private Label label133;
        private Label label134;
        private Label label135;
        private Label label136;
        private Label label137;
        private Label label138;
        private Label label139;
        private Label label140;
        private Label label141;
        private Label label142;
        private Label label143;
        private Label label144;
        private Label label145;
        private Label label146;
        private Label label147;
        private Label label148;
        private Label label149;
        private Label label150;
        private PictureBox pictureBox1;
        private PictureBox pictureBox2;
        private PictureBox pictureBox3;
        private Label label116;
        private Label label118;
        private Label label119;
        private Label label120;
        private Label label121;
        private Label label151;
        private Label label152;
        private Label label153;
        private Label label154;
        private Label label33;
        private Label label34;
        private Label label35;
        private GroupBox groupBox8;
        private Label label36;
        private RichTextBox richTextBox1;
        private GroupBox groupBox9;
        private RichTextBox richTextBox2;
        private GroupBox groupBox10;
        private RichTextBox richTextBox3;
        private Label label37;
        private PictureBox pictureBox4;

        public frmHelp()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(frmHelp));
            this.tabControl1 = new TabControl();
            this.tabPage1 = new TabPage();
            this.pictureBox1 = new PictureBox();
            this.groupBox4 = new GroupBox();
            this.label78 = new Label();
            this.label79 = new Label();
            this.label80 = new Label();
            this.label81 = new Label();
            this.label82 = new Label();
            this.label83 = new Label();
            this.label84 = new Label();
            this.label85 = new Label();
            this.label86 = new Label();
            this.label87 = new Label();
            this.label73 = new Label();
            this.label74 = new Label();
            this.label75 = new Label();
            this.label76 = new Label();
            this.label77 = new Label();
            this.label53 = new Label();
            this.label54 = new Label();
            this.label55 = new Label();
            this.label56 = new Label();
            this.label57 = new Label();
            this.label58 = new Label();
            this.label59 = new Label();
            this.label60 = new Label();
            this.label61 = new Label();
            this.label62 = new Label();
            this.label63 = new Label();
            this.label64 = new Label();
            this.label65 = new Label();
            this.label66 = new Label();
            this.label67 = new Label();
            this.label68 = new Label();
            this.label69 = new Label();
            this.label70 = new Label();
            this.label71 = new Label();
            this.label72 = new Label();
            this.groupBox1 = new GroupBox();
            this.label49 = new Label();
            this.label50 = new Label();
            this.label51 = new Label();
            this.label52 = new Label();
            this.label1 = new Label();
            this.label2 = new Label();
            this.label3 = new Label();
            this.label4 = new Label();
            this.label5 = new Label();
            this.label6 = new Label();
            this.label7 = new Label();
            this.label8 = new Label();
            this.label9 = new Label();
            this.label10 = new Label();
            this.label11 = new Label();
            this.label12 = new Label();
            this.label45 = new Label();
            this.label46 = new Label();
            this.label47 = new Label();
            this.label48 = new Label();
            this.groupBox2 = new GroupBox();
            this.label13 = new Label();
            this.label14 = new Label();
            this.label15 = new Label();
            this.label16 = new Label();
            this.label17 = new Label();
            this.label18 = new Label();
            this.label19 = new Label();
            this.label20 = new Label();
            this.label21 = new Label();
            this.label22 = new Label();
            this.label23 = new Label();
            this.label24 = new Label();
            this.label25 = new Label();
            this.label26 = new Label();
            this.label27 = new Label();
            this.label28 = new Label();
            this.tabPage2 = new TabPage();
            this.pictureBox2 = new PictureBox();
            this.groupBox6 = new GroupBox();
            this.label30 = new Label();
            this.label89 = new Label();
            this.label93 = new Label();
            this.label96 = new Label();
            this.label100 = new Label();
            this.label101 = new Label();
            this.label102 = new Label();
            this.label103 = new Label();
            this.label104 = new Label();
            this.label105 = new Label();
            this.label106 = new Label();
            this.label107 = new Label();
            this.label108 = new Label();
            this.label109 = new Label();
            this.label110 = new Label();
            this.label111 = new Label();
            this.label112 = new Label();
            this.label113 = new Label();
            this.label114 = new Label();
            this.label115 = new Label();
            this.groupBox5 = new GroupBox();
            this.label29 = new Label();
            this.label31 = new Label();
            this.label32 = new Label();
            this.label88 = new Label();
            this.label90 = new Label();
            this.label91 = new Label();
            this.label92 = new Label();
            this.label94 = new Label();
            this.label95 = new Label();
            this.label97 = new Label();
            this.label98 = new Label();
            this.label99 = new Label();
            this.groupBox3 = new GroupBox();
            this.label33 = new Label();
            this.label34 = new Label();
            this.label35 = new Label();
            this.label116 = new Label();
            this.label118 = new Label();
            this.label152 = new Label();
            this.label153 = new Label();
            this.label151 = new Label();
            this.label119 = new Label();
            this.label154 = new Label();
            this.label121 = new Label();
            this.label120 = new Label();
            this.tabPage3 = new TabPage();
            this.groupBox8 = new GroupBox();
            this.richTextBox1 = new RichTextBox();
            this.label36 = new Label();
            this.pictureBox3 = new PictureBox();
            this.groupBox7 = new GroupBox();
            this.label117 = new Label();
            this.label122 = new Label();
            this.label123 = new Label();
            this.label124 = new Label();
            this.label125 = new Label();
            this.label126 = new Label();
            this.label127 = new Label();
            this.label128 = new Label();
            this.label129 = new Label();
            this.label130 = new Label();
            this.label131 = new Label();
            this.label132 = new Label();
            this.label133 = new Label();
            this.label134 = new Label();
            this.label135 = new Label();
            this.label136 = new Label();
            this.label137 = new Label();
            this.label138 = new Label();
            this.label139 = new Label();
            this.label140 = new Label();
            this.label141 = new Label();
            this.label142 = new Label();
            this.label143 = new Label();
            this.label144 = new Label();
            this.label145 = new Label();
            this.label146 = new Label();
            this.label147 = new Label();
            this.label148 = new Label();
            this.label149 = new Label();
            this.label150 = new Label();
            this.tabPage4 = new TabPage();
            this.pictureBox4 = new PictureBox();
            this.groupBox10 = new GroupBox();
            this.richTextBox3 = new RichTextBox();
            this.label37 = new Label();
            this.groupBox9 = new GroupBox();
            this.richTextBox2 = new RichTextBox();
            this.panel1 = new Panel();
            this.button1 = new Button();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            ((ISupportInitialize) this.pictureBox1).BeginInit();
            this.groupBox4.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.tabPage2.SuspendLayout();
            ((ISupportInitialize) this.pictureBox2).BeginInit();
            this.groupBox6.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.tabPage3.SuspendLayout();
            this.groupBox8.SuspendLayout();
            ((ISupportInitialize) this.pictureBox3).BeginInit();
            this.groupBox7.SuspendLayout();
            this.tabPage4.SuspendLayout();
            ((ISupportInitialize) this.pictureBox4).BeginInit();
            this.groupBox10.SuspendLayout();
            this.groupBox9.SuspendLayout();
            this.panel1.SuspendLayout();
            base.SuspendLayout();
            this.tabControl1.Appearance = TabAppearance.FlatButtons;
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Controls.Add(this.tabPage4);
            this.tabControl1.Dock = DockStyle.Fill;
            this.tabControl1.Location = new Point(0, 0);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new Size(0x2e9, 0x1bb);
            this.tabControl1.TabIndex = 0;
            this.tabPage1.Controls.Add(this.pictureBox1);
            this.tabPage1.Controls.Add(this.groupBox4);
            this.tabPage1.Controls.Add(this.groupBox1);
            this.tabPage1.Controls.Add(this.groupBox2);
            this.tabPage1.Location = new Point(4, 0x18);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new Padding(3);
            this.tabPage1.Size = new Size(0x2e1, 0x19f);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "生产类";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.pictureBox1.Image = Resources.png0505;
            this.pictureBox1.Location = new Point(0x22e, 0x17);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new Size(0x80, 0x80);
            this.pictureBox1.SizeMode = PictureBoxSizeMode.AutoSize;
            this.pictureBox1.TabIndex = 120;
            this.pictureBox1.TabStop = false;
            this.groupBox4.Controls.Add(this.label78);
            this.groupBox4.Controls.Add(this.label79);
            this.groupBox4.Controls.Add(this.label80);
            this.groupBox4.Controls.Add(this.label81);
            this.groupBox4.Controls.Add(this.label82);
            this.groupBox4.Controls.Add(this.label83);
            this.groupBox4.Controls.Add(this.label84);
            this.groupBox4.Controls.Add(this.label85);
            this.groupBox4.Controls.Add(this.label86);
            this.groupBox4.Controls.Add(this.label87);
            this.groupBox4.Controls.Add(this.label73);
            this.groupBox4.Controls.Add(this.label74);
            this.groupBox4.Controls.Add(this.label75);
            this.groupBox4.Controls.Add(this.label76);
            this.groupBox4.Controls.Add(this.label77);
            this.groupBox4.Controls.Add(this.label53);
            this.groupBox4.Controls.Add(this.label54);
            this.groupBox4.Controls.Add(this.label55);
            this.groupBox4.Controls.Add(this.label56);
            this.groupBox4.Controls.Add(this.label57);
            this.groupBox4.Controls.Add(this.label58);
            this.groupBox4.Controls.Add(this.label59);
            this.groupBox4.Controls.Add(this.label60);
            this.groupBox4.Controls.Add(this.label61);
            this.groupBox4.Controls.Add(this.label62);
            this.groupBox4.Controls.Add(this.label63);
            this.groupBox4.Controls.Add(this.label64);
            this.groupBox4.Controls.Add(this.label65);
            this.groupBox4.Controls.Add(this.label66);
            this.groupBox4.Controls.Add(this.label67);
            this.groupBox4.Controls.Add(this.label68);
            this.groupBox4.Controls.Add(this.label69);
            this.groupBox4.Controls.Add(this.label70);
            this.groupBox4.Controls.Add(this.label71);
            this.groupBox4.Controls.Add(this.label72);
            this.groupBox4.Location = new Point(8, 0xf4);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(0x2d1, 0x84);
            this.groupBox4.TabIndex = 0x77;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "生产线";
            this.label78.BorderStyle = BorderStyle.FixedSingle;
            this.label78.Location = new Point(0x264, 0x61);
            this.label78.Name = "label78";
            this.label78.Size = new Size(0x66, 0x15);
            this.label78.TabIndex = 0x85;
            this.label78.Text = "6M";
            this.label78.TextAlign = ContentAlignment.MiddleCenter;
            this.label79.BorderStyle = BorderStyle.FixedSingle;
            this.label79.Location = new Point(0x1ff, 0x61);
            this.label79.Name = "label79";
            this.label79.Size = new Size(0x66, 0x15);
            this.label79.TabIndex = 0x84;
            this.label79.Text = "1M/年";
            this.label79.TextAlign = ContentAlignment.MiddleCenter;
            this.label80.BorderStyle = BorderStyle.FixedSingle;
            this.label80.Location = new Point(0x264, 0x39);
            this.label80.Name = "label80";
            this.label80.Size = new Size(0x66, 0x15);
            this.label80.TabIndex = 0x83;
            this.label80.Text = "2M";
            this.label80.TextAlign = ContentAlignment.MiddleCenter;
            this.label81.BorderStyle = BorderStyle.FixedSingle;
            this.label81.Location = new Point(0x264, 0x4d);
            this.label81.Name = "label81";
            this.label81.Size = new Size(0x66, 0x15);
            this.label81.TabIndex = 130;
            this.label81.Text = "4M";
            this.label81.TextAlign = ContentAlignment.MiddleCenter;
            this.label82.BorderStyle = BorderStyle.FixedSingle;
            this.label82.Location = new Point(0x264, 0x25);
            this.label82.Name = "label82";
            this.label82.Size = new Size(0x66, 0x15);
            this.label82.TabIndex = 0x81;
            this.label82.Text = "1M";
            this.label82.TextAlign = ContentAlignment.MiddleCenter;
            this.label83.BorderStyle = BorderStyle.FixedSingle;
            this.label83.Location = new Point(0x264, 0x11);
            this.label83.Name = "label83";
            this.label83.Size = new Size(0x66, 0x15);
            this.label83.TabIndex = 0x80;
            this.label83.Text = "出售残值";
            this.label83.TextAlign = ContentAlignment.MiddleCenter;
            this.label84.BorderStyle = BorderStyle.FixedSingle;
            this.label84.Location = new Point(0x1ff, 0x39);
            this.label84.Name = "label84";
            this.label84.Size = new Size(0x66, 0x15);
            this.label84.TabIndex = 0x7f;
            this.label84.Text = "1M/年";
            this.label84.TextAlign = ContentAlignment.MiddleCenter;
            this.label85.BorderStyle = BorderStyle.FixedSingle;
            this.label85.Location = new Point(0x1ff, 0x4d);
            this.label85.Name = "label85";
            this.label85.Size = new Size(0x66, 0x15);
            this.label85.TabIndex = 0x7e;
            this.label85.Text = "1M/年";
            this.label85.TextAlign = ContentAlignment.MiddleCenter;
            this.label86.BorderStyle = BorderStyle.FixedSingle;
            this.label86.Location = new Point(0x1ff, 0x25);
            this.label86.Name = "label86";
            this.label86.Size = new Size(0x66, 0x15);
            this.label86.TabIndex = 0x7d;
            this.label86.Text = "1M/年";
            this.label86.TextAlign = ContentAlignment.MiddleCenter;
            this.label87.BorderStyle = BorderStyle.FixedSingle;
            this.label87.Location = new Point(0x1ff, 0x11);
            this.label87.Name = "label87";
            this.label87.Size = new Size(0x66, 0x15);
            this.label87.TabIndex = 0x7c;
            this.label87.Text = "维护费用";
            this.label87.TextAlign = ContentAlignment.MiddleCenter;
            this.label73.BorderStyle = BorderStyle.FixedSingle;
            this.label73.Location = new Point(410, 0x61);
            this.label73.Name = "label73";
            this.label73.Size = new Size(0x66, 0x15);
            this.label73.TabIndex = 0x7b;
            this.label73.Text = "无";
            this.label73.TextAlign = ContentAlignment.MiddleCenter;
            this.label74.BorderStyle = BorderStyle.FixedSingle;
            this.label74.Location = new Point(0x135, 0x61);
            this.label74.Name = "label74";
            this.label74.Size = new Size(0x66, 0x15);
            this.label74.TabIndex = 0x7a;
            this.label74.Text = "1季度";
            this.label74.TextAlign = ContentAlignment.MiddleCenter;
            this.label75.BorderStyle = BorderStyle.FixedSingle;
            this.label75.Location = new Point(0xd0, 0x61);
            this.label75.Name = "label75";
            this.label75.Size = new Size(0x66, 0x15);
            this.label75.TabIndex = 0x79;
            this.label75.Text = "4季度";
            this.label75.TextAlign = ContentAlignment.MiddleCenter;
            this.label76.BorderStyle = BorderStyle.FixedSingle;
            this.label76.Location = new Point(0x6b, 0x61);
            this.label76.Name = "label76";
            this.label76.Size = new Size(0x66, 0x15);
            this.label76.TabIndex = 120;
            this.label76.Text = "24M";
            this.label76.TextAlign = ContentAlignment.MiddleCenter;
            this.label77.BorderStyle = BorderStyle.FixedSingle;
            this.label77.Location = new Point(6, 0x61);
            this.label77.Name = "label77";
            this.label77.Size = new Size(0x66, 0x15);
            this.label77.TabIndex = 0x77;
            this.label77.Text = "柔性线";
            this.label77.TextAlign = ContentAlignment.MiddleCenter;
            this.label53.BorderStyle = BorderStyle.FixedSingle;
            this.label53.Location = new Point(410, 0x39);
            this.label53.Name = "label53";
            this.label53.Size = new Size(0x66, 0x15);
            this.label53.TabIndex = 0x76;
            this.label53.Text = "1季度";
            this.label53.TextAlign = ContentAlignment.MiddleCenter;
            this.label54.BorderStyle = BorderStyle.FixedSingle;
            this.label54.Location = new Point(410, 0x4d);
            this.label54.Name = "label54";
            this.label54.Size = new Size(0x66, 0x15);
            this.label54.TabIndex = 0x75;
            this.label54.Text = "2季度";
            this.label54.TextAlign = ContentAlignment.MiddleCenter;
            this.label55.BorderStyle = BorderStyle.FixedSingle;
            this.label55.Location = new Point(410, 0x25);
            this.label55.Name = "label55";
            this.label55.Size = new Size(0x66, 0x15);
            this.label55.TabIndex = 0x74;
            this.label55.Text = "无";
            this.label55.TextAlign = ContentAlignment.MiddleCenter;
            this.label56.BorderStyle = BorderStyle.FixedSingle;
            this.label56.Location = new Point(410, 0x11);
            this.label56.Name = "label56";
            this.label56.Size = new Size(0x66, 0x15);
            this.label56.TabIndex = 0x73;
            this.label56.Text = "转产周期";
            this.label56.TextAlign = ContentAlignment.MiddleCenter;
            this.label57.BorderStyle = BorderStyle.FixedSingle;
            this.label57.Location = new Point(0x135, 0x39);
            this.label57.Name = "label57";
            this.label57.Size = new Size(0x66, 0x15);
            this.label57.TabIndex = 0x72;
            this.label57.Text = "2季度";
            this.label57.TextAlign = ContentAlignment.MiddleCenter;
            this.label58.BorderStyle = BorderStyle.FixedSingle;
            this.label58.Location = new Point(0x135, 0x4d);
            this.label58.Name = "label58";
            this.label58.Size = new Size(0x66, 0x15);
            this.label58.TabIndex = 0x71;
            this.label58.Text = "1季度";
            this.label58.TextAlign = ContentAlignment.MiddleCenter;
            this.label59.BorderStyle = BorderStyle.FixedSingle;
            this.label59.Location = new Point(0x135, 0x25);
            this.label59.Name = "label59";
            this.label59.Size = new Size(0x66, 0x15);
            this.label59.TabIndex = 0x70;
            this.label59.Text = "3季度";
            this.label59.TextAlign = ContentAlignment.MiddleCenter;
            this.label60.BorderStyle = BorderStyle.FixedSingle;
            this.label60.Location = new Point(0x135, 0x11);
            this.label60.Name = "label60";
            this.label60.Size = new Size(0x66, 0x15);
            this.label60.TabIndex = 0x6f;
            this.label60.Text = "生产周期";
            this.label60.TextAlign = ContentAlignment.MiddleCenter;
            this.label61.BorderStyle = BorderStyle.FixedSingle;
            this.label61.Location = new Point(0xd0, 0x39);
            this.label61.Name = "label61";
            this.label61.Size = new Size(0x66, 0x15);
            this.label61.TabIndex = 110;
            this.label61.Text = "2季度";
            this.label61.TextAlign = ContentAlignment.MiddleCenter;
            this.label62.BorderStyle = BorderStyle.FixedSingle;
            this.label62.Location = new Point(0xd0, 0x4d);
            this.label62.Name = "label62";
            this.label62.Size = new Size(0x66, 0x15);
            this.label62.TabIndex = 0x6d;
            this.label62.Text = "4季度";
            this.label62.TextAlign = ContentAlignment.MiddleCenter;
            this.label63.BorderStyle = BorderStyle.FixedSingle;
            this.label63.Location = new Point(0xd0, 0x25);
            this.label63.Name = "label63";
            this.label63.Size = new Size(0x66, 0x15);
            this.label63.TabIndex = 0x6c;
            this.label63.Text = "无";
            this.label63.TextAlign = ContentAlignment.MiddleCenter;
            this.label64.BorderStyle = BorderStyle.FixedSingle;
            this.label64.Location = new Point(0xd0, 0x11);
            this.label64.Name = "label64";
            this.label64.Size = new Size(0x66, 0x15);
            this.label64.TabIndex = 0x6b;
            this.label64.Text = "安装周期";
            this.label64.TextAlign = ContentAlignment.MiddleCenter;
            this.label65.BorderStyle = BorderStyle.FixedSingle;
            this.label65.Location = new Point(0x6b, 0x39);
            this.label65.Name = "label65";
            this.label65.Size = new Size(0x66, 0x15);
            this.label65.TabIndex = 0x6a;
            this.label65.Text = "8M";
            this.label65.TextAlign = ContentAlignment.MiddleCenter;
            this.label66.BorderStyle = BorderStyle.FixedSingle;
            this.label66.Location = new Point(0x6b, 0x4d);
            this.label66.Name = "label66";
            this.label66.Size = new Size(0x66, 0x15);
            this.label66.TabIndex = 0x69;
            this.label66.Text = "16M";
            this.label66.TextAlign = ContentAlignment.MiddleCenter;
            this.label67.BorderStyle = BorderStyle.FixedSingle;
            this.label67.Location = new Point(0x6b, 0x25);
            this.label67.Name = "label67";
            this.label67.Size = new Size(0x66, 0x15);
            this.label67.TabIndex = 0x68;
            this.label67.Text = "5M";
            this.label67.TextAlign = ContentAlignment.MiddleCenter;
            this.label68.BorderStyle = BorderStyle.FixedSingle;
            this.label68.Location = new Point(0x6b, 0x11);
            this.label68.Name = "label68";
            this.label68.Size = new Size(0x66, 0x15);
            this.label68.TabIndex = 0x67;
            this.label68.Text = "购买价格";
            this.label68.TextAlign = ContentAlignment.MiddleCenter;
            this.label69.BorderStyle = BorderStyle.FixedSingle;
            this.label69.Location = new Point(6, 0x4d);
            this.label69.Name = "label69";
            this.label69.Size = new Size(0x66, 0x15);
            this.label69.TabIndex = 0x66;
            this.label69.Text = "全自动";
            this.label69.TextAlign = ContentAlignment.MiddleCenter;
            this.label70.BorderStyle = BorderStyle.FixedSingle;
            this.label70.Location = new Point(6, 0x39);
            this.label70.Name = "label70";
            this.label70.Size = new Size(0x66, 0x15);
            this.label70.TabIndex = 0x65;
            this.label70.Text = "半自动";
            this.label70.TextAlign = ContentAlignment.MiddleCenter;
            this.label71.BorderStyle = BorderStyle.FixedSingle;
            this.label71.Location = new Point(6, 0x25);
            this.label71.Name = "label71";
            this.label71.Size = new Size(0x66, 0x15);
            this.label71.TabIndex = 100;
            this.label71.Text = "手工线";
            this.label71.TextAlign = ContentAlignment.MiddleCenter;
            this.label72.BorderStyle = BorderStyle.FixedSingle;
            this.label72.Location = new Point(6, 0x11);
            this.label72.Name = "label72";
            this.label72.Size = new Size(0x66, 0x15);
            this.label72.TabIndex = 0x63;
            this.label72.Text = "生产线";
            this.label72.TextAlign = ContentAlignment.MiddleCenter;
            this.groupBox1.Controls.Add(this.label49);
            this.groupBox1.Controls.Add(this.label50);
            this.groupBox1.Controls.Add(this.label51);
            this.groupBox1.Controls.Add(this.label52);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.label7);
            this.groupBox1.Controls.Add(this.label8);
            this.groupBox1.Controls.Add(this.label9);
            this.groupBox1.Controls.Add(this.label10);
            this.groupBox1.Controls.Add(this.label11);
            this.groupBox1.Controls.Add(this.label12);
            this.groupBox1.Controls.Add(this.label45);
            this.groupBox1.Controls.Add(this.label46);
            this.groupBox1.Controls.Add(this.label47);
            this.groupBox1.Controls.Add(this.label48);
            this.groupBox1.Location = new Point(8, 0x7d);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0x207, 0x71);
            this.groupBox1.TabIndex = 0x74;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "产品生产与加工费";
            this.label49.BorderStyle = BorderStyle.FixedSingle;
            this.label49.Location = new Point(410, 0x39);
            this.label49.Name = "label49";
            this.label49.Size = new Size(0x66, 0x15);
            this.label49.TabIndex = 0x76;
            this.label49.Text = "1M";
            this.label49.TextAlign = ContentAlignment.MiddleCenter;
            this.label50.BorderStyle = BorderStyle.FixedSingle;
            this.label50.Location = new Point(410, 0x4d);
            this.label50.Name = "label50";
            this.label50.Size = new Size(0x66, 0x15);
            this.label50.TabIndex = 0x75;
            this.label50.Text = "5M";
            this.label50.TextAlign = ContentAlignment.MiddleCenter;
            this.label51.BorderStyle = BorderStyle.FixedSingle;
            this.label51.Location = new Point(410, 0x25);
            this.label51.Name = "label51";
            this.label51.Size = new Size(0x66, 0x15);
            this.label51.TabIndex = 0x74;
            this.label51.Text = "4M";
            this.label51.TextAlign = ContentAlignment.MiddleCenter;
            this.label52.BorderStyle = BorderStyle.FixedSingle;
            this.label52.Location = new Point(410, 0x11);
            this.label52.Name = "label52";
            this.label52.Size = new Size(0x66, 0x15);
            this.label52.TabIndex = 0x73;
            this.label52.Text = "P4";
            this.label52.TextAlign = ContentAlignment.MiddleCenter;
            this.label1.BorderStyle = BorderStyle.FixedSingle;
            this.label1.Location = new Point(0x135, 0x39);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x66, 0x15);
            this.label1.TabIndex = 0x72;
            this.label1.Text = "1M";
            this.label1.TextAlign = ContentAlignment.MiddleCenter;
            this.label2.BorderStyle = BorderStyle.FixedSingle;
            this.label2.Location = new Point(0x135, 0x4d);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x66, 0x15);
            this.label2.TabIndex = 0x71;
            this.label2.Text = "4M";
            this.label2.TextAlign = ContentAlignment.MiddleCenter;
            this.label3.BorderStyle = BorderStyle.FixedSingle;
            this.label3.Location = new Point(0x135, 0x25);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x66, 0x15);
            this.label3.TabIndex = 0x70;
            this.label3.Text = "3M";
            this.label3.TextAlign = ContentAlignment.MiddleCenter;
            this.label4.BorderStyle = BorderStyle.FixedSingle;
            this.label4.Location = new Point(0x135, 0x11);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x66, 0x15);
            this.label4.TabIndex = 0x6f;
            this.label4.Text = "P3";
            this.label4.TextAlign = ContentAlignment.MiddleCenter;
            this.label5.BorderStyle = BorderStyle.FixedSingle;
            this.label5.Location = new Point(0xd0, 0x39);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x66, 0x15);
            this.label5.TabIndex = 110;
            this.label5.Text = "1M";
            this.label5.TextAlign = ContentAlignment.MiddleCenter;
            this.label6.BorderStyle = BorderStyle.FixedSingle;
            this.label6.Location = new Point(0xd0, 0x4d);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x66, 0x15);
            this.label6.TabIndex = 0x6d;
            this.label6.Text = "3M";
            this.label6.TextAlign = ContentAlignment.MiddleCenter;
            this.label7.BorderStyle = BorderStyle.FixedSingle;
            this.label7.Location = new Point(0xd0, 0x25);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x66, 0x15);
            this.label7.TabIndex = 0x6c;
            this.label7.Text = "2M";
            this.label7.TextAlign = ContentAlignment.MiddleCenter;
            this.label8.BorderStyle = BorderStyle.FixedSingle;
            this.label8.Location = new Point(0xd0, 0x11);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x66, 0x15);
            this.label8.TabIndex = 0x6b;
            this.label8.Text = "P2";
            this.label8.TextAlign = ContentAlignment.MiddleCenter;
            this.label9.BorderStyle = BorderStyle.FixedSingle;
            this.label9.Location = new Point(0x6b, 0x39);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x66, 0x15);
            this.label9.TabIndex = 0x6a;
            this.label9.Text = "1M";
            this.label9.TextAlign = ContentAlignment.MiddleCenter;
            this.label10.BorderStyle = BorderStyle.FixedSingle;
            this.label10.Location = new Point(0x6b, 0x4d);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x66, 0x15);
            this.label10.TabIndex = 0x69;
            this.label10.Text = "2M";
            this.label10.TextAlign = ContentAlignment.MiddleCenter;
            this.label11.BorderStyle = BorderStyle.FixedSingle;
            this.label11.Location = new Point(0x6b, 0x25);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x66, 0x15);
            this.label11.TabIndex = 0x68;
            this.label11.Text = "1M";
            this.label11.TextAlign = ContentAlignment.MiddleCenter;
            this.label12.BorderStyle = BorderStyle.FixedSingle;
            this.label12.Location = new Point(0x6b, 0x11);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x66, 0x15);
            this.label12.TabIndex = 0x67;
            this.label12.Text = "P1";
            this.label12.TextAlign = ContentAlignment.MiddleCenter;
            this.label45.BorderStyle = BorderStyle.FixedSingle;
            this.label45.Location = new Point(6, 0x4d);
            this.label45.Name = "label45";
            this.label45.Size = new Size(0x66, 0x15);
            this.label45.TabIndex = 0x66;
            this.label45.Text = "合计";
            this.label45.TextAlign = ContentAlignment.MiddleCenter;
            this.label46.BorderStyle = BorderStyle.FixedSingle;
            this.label46.Location = new Point(6, 0x39);
            this.label46.Name = "label46";
            this.label46.Size = new Size(0x66, 0x15);
            this.label46.TabIndex = 0x65;
            this.label46.Text = "加工费";
            this.label46.TextAlign = ContentAlignment.MiddleCenter;
            this.label47.BorderStyle = BorderStyle.FixedSingle;
            this.label47.Location = new Point(6, 0x25);
            this.label47.Name = "label47";
            this.label47.Size = new Size(0x66, 0x15);
            this.label47.TabIndex = 100;
            this.label47.Text = "成本";
            this.label47.TextAlign = ContentAlignment.MiddleCenter;
            this.label48.BorderStyle = BorderStyle.FixedSingle;
            this.label48.Location = new Point(6, 0x11);
            this.label48.Name = "label48";
            this.label48.Size = new Size(0x66, 0x15);
            this.label48.TabIndex = 0x63;
            this.label48.Text = "产品";
            this.label48.TextAlign = ContentAlignment.MiddleCenter;
            this.groupBox2.Controls.Add(this.label13);
            this.groupBox2.Controls.Add(this.label14);
            this.groupBox2.Controls.Add(this.label15);
            this.groupBox2.Controls.Add(this.label16);
            this.groupBox2.Controls.Add(this.label17);
            this.groupBox2.Controls.Add(this.label18);
            this.groupBox2.Controls.Add(this.label19);
            this.groupBox2.Controls.Add(this.label20);
            this.groupBox2.Controls.Add(this.label21);
            this.groupBox2.Controls.Add(this.label22);
            this.groupBox2.Controls.Add(this.label23);
            this.groupBox2.Controls.Add(this.label24);
            this.groupBox2.Controls.Add(this.label25);
            this.groupBox2.Controls.Add(this.label26);
            this.groupBox2.Controls.Add(this.label27);
            this.groupBox2.Controls.Add(this.label28);
            this.groupBox2.Location = new Point(8, 6);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(0x1a1, 0x71);
            this.groupBox2.TabIndex = 0x73;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "建筑";
            this.label13.BorderStyle = BorderStyle.FixedSingle;
            this.label13.Location = new Point(0x135, 0x39);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x66, 0x15);
            this.label13.TabIndex = 0x72;
            this.label13.Text = "3条生产线";
            this.label13.TextAlign = ContentAlignment.MiddleCenter;
            this.label14.BorderStyle = BorderStyle.FixedSingle;
            this.label14.Location = new Point(0x135, 0x4d);
            this.label14.Name = "label14";
            this.label14.Size = new Size(0x66, 0x15);
            this.label14.TabIndex = 0x71;
            this.label14.Text = "1条生产线";
            this.label14.TextAlign = ContentAlignment.MiddleCenter;
            this.label15.BorderStyle = BorderStyle.FixedSingle;
            this.label15.Location = new Point(0x135, 0x25);
            this.label15.Name = "label15";
            this.label15.Size = new Size(0x66, 0x15);
            this.label15.TabIndex = 0x70;
            this.label15.Text = "4条生产线";
            this.label15.TextAlign = ContentAlignment.MiddleCenter;
            this.label16.BorderStyle = BorderStyle.FixedSingle;
            this.label16.Location = new Point(0x135, 0x11);
            this.label16.Name = "label16";
            this.label16.Size = new Size(0x66, 0x15);
            this.label16.TabIndex = 0x6f;
            this.label16.Text = "容量";
            this.label16.TextAlign = ContentAlignment.MiddleCenter;
            this.label17.BorderStyle = BorderStyle.FixedSingle;
            this.label17.Location = new Point(0xd0, 0x39);
            this.label17.Name = "label17";
            this.label17.Size = new Size(0x66, 0x15);
            this.label17.TabIndex = 110;
            this.label17.Text = "3M/年";
            this.label17.TextAlign = ContentAlignment.MiddleCenter;
            this.label18.BorderStyle = BorderStyle.FixedSingle;
            this.label18.Location = new Point(0xd0, 0x4d);
            this.label18.Name = "label18";
            this.label18.Size = new Size(0x66, 0x15);
            this.label18.TabIndex = 0x6d;
            this.label18.Text = "2M/年";
            this.label18.TextAlign = ContentAlignment.MiddleCenter;
            this.label19.BorderStyle = BorderStyle.FixedSingle;
            this.label19.Location = new Point(0xd0, 0x25);
            this.label19.Name = "label19";
            this.label19.Size = new Size(0x66, 0x15);
            this.label19.TabIndex = 0x6c;
            this.label19.Text = "4M/年";
            this.label19.TextAlign = ContentAlignment.MiddleCenter;
            this.label20.BorderStyle = BorderStyle.FixedSingle;
            this.label20.Location = new Point(0xd0, 0x11);
            this.label20.Name = "label20";
            this.label20.Size = new Size(0x66, 0x15);
            this.label20.TabIndex = 0x6b;
            this.label20.Text = "租赁";
            this.label20.TextAlign = ContentAlignment.MiddleCenter;
            this.label21.BorderStyle = BorderStyle.FixedSingle;
            this.label21.Location = new Point(0x6b, 0x39);
            this.label21.Name = "label21";
            this.label21.Size = new Size(0x66, 0x15);
            this.label21.TabIndex = 0x6a;
            this.label21.Text = "24M";
            this.label21.TextAlign = ContentAlignment.MiddleCenter;
            this.label22.BorderStyle = BorderStyle.FixedSingle;
            this.label22.Location = new Point(0x6b, 0x4d);
            this.label22.Name = "label22";
            this.label22.Size = new Size(0x66, 0x15);
            this.label22.TabIndex = 0x69;
            this.label22.Text = "12M";
            this.label22.TextAlign = ContentAlignment.MiddleCenter;
            this.label23.BorderStyle = BorderStyle.FixedSingle;
            this.label23.Location = new Point(0x6b, 0x25);
            this.label23.Name = "label23";
            this.label23.Size = new Size(0x66, 0x15);
            this.label23.TabIndex = 0x68;
            this.label23.Text = "32M";
            this.label23.TextAlign = ContentAlignment.MiddleCenter;
            this.label24.BorderStyle = BorderStyle.FixedSingle;
            this.label24.Location = new Point(0x6b, 0x11);
            this.label24.Name = "label24";
            this.label24.Size = new Size(0x66, 0x15);
            this.label24.TabIndex = 0x67;
            this.label24.Text = "购买";
            this.label24.TextAlign = ContentAlignment.MiddleCenter;
            this.label25.BorderStyle = BorderStyle.FixedSingle;
            this.label25.Location = new Point(6, 0x4d);
            this.label25.Name = "label25";
            this.label25.Size = new Size(0x66, 0x15);
            this.label25.TabIndex = 0x66;
            this.label25.Text = "厂房C";
            this.label25.TextAlign = ContentAlignment.MiddleCenter;
            this.label26.BorderStyle = BorderStyle.FixedSingle;
            this.label26.Location = new Point(6, 0x39);
            this.label26.Name = "label26";
            this.label26.Size = new Size(0x66, 0x15);
            this.label26.TabIndex = 0x65;
            this.label26.Text = "厂房B";
            this.label26.TextAlign = ContentAlignment.MiddleCenter;
            this.label27.BorderStyle = BorderStyle.FixedSingle;
            this.label27.Location = new Point(6, 0x25);
            this.label27.Name = "label27";
            this.label27.Size = new Size(0x66, 0x15);
            this.label27.TabIndex = 100;
            this.label27.Text = "厂房A";
            this.label27.TextAlign = ContentAlignment.MiddleCenter;
            this.label28.BorderStyle = BorderStyle.FixedSingle;
            this.label28.Location = new Point(6, 0x11);
            this.label28.Name = "label28";
            this.label28.Size = new Size(0x66, 0x15);
            this.label28.TabIndex = 0x63;
            this.label28.TextAlign = ContentAlignment.MiddleCenter;
            this.tabPage2.Controls.Add(this.pictureBox2);
            this.tabPage2.Controls.Add(this.groupBox6);
            this.tabPage2.Controls.Add(this.groupBox5);
            this.tabPage2.Controls.Add(this.groupBox3);
            this.tabPage2.Location = new Point(4, 0x18);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new Padding(3);
            this.tabPage2.Size = new Size(0x2e1, 0x19f);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "认证类";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.pictureBox2.Image = Resources.Run;
            this.pictureBox2.Location = new Point(0x20c, 0x20);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new Size(0x80, 0x80);
            this.pictureBox2.SizeMode = PictureBoxSizeMode.AutoSize;
            this.pictureBox2.TabIndex = 0x79;
            this.pictureBox2.TabStop = false;
            this.groupBox6.Controls.Add(this.label30);
            this.groupBox6.Controls.Add(this.label89);
            this.groupBox6.Controls.Add(this.label93);
            this.groupBox6.Controls.Add(this.label96);
            this.groupBox6.Controls.Add(this.label100);
            this.groupBox6.Controls.Add(this.label101);
            this.groupBox6.Controls.Add(this.label102);
            this.groupBox6.Controls.Add(this.label103);
            this.groupBox6.Controls.Add(this.label104);
            this.groupBox6.Controls.Add(this.label105);
            this.groupBox6.Controls.Add(this.label106);
            this.groupBox6.Controls.Add(this.label107);
            this.groupBox6.Controls.Add(this.label108);
            this.groupBox6.Controls.Add(this.label109);
            this.groupBox6.Controls.Add(this.label110);
            this.groupBox6.Controls.Add(this.label111);
            this.groupBox6.Controls.Add(this.label112);
            this.groupBox6.Controls.Add(this.label113);
            this.groupBox6.Controls.Add(this.label114);
            this.groupBox6.Controls.Add(this.label115);
            this.groupBox6.Location = new Point(8, 0xdd);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new Size(0x207, 0x71);
            this.groupBox6.TabIndex = 0x76;
            this.groupBox6.TabStop = false;
            this.groupBox6.Text = "新市场开拓与投资";
            this.label30.BorderStyle = BorderStyle.FixedSingle;
            this.label30.Location = new Point(410, 0x39);
            this.label30.Name = "label30";
            this.label30.Size = new Size(0x66, 0x15);
            this.label30.TabIndex = 0x76;
            this.label30.Text = "1M/年";
            this.label30.TextAlign = ContentAlignment.MiddleCenter;
            this.label89.BorderStyle = BorderStyle.FixedSingle;
            this.label89.Location = new Point(410, 0x4d);
            this.label89.Name = "label89";
            this.label89.Size = new Size(0x66, 0x15);
            this.label89.TabIndex = 0x75;
            this.label89.Text = "4M";
            this.label89.TextAlign = ContentAlignment.MiddleCenter;
            this.label93.BorderStyle = BorderStyle.FixedSingle;
            this.label93.Location = new Point(410, 0x25);
            this.label93.Name = "label93";
            this.label93.Size = new Size(0x66, 0x15);
            this.label93.TabIndex = 0x74;
            this.label93.Text = ">=4年";
            this.label93.TextAlign = ContentAlignment.MiddleCenter;
            this.label96.BorderStyle = BorderStyle.FixedSingle;
            this.label96.Location = new Point(410, 0x11);
            this.label96.Name = "label96";
            this.label96.Size = new Size(0x66, 0x15);
            this.label96.TabIndex = 0x73;
            this.label96.Text = "国际";
            this.label96.TextAlign = ContentAlignment.MiddleCenter;
            this.label100.BorderStyle = BorderStyle.FixedSingle;
            this.label100.Location = new Point(0x135, 0x39);
            this.label100.Name = "label100";
            this.label100.Size = new Size(0x66, 0x15);
            this.label100.TabIndex = 0x72;
            this.label100.Text = "1M/年";
            this.label100.TextAlign = ContentAlignment.MiddleCenter;
            this.label101.BorderStyle = BorderStyle.FixedSingle;
            this.label101.Location = new Point(0x135, 0x4d);
            this.label101.Name = "label101";
            this.label101.Size = new Size(0x66, 0x15);
            this.label101.TabIndex = 0x71;
            this.label101.Text = "3M";
            this.label101.TextAlign = ContentAlignment.MiddleCenter;
            this.label102.BorderStyle = BorderStyle.FixedSingle;
            this.label102.Location = new Point(0x135, 0x25);
            this.label102.Name = "label102";
            this.label102.Size = new Size(0x66, 0x15);
            this.label102.TabIndex = 0x70;
            this.label102.Text = ">=3年";
            this.label102.TextAlign = ContentAlignment.MiddleCenter;
            this.label103.BorderStyle = BorderStyle.FixedSingle;
            this.label103.Location = new Point(0x135, 0x11);
            this.label103.Name = "label103";
            this.label103.Size = new Size(0x66, 0x15);
            this.label103.TabIndex = 0x6f;
            this.label103.Text = "亚洲";
            this.label103.TextAlign = ContentAlignment.MiddleCenter;
            this.label104.BorderStyle = BorderStyle.FixedSingle;
            this.label104.Location = new Point(0xd0, 0x39);
            this.label104.Name = "label104";
            this.label104.Size = new Size(0x66, 0x15);
            this.label104.TabIndex = 110;
            this.label104.Text = "1M/年";
            this.label104.TextAlign = ContentAlignment.MiddleCenter;
            this.label105.BorderStyle = BorderStyle.FixedSingle;
            this.label105.Location = new Point(0xd0, 0x4d);
            this.label105.Name = "label105";
            this.label105.Size = new Size(0x66, 0x15);
            this.label105.TabIndex = 0x6d;
            this.label105.Text = "2M";
            this.label105.TextAlign = ContentAlignment.MiddleCenter;
            this.label106.BorderStyle = BorderStyle.FixedSingle;
            this.label106.Location = new Point(0xd0, 0x25);
            this.label106.Name = "label106";
            this.label106.Size = new Size(0x66, 0x15);
            this.label106.TabIndex = 0x6c;
            this.label106.Text = ">=2年";
            this.label106.TextAlign = ContentAlignment.MiddleCenter;
            this.label107.BorderStyle = BorderStyle.FixedSingle;
            this.label107.Location = new Point(0xd0, 0x11);
            this.label107.Name = "label107";
            this.label107.Size = new Size(0x66, 0x15);
            this.label107.TabIndex = 0x6b;
            this.label107.Text = "国内";
            this.label107.TextAlign = ContentAlignment.MiddleCenter;
            this.label108.BorderStyle = BorderStyle.FixedSingle;
            this.label108.Location = new Point(0x6b, 0x39);
            this.label108.Name = "label108";
            this.label108.Size = new Size(0x66, 0x15);
            this.label108.TabIndex = 0x6a;
            this.label108.Text = "1M/年";
            this.label108.TextAlign = ContentAlignment.MiddleCenter;
            this.label109.BorderStyle = BorderStyle.FixedSingle;
            this.label109.Location = new Point(0x6b, 0x4d);
            this.label109.Name = "label109";
            this.label109.Size = new Size(0x66, 0x15);
            this.label109.TabIndex = 0x69;
            this.label109.Text = "1M";
            this.label109.TextAlign = ContentAlignment.MiddleCenter;
            this.label110.BorderStyle = BorderStyle.FixedSingle;
            this.label110.Location = new Point(0x6b, 0x25);
            this.label110.Name = "label110";
            this.label110.Size = new Size(0x66, 0x15);
            this.label110.TabIndex = 0x68;
            this.label110.Text = ">=1年";
            this.label110.TextAlign = ContentAlignment.MiddleCenter;
            this.label111.BorderStyle = BorderStyle.FixedSingle;
            this.label111.Location = new Point(0x6b, 0x11);
            this.label111.Name = "label111";
            this.label111.Size = new Size(0x66, 0x15);
            this.label111.TabIndex = 0x67;
            this.label111.Text = "区域";
            this.label111.TextAlign = ContentAlignment.MiddleCenter;
            this.label112.BorderStyle = BorderStyle.FixedSingle;
            this.label112.Location = new Point(6, 0x4d);
            this.label112.Name = "label112";
            this.label112.Size = new Size(0x66, 0x15);
            this.label112.TabIndex = 0x66;
            this.label112.Text = "合计";
            this.label112.TextAlign = ContentAlignment.MiddleCenter;
            this.label113.BorderStyle = BorderStyle.FixedSingle;
            this.label113.Location = new Point(6, 0x39);
            this.label113.Name = "label113";
            this.label113.Size = new Size(0x66, 0x15);
            this.label113.TabIndex = 0x65;
            this.label113.Text = "投资规则";
            this.label113.TextAlign = ContentAlignment.MiddleCenter;
            this.label114.BorderStyle = BorderStyle.FixedSingle;
            this.label114.Location = new Point(6, 0x25);
            this.label114.Name = "label114";
            this.label114.Size = new Size(0x66, 0x15);
            this.label114.TabIndex = 100;
            this.label114.Text = "完成时间";
            this.label114.TextAlign = ContentAlignment.MiddleCenter;
            this.label115.BorderStyle = BorderStyle.FixedSingle;
            this.label115.Location = new Point(6, 0x11);
            this.label115.Name = "label115";
            this.label115.Size = new Size(0x66, 0x15);
            this.label115.TabIndex = 0x63;
            this.label115.Text = "市场";
            this.label115.TextAlign = ContentAlignment.MiddleCenter;
            this.groupBox5.Controls.Add(this.label29);
            this.groupBox5.Controls.Add(this.label31);
            this.groupBox5.Controls.Add(this.label32);
            this.groupBox5.Controls.Add(this.label88);
            this.groupBox5.Controls.Add(this.label90);
            this.groupBox5.Controls.Add(this.label91);
            this.groupBox5.Controls.Add(this.label92);
            this.groupBox5.Controls.Add(this.label94);
            this.groupBox5.Controls.Add(this.label95);
            this.groupBox5.Controls.Add(this.label97);
            this.groupBox5.Controls.Add(this.label98);
            this.groupBox5.Controls.Add(this.label99);
            this.groupBox5.Location = new Point(8, 0x7d);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new Size(0x1a1, 90);
            this.groupBox5.TabIndex = 0x75;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "产品研发投资周期";
            this.label29.BorderStyle = BorderStyle.FixedSingle;
            this.label29.Location = new Point(0x135, 0x39);
            this.label29.Name = "label29";
            this.label29.Size = new Size(0x66, 0x15);
            this.label29.TabIndex = 0x72;
            this.label29.Text = "18M";
            this.label29.TextAlign = ContentAlignment.MiddleCenter;
            this.label31.BorderStyle = BorderStyle.FixedSingle;
            this.label31.Location = new Point(0x135, 0x25);
            this.label31.Name = "label31";
            this.label31.Size = new Size(0x66, 0x15);
            this.label31.TabIndex = 0x70;
            this.label31.Text = "1.5年(6季度)";
            this.label31.TextAlign = ContentAlignment.MiddleCenter;
            this.label32.BorderStyle = BorderStyle.FixedSingle;
            this.label32.Location = new Point(0x135, 0x11);
            this.label32.Name = "label32";
            this.label32.Size = new Size(0x66, 0x15);
            this.label32.TabIndex = 0x6f;
            this.label32.Text = "P4";
            this.label32.TextAlign = ContentAlignment.MiddleCenter;
            this.label88.BorderStyle = BorderStyle.FixedSingle;
            this.label88.Location = new Point(0xd0, 0x39);
            this.label88.Name = "label88";
            this.label88.Size = new Size(0x66, 0x15);
            this.label88.TabIndex = 110;
            this.label88.Text = "12M";
            this.label88.TextAlign = ContentAlignment.MiddleCenter;
            this.label90.BorderStyle = BorderStyle.FixedSingle;
            this.label90.Location = new Point(0xd0, 0x25);
            this.label90.Name = "label90";
            this.label90.Size = new Size(0x66, 0x15);
            this.label90.TabIndex = 0x6c;
            this.label90.Text = "1.5年(6季度)";
            this.label90.TextAlign = ContentAlignment.MiddleCenter;
            this.label91.BorderStyle = BorderStyle.FixedSingle;
            this.label91.Location = new Point(0xd0, 0x11);
            this.label91.Name = "label91";
            this.label91.Size = new Size(0x66, 0x15);
            this.label91.TabIndex = 0x6b;
            this.label91.Text = "P3";
            this.label91.TextAlign = ContentAlignment.MiddleCenter;
            this.label92.BorderStyle = BorderStyle.FixedSingle;
            this.label92.Location = new Point(0x6b, 0x39);
            this.label92.Name = "label92";
            this.label92.Size = new Size(0x66, 0x15);
            this.label92.TabIndex = 0x6a;
            this.label92.Text = "6M";
            this.label92.TextAlign = ContentAlignment.MiddleCenter;
            this.label94.BorderStyle = BorderStyle.FixedSingle;
            this.label94.Location = new Point(0x6b, 0x25);
            this.label94.Name = "label94";
            this.label94.Size = new Size(0x66, 0x15);
            this.label94.TabIndex = 0x68;
            this.label94.Text = "1.5年(6季度)";
            this.label94.TextAlign = ContentAlignment.MiddleCenter;
            this.label95.BorderStyle = BorderStyle.FixedSingle;
            this.label95.Location = new Point(0x6b, 0x11);
            this.label95.Name = "label95";
            this.label95.Size = new Size(0x66, 0x15);
            this.label95.TabIndex = 0x67;
            this.label95.Text = "P2";
            this.label95.TextAlign = ContentAlignment.MiddleCenter;
            this.label97.BorderStyle = BorderStyle.FixedSingle;
            this.label97.Location = new Point(6, 0x39);
            this.label97.Name = "label97";
            this.label97.Size = new Size(0x66, 0x15);
            this.label97.TabIndex = 0x65;
            this.label97.Text = "开发投资";
            this.label97.TextAlign = ContentAlignment.MiddleCenter;
            this.label98.BorderStyle = BorderStyle.FixedSingle;
            this.label98.Location = new Point(6, 0x25);
            this.label98.Name = "label98";
            this.label98.Size = new Size(0x66, 0x15);
            this.label98.TabIndex = 100;
            this.label98.Text = "周期";
            this.label98.TextAlign = ContentAlignment.MiddleCenter;
            this.label99.BorderStyle = BorderStyle.FixedSingle;
            this.label99.Location = new Point(6, 0x11);
            this.label99.Name = "label99";
            this.label99.Size = new Size(0x66, 0x15);
            this.label99.TabIndex = 0x63;
            this.label99.Text = "产品";
            this.label99.TextAlign = ContentAlignment.MiddleCenter;
            this.groupBox3.Controls.Add(this.label33);
            this.groupBox3.Controls.Add(this.label34);
            this.groupBox3.Controls.Add(this.label35);
            this.groupBox3.Controls.Add(this.label116);
            this.groupBox3.Controls.Add(this.label118);
            this.groupBox3.Controls.Add(this.label152);
            this.groupBox3.Controls.Add(this.label153);
            this.groupBox3.Controls.Add(this.label151);
            this.groupBox3.Controls.Add(this.label119);
            this.groupBox3.Controls.Add(this.label154);
            this.groupBox3.Controls.Add(this.label121);
            this.groupBox3.Controls.Add(this.label120);
            this.groupBox3.Location = new Point(8, 6);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(0x13f, 0x71);
            this.groupBox3.TabIndex = 0x74;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "资格认证";
            this.label33.BorderStyle = BorderStyle.FixedSingle;
            this.label33.Location = new Point(0xd0, 0x4d);
            this.label33.Name = "label33";
            this.label33.Size = new Size(0x66, 0x15);
            this.label33.TabIndex = 0x7a;
            this.label33.Text = "4M";
            this.label33.TextAlign = ContentAlignment.MiddleCenter;
            this.label34.BorderStyle = BorderStyle.FixedSingle;
            this.label34.Location = new Point(6, 0x4d);
            this.label34.Name = "label34";
            this.label34.Size = new Size(0x66, 0x15);
            this.label34.TabIndex = 120;
            this.label34.Text = "合计";
            this.label34.TextAlign = ContentAlignment.MiddleCenter;
            this.label35.BorderStyle = BorderStyle.FixedSingle;
            this.label35.Location = new Point(0x6b, 0x4d);
            this.label35.Name = "label35";
            this.label35.Size = new Size(0x66, 0x15);
            this.label35.TabIndex = 0x79;
            this.label35.Text = "2M";
            this.label35.TextAlign = ContentAlignment.MiddleCenter;
            this.label116.BorderStyle = BorderStyle.FixedSingle;
            this.label116.Location = new Point(0xd0, 0x39);
            this.label116.Name = "label116";
            this.label116.Size = new Size(0x66, 0x15);
            this.label116.TabIndex = 0x77;
            this.label116.Text = "1M/年";
            this.label116.TextAlign = ContentAlignment.MiddleCenter;
            this.label118.BorderStyle = BorderStyle.FixedSingle;
            this.label118.Location = new Point(0xd0, 0x25);
            this.label118.Name = "label118";
            this.label118.Size = new Size(0x66, 0x15);
            this.label118.TabIndex = 0x76;
            this.label118.Text = ">=4M年";
            this.label118.TextAlign = ContentAlignment.MiddleCenter;
            this.label152.BorderStyle = BorderStyle.FixedSingle;
            this.label152.Location = new Point(6, 0x39);
            this.label152.Name = "label152";
            this.label152.Size = new Size(0x66, 0x15);
            this.label152.TabIndex = 0x71;
            this.label152.Text = "认证投资规则";
            this.label152.TextAlign = ContentAlignment.MiddleCenter;
            this.label153.BorderStyle = BorderStyle.FixedSingle;
            this.label153.Location = new Point(6, 0x25);
            this.label153.Name = "label153";
            this.label153.Size = new Size(0x66, 0x15);
            this.label153.TabIndex = 0x70;
            this.label153.Text = "认证时间";
            this.label153.TextAlign = ContentAlignment.MiddleCenter;
            this.label151.BorderStyle = BorderStyle.FixedSingle;
            this.label151.Location = new Point(0x6b, 0x11);
            this.label151.Name = "label151";
            this.label151.Size = new Size(0x66, 0x15);
            this.label151.TabIndex = 0x72;
            this.label151.Text = "ISO9000";
            this.label151.TextAlign = ContentAlignment.MiddleCenter;
            this.label119.BorderStyle = BorderStyle.FixedSingle;
            this.label119.Location = new Point(0xd0, 0x11);
            this.label119.Name = "label119";
            this.label119.Size = new Size(0x66, 0x15);
            this.label119.TabIndex = 0x75;
            this.label119.Text = "ISO14000";
            this.label119.TextAlign = ContentAlignment.MiddleCenter;
            this.label154.BorderStyle = BorderStyle.FixedSingle;
            this.label154.Location = new Point(6, 0x11);
            this.label154.Name = "label154";
            this.label154.Size = new Size(0x66, 0x15);
            this.label154.TabIndex = 0x6f;
            this.label154.Text = "管理体系";
            this.label154.TextAlign = ContentAlignment.MiddleCenter;
            this.label121.BorderStyle = BorderStyle.FixedSingle;
            this.label121.Location = new Point(0x6b, 0x25);
            this.label121.Name = "label121";
            this.label121.Size = new Size(0x66, 0x15);
            this.label121.TabIndex = 0x73;
            this.label121.Text = ">=2年";
            this.label121.TextAlign = ContentAlignment.MiddleCenter;
            this.label120.BorderStyle = BorderStyle.FixedSingle;
            this.label120.Location = new Point(0x6b, 0x39);
            this.label120.Name = "label120";
            this.label120.Size = new Size(0x66, 0x15);
            this.label120.TabIndex = 0x74;
            this.label120.Text = "1M/年";
            this.label120.TextAlign = ContentAlignment.MiddleCenter;
            this.tabPage3.Controls.Add(this.groupBox8);
            this.tabPage3.Controls.Add(this.pictureBox3);
            this.tabPage3.Controls.Add(this.groupBox7);
            this.tabPage3.Location = new Point(4, 0x18);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new Padding(3);
            this.tabPage3.Size = new Size(0x2e1, 0x19f);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "贷款类";
            this.tabPage3.UseVisualStyleBackColor = true;
            this.groupBox8.Controls.Add(this.richTextBox1);
            this.groupBox8.Controls.Add(this.label36);
            this.groupBox8.Location = new Point(6, 0x90);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new Size(0x19b, 0x59);
            this.groupBox8.TabIndex = 0x7a;
            this.groupBox8.TabStop = false;
            this.groupBox8.Text = "六年末注意事项";
            this.richTextBox1.BorderStyle = BorderStyle.None;
            this.richTextBox1.Dock = DockStyle.Fill;
            this.richTextBox1.Location = new Point(3, 0x11);
            this.richTextBox1.Name = "richTextBox1";
            this.richTextBox1.ReadOnly = true;
            this.richTextBox1.Size = new Size(0x195, 0x45);
            this.richTextBox1.TabIndex = 1;
            this.richTextBox1.Text = "\n    所有的短贷和高利贷原则上都要还清，否则就减掉发展能力相应分数。长贷按接手时的数额40M要求，以40M为界，不到40M加分，多则减分。";
            this.label36.AutoSize = true;
            this.label36.Location = new Point(20, 0x1f);
            this.label36.Name = "label36";
            this.label36.Size = new Size(0, 12);
            this.label36.TabIndex = 0;
            this.pictureBox3.Image = Resources.png0273;
            this.pictureBox3.Location = new Point(0x1eb, 0xa1);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new Size(0x80, 0x80);
            this.pictureBox3.SizeMode = PictureBoxSizeMode.AutoSize;
            this.pictureBox3.TabIndex = 0x79;
            this.pictureBox3.TabStop = false;
            this.groupBox7.Controls.Add(this.label117);
            this.groupBox7.Controls.Add(this.label122);
            this.groupBox7.Controls.Add(this.label123);
            this.groupBox7.Controls.Add(this.label124);
            this.groupBox7.Controls.Add(this.label125);
            this.groupBox7.Controls.Add(this.label126);
            this.groupBox7.Controls.Add(this.label127);
            this.groupBox7.Controls.Add(this.label128);
            this.groupBox7.Controls.Add(this.label129);
            this.groupBox7.Controls.Add(this.label130);
            this.groupBox7.Controls.Add(this.label131);
            this.groupBox7.Controls.Add(this.label132);
            this.groupBox7.Controls.Add(this.label133);
            this.groupBox7.Controls.Add(this.label134);
            this.groupBox7.Controls.Add(this.label135);
            this.groupBox7.Controls.Add(this.label136);
            this.groupBox7.Controls.Add(this.label137);
            this.groupBox7.Controls.Add(this.label138);
            this.groupBox7.Controls.Add(this.label139);
            this.groupBox7.Controls.Add(this.label140);
            this.groupBox7.Controls.Add(this.label141);
            this.groupBox7.Controls.Add(this.label142);
            this.groupBox7.Controls.Add(this.label143);
            this.groupBox7.Controls.Add(this.label144);
            this.groupBox7.Controls.Add(this.label145);
            this.groupBox7.Controls.Add(this.label146);
            this.groupBox7.Controls.Add(this.label147);
            this.groupBox7.Controls.Add(this.label148);
            this.groupBox7.Controls.Add(this.label149);
            this.groupBox7.Controls.Add(this.label150);
            this.groupBox7.Location = new Point(6, 6);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new Size(0x287, 0x84);
            this.groupBox7.TabIndex = 120;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "生产线";
            this.label117.BorderStyle = BorderStyle.FixedSingle;
            this.label117.Location = new Point(0x21a, 0x61);
            this.label117.Name = "label117";
            this.label117.Size = new Size(0x66, 0x15);
            this.label117.TabIndex = 0x84;
            this.label117.Text = "------";
            this.label117.TextAlign = ContentAlignment.MiddleCenter;
            this.label122.BorderStyle = BorderStyle.FixedSingle;
            this.label122.Location = new Point(0x21a, 0x39);
            this.label122.Name = "label122";
            this.label122.Size = new Size(0x66, 0x15);
            this.label122.TabIndex = 0x7f;
            this.label122.Text = "1年";
            this.label122.TextAlign = ContentAlignment.MiddleCenter;
            this.label123.BorderStyle = BorderStyle.FixedSingle;
            this.label123.Location = new Point(0x21a, 0x4d);
            this.label123.Name = "label123";
            this.label123.Size = new Size(0x66, 0x15);
            this.label123.TabIndex = 0x7e;
            this.label123.Text = "1年";
            this.label123.TextAlign = ContentAlignment.MiddleCenter;
            this.label124.BorderStyle = BorderStyle.FixedSingle;
            this.label124.Location = new Point(0x21a, 0x25);
            this.label124.Name = "label124";
            this.label124.Size = new Size(0x66, 0x15);
            this.label124.TabIndex = 0x7d;
            this.label124.Text = "5年";
            this.label124.TextAlign = ContentAlignment.MiddleCenter;
            this.label125.BorderStyle = BorderStyle.FixedSingle;
            this.label125.Location = new Point(0x21a, 0x11);
            this.label125.Name = "label125";
            this.label125.Size = new Size(0x66, 0x15);
            this.label125.TabIndex = 0x7c;
            this.label125.Text = "贷款期限";
            this.label125.TextAlign = ContentAlignment.MiddleCenter;
            this.label126.BorderStyle = BorderStyle.FixedSingle;
            this.label126.Location = new Point(410, 0x61);
            this.label126.Name = "label126";
            this.label126.Size = new Size(0x81, 0x15);
            this.label126.TabIndex = 0x7b;
            this.label126.Text = "变现时贴息";
            this.label126.TextAlign = ContentAlignment.MiddleCenter;
            this.label127.BorderStyle = BorderStyle.FixedSingle;
            this.label127.Location = new Point(0x135, 0x61);
            this.label127.Name = "label127";
            this.label127.Size = new Size(0x66, 0x15);
            this.label127.TabIndex = 0x7a;
            this.label127.Text = "1：6";
            this.label127.TextAlign = ContentAlignment.MiddleCenter;
            this.label128.BorderStyle = BorderStyle.FixedSingle;
            this.label128.Location = new Point(0xd0, 0x61);
            this.label128.Name = "label128";
            this.label128.Size = new Size(0x66, 0x15);
            this.label128.TabIndex = 0x79;
            this.label128.Text = "视应收款额";
            this.label128.TextAlign = ContentAlignment.MiddleCenter;
            this.label129.BorderStyle = BorderStyle.FixedSingle;
            this.label129.Location = new Point(0x6b, 0x61);
            this.label129.Name = "label129";
            this.label129.Size = new Size(0x66, 0x15);
            this.label129.TabIndex = 120;
            this.label129.Text = "任何时间";
            this.label129.TextAlign = ContentAlignment.MiddleCenter;
            this.label130.BorderStyle = BorderStyle.FixedSingle;
            this.label130.Location = new Point(6, 0x61);
            this.label130.Name = "label130";
            this.label130.Size = new Size(0x66, 0x15);
            this.label130.TabIndex = 0x77;
            this.label130.Text = "资金贴现";
            this.label130.TextAlign = ContentAlignment.MiddleCenter;
            this.label131.BorderStyle = BorderStyle.FixedSingle;
            this.label131.Location = new Point(410, 0x39);
            this.label131.Name = "label131";
            this.label131.Size = new Size(0x81, 0x15);
            this.label131.TabIndex = 0x76;
            this.label131.Text = "到期一次还本、付息";
            this.label131.TextAlign = ContentAlignment.MiddleCenter;
            this.label132.BorderStyle = BorderStyle.FixedSingle;
            this.label132.Location = new Point(410, 0x4d);
            this.label132.Name = "label132";
            this.label132.Size = new Size(0x81, 0x15);
            this.label132.TabIndex = 0x75;
            this.label132.Text = "到期一次还本、付息";
            this.label132.TextAlign = ContentAlignment.MiddleCenter;
            this.label133.BorderStyle = BorderStyle.FixedSingle;
            this.label133.Location = new Point(410, 0x25);
            this.label133.Name = "label133";
            this.label133.Size = new Size(0x81, 0x15);
            this.label133.TabIndex = 0x74;
            this.label133.Text = "年底付息，到期还本";
            this.label133.TextAlign = ContentAlignment.MiddleCenter;
            this.label134.BorderStyle = BorderStyle.FixedSingle;
            this.label134.Location = new Point(410, 0x11);
            this.label134.Name = "label134";
            this.label134.Size = new Size(0x81, 0x15);
            this.label134.TabIndex = 0x73;
            this.label134.Text = "还款方式";
            this.label134.TextAlign = ContentAlignment.MiddleCenter;
            this.label135.BorderStyle = BorderStyle.FixedSingle;
            this.label135.Location = new Point(0x135, 0x39);
            this.label135.Name = "label135";
            this.label135.Size = new Size(0x66, 0x15);
            this.label135.TabIndex = 0x72;
            this.label135.Text = "5%";
            this.label135.TextAlign = ContentAlignment.MiddleCenter;
            this.label136.BorderStyle = BorderStyle.FixedSingle;
            this.label136.Location = new Point(0x135, 0x4d);
            this.label136.Name = "label136";
            this.label136.Size = new Size(0x66, 0x15);
            this.label136.TabIndex = 0x71;
            this.label136.Text = "20%";
            this.label136.TextAlign = ContentAlignment.MiddleCenter;
            this.label137.BorderStyle = BorderStyle.FixedSingle;
            this.label137.Location = new Point(0x135, 0x25);
            this.label137.Name = "label137";
            this.label137.Size = new Size(0x66, 0x15);
            this.label137.TabIndex = 0x70;
            this.label137.Text = "10%";
            this.label137.TextAlign = ContentAlignment.MiddleCenter;
            this.label138.BorderStyle = BorderStyle.FixedSingle;
            this.label138.Location = new Point(0x135, 0x11);
            this.label138.Name = "label138";
            this.label138.Size = new Size(0x66, 0x15);
            this.label138.TabIndex = 0x6f;
            this.label138.Text = "年息";
            this.label138.TextAlign = ContentAlignment.MiddleCenter;
            this.label139.BorderStyle = BorderStyle.FixedSingle;
            this.label139.Location = new Point(0xd0, 0x39);
            this.label139.Name = "label139";
            this.label139.Size = new Size(0x66, 0x15);
            this.label139.TabIndex = 110;
            this.label139.Text = "上年权益的2倍";
            this.label139.TextAlign = ContentAlignment.MiddleCenter;
            this.label140.BorderStyle = BorderStyle.FixedSingle;
            this.label140.Location = new Point(0xd0, 0x4d);
            this.label140.Name = "label140";
            this.label140.Size = new Size(0x66, 0x15);
            this.label140.TabIndex = 0x6d;
            this.label140.Text = "上年权益的3倍";
            this.label140.TextAlign = ContentAlignment.MiddleCenter;
            this.label141.BorderStyle = BorderStyle.FixedSingle;
            this.label141.Location = new Point(0xd0, 0x25);
            this.label141.Name = "label141";
            this.label141.Size = new Size(0x66, 0x15);
            this.label141.TabIndex = 0x6c;
            this.label141.Text = "上年权益的2倍";
            this.label141.TextAlign = ContentAlignment.MiddleCenter;
            this.label142.BorderStyle = BorderStyle.FixedSingle;
            this.label142.Location = new Point(0xd0, 0x11);
            this.label142.Name = "label142";
            this.label142.Size = new Size(0x66, 0x15);
            this.label142.TabIndex = 0x6b;
            this.label142.Text = "贷款额度";
            this.label142.TextAlign = ContentAlignment.MiddleCenter;
            this.label143.BorderStyle = BorderStyle.FixedSingle;
            this.label143.Location = new Point(0x6b, 0x39);
            this.label143.Name = "label143";
            this.label143.Size = new Size(0x66, 0x15);
            this.label143.TabIndex = 0x6a;
            this.label143.Text = "每季度初";
            this.label143.TextAlign = ContentAlignment.MiddleCenter;
            this.label144.BorderStyle = BorderStyle.FixedSingle;
            this.label144.Location = new Point(0x6b, 0x4d);
            this.label144.Name = "label144";
            this.label144.Size = new Size(0x66, 0x15);
            this.label144.TabIndex = 0x69;
            this.label144.Text = "每季度初";
            this.label144.TextAlign = ContentAlignment.MiddleCenter;
            this.label145.BorderStyle = BorderStyle.FixedSingle;
            this.label145.Location = new Point(0x6b, 0x25);
            this.label145.Name = "label145";
            this.label145.Size = new Size(0x66, 0x15);
            this.label145.TabIndex = 0x68;
            this.label145.Text = "每年年末";
            this.label145.TextAlign = ContentAlignment.MiddleCenter;
            this.label146.BorderStyle = BorderStyle.FixedSingle;
            this.label146.Location = new Point(0x6b, 0x11);
            this.label146.Name = "label146";
            this.label146.Size = new Size(0x66, 0x15);
            this.label146.TabIndex = 0x67;
            this.label146.Text = "贷款时间";
            this.label146.TextAlign = ContentAlignment.MiddleCenter;
            this.label147.BorderStyle = BorderStyle.FixedSingle;
            this.label147.Location = new Point(6, 0x4d);
            this.label147.Name = "label147";
            this.label147.Size = new Size(0x66, 0x15);
            this.label147.TabIndex = 0x66;
            this.label147.Text = "高利贷款";
            this.label147.TextAlign = ContentAlignment.MiddleCenter;
            this.label148.BorderStyle = BorderStyle.FixedSingle;
            this.label148.Location = new Point(6, 0x39);
            this.label148.Name = "label148";
            this.label148.Size = new Size(0x66, 0x15);
            this.label148.TabIndex = 0x65;
            this.label148.Text = "短期贷款";
            this.label148.TextAlign = ContentAlignment.MiddleCenter;
            this.label149.BorderStyle = BorderStyle.FixedSingle;
            this.label149.Location = new Point(6, 0x25);
            this.label149.Name = "label149";
            this.label149.Size = new Size(0x66, 0x15);
            this.label149.TabIndex = 100;
            this.label149.Text = "长期贷款";
            this.label149.TextAlign = ContentAlignment.MiddleCenter;
            this.label150.BorderStyle = BorderStyle.FixedSingle;
            this.label150.Location = new Point(6, 0x11);
            this.label150.Name = "label150";
            this.label150.Size = new Size(0x66, 0x15);
            this.label150.TabIndex = 0x63;
            this.label150.Text = "贷款规则";
            this.label150.TextAlign = ContentAlignment.MiddleCenter;
            this.tabPage4.Controls.Add(this.pictureBox4);
            this.tabPage4.Controls.Add(this.groupBox10);
            this.tabPage4.Controls.Add(this.groupBox9);
            this.tabPage4.Location = new Point(4, 0x18);
            this.tabPage4.Name = "tabPage4";
            this.tabPage4.Size = new Size(0x2e1, 0x19f);
            this.tabPage4.TabIndex = 3;
            this.tabPage4.Text = "评分类";
            this.tabPage4.UseVisualStyleBackColor = true;
            this.pictureBox4.Image = Resources.PingFen;
            this.pictureBox4.Location = new Point(0x23d, 0x17);
            this.pictureBox4.Name = "pictureBox4";
            this.pictureBox4.Size = new Size(0x80, 0x80);
            this.pictureBox4.SizeMode = PictureBoxSizeMode.AutoSize;
            this.pictureBox4.TabIndex = 0x7c;
            this.pictureBox4.TabStop = false;
            this.groupBox10.Controls.Add(this.richTextBox3);
            this.groupBox10.Controls.Add(this.label37);
            this.groupBox10.Location = new Point(6, 0x124);
            this.groupBox10.Name = "groupBox10";
            this.groupBox10.Size = new Size(0x20e, 70);
            this.groupBox10.TabIndex = 0x7b;
            this.groupBox10.TabStop = false;
            this.groupBox10.Text = "其他";
            this.richTextBox3.BorderStyle = BorderStyle.None;
            this.richTextBox3.Dock = DockStyle.Fill;
            this.richTextBox3.Location = new Point(3, 0x11);
            this.richTextBox3.Name = "richTextBox3";
            this.richTextBox3.ReadOnly = true;
            this.richTextBox3.Size = new Size(520, 50);
            this.richTextBox3.TabIndex = 1;
            this.richTextBox3.Text = "\n    判断结束的原则是：当现金流或权益为负时系统判定对抗失败。";
            this.label37.AutoSize = true;
            this.label37.Location = new Point(20, 0x1f);
            this.label37.Name = "label37";
            this.label37.Size = new Size(0, 12);
            this.label37.TabIndex = 0;
            this.groupBox9.Controls.Add(this.richTextBox2);
            this.groupBox9.Location = new Point(6, 6);
            this.groupBox9.Name = "groupBox9";
            this.groupBox9.Size = new Size(0x20e, 280);
            this.groupBox9.TabIndex = 0;
            this.groupBox9.TabStop = false;
            this.groupBox9.Text = "计分标准";
            this.richTextBox2.BorderStyle = BorderStyle.None;
            this.richTextBox2.Dock = DockStyle.Fill;
            this.richTextBox2.Location = new Point(3, 0x11);
            this.richTextBox2.Name = "richTextBox2";
            this.richTextBox2.ReadOnly = true;
            this.richTextBox2.Size = new Size(520, 260);
            this.richTextBox2.TabIndex = 2;
            this.richTextBox2.Text = manager.GetString("richTextBox2.Text");
            this.panel1.Controls.Add(this.button1);
            this.panel1.Dock = DockStyle.Bottom;
            this.panel1.Location = new Point(0, 0x197);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(0x2e9, 0x24);
            this.panel1.TabIndex = 1;
            this.button1.DialogResult = DialogResult.OK;
            this.button1.Location = new Point(0x28b, 6);
            this.button1.Name = "button1";
            this.button1.Size = new Size(0x4b, 0x17);
            this.button1.TabIndex = 0;
            this.button1.Text = "确定";
            this.button1.UseVisualStyleBackColor = true;
            base.AcceptButton = this.button1;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(0x2e9, 0x1bb);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.tabControl1);
            base.FormBorderStyle = FormBorderStyle.FixedDialog;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmHelp";
            base.ShowInTaskbar = false;
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "沙盘模拟对抗规则表";
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            ((ISupportInitialize) this.pictureBox1).EndInit();
            this.groupBox4.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            ((ISupportInitialize) this.pictureBox2).EndInit();
            this.groupBox6.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.tabPage3.ResumeLayout(false);
            this.tabPage3.PerformLayout();
            this.groupBox8.ResumeLayout(false);
            this.groupBox8.PerformLayout();
            ((ISupportInitialize) this.pictureBox3).EndInit();
            this.groupBox7.ResumeLayout(false);
            this.tabPage4.ResumeLayout(false);
            this.tabPage4.PerformLayout();
            ((ISupportInitialize) this.pictureBox4).EndInit();
            this.groupBox10.ResumeLayout(false);
            this.groupBox10.PerformLayout();
            this.groupBox9.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            base.ResumeLayout(false);
        }
    }
}

