namespace ERPChess
{
    using BusinessTier;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class frmShowBusinessResult : Form
    {
        private IContainer components;
        private Button button1;
        private TabControl tabControl;
        private TabPage tabPage2;
        private ComboBox comboBox1;
        private Label label188;
        private GroupBox groupBox2;
        private Label label031;
        private Label label043;
        private Label label042;
        private Label label041;
        private Label label039;
        private Label label038;
        private Label label037;
        private Label label036;
        private Label label035;
        private Label label034;
        private Label label033;
        private Label label032;
        private Label label15;
        private Label label12;
        private Label label13;
        private Label label9;
        private Label label10;
        private Label label11;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label4;
        private Label label1;
        private Label label5;
        private Label label2;
        private GroupBox groupBox3;
        private Label label3;
        private Label label064;
        private Label label18;
        private Label label054;
        private Label label20;
        private Label label21;
        private Label label22;
        private Label label053;
        private Label label24;
        private Label label063;
        private Label label26;
        private Label label052;
        private Label label28;
        private Label label062;
        private Label label43;
        private Label label051;
        private Label label49;
        private Label label061;
        private Label label55;
        private Label label050;
        private Label label61;
        private Label label060;
        private Label label67;
        private Label label049;
        private Label label73;
        private Label label055;
        private Label label79;
        private Label label044;
        private Label label85;
        private Label label88;
        private Label label91;
        private Label label048;
        private Label label97;
        private Label label059;
        private Label label103;
        private Label label106;
        private Label label109;
        private Label label058;
        private Label label115;
        private Label label047;
        private Label label120;
        private Label label057;
        private Label label129;
        private Label label046;
        private Label label131;
        private Label label056;
        private Label label133;
        private Label label045;
        private Label label135;
        private Label label141;
        private Label label142;
        private Label label143;
        private Label label144;
        private TabPage tabPage1;
        private GroupBox groupBox1;
        private Label label003;
        private Label label002;
        private Label label001;
        private Label label179;
        private Label label257;
        private Label label258;
        private DataGridView dataGridViewCJDHH;
        private Label label203;
        private Label label204;
        private Label label205;
        private Label label214;
        private Label label215;
        private Label label016;
        private Label label015;
        private Label label014;
        private Label label013;
        private Label label228;
        private Label label151;
        private Label label152;
        private Label label153;
        private Label label162;
        private Label label163;
        private Label label012;
        private Label label011;
        private Label label010;
        private Label label009;
        private Label label008;
        private Label label122;
        private Label label123;
        private Label label124;
        private Label label125;
        private Label label136;
        private Label label007;
        private Label label006;
        private Label label005;
        private Label label004;
        private Label label150;
        private Label label255;
        private Label label030;
        private Label label121;
        private Label label190;
        private Label label229;
        private Label label230;
        private Label label231;
        private Label label029;
        private Label label028;
        private Label label027;
        private Label label026;
        private Label label025;
        private Label label237;
        private Label label238;
        private Label label239;
        private Label label240;
        private Label label241;
        private Label label024;
        private Label label023;
        private Label label022;
        private Label label021;
        private Label label254;
        private Label labelfkhj;
        private Label label16;
        private DataGridViewTextBoxColumn 编号;
        private DataGridViewTextBoxColumn 产品;
        private DataGridViewTextBoxColumn 数量;
        private DataGridViewTextBoxColumn 单价;
        private DataGridViewTextBoxColumn 金额;
        private DataGridViewTextBoxColumn 账期;
        private DataGridViewTextBoxColumn ISO;
        private DataGridViewTextBoxColumn 成本;
        private DataGridViewTextBoxColumn 利润;
        private DataGridViewTextBoxColumn 违约罚款;
        private DataGridViewTextBoxColumn 交付;
        private Label label19;
        private Label label066;
        private Label label14;
        private Label label065;
        private Label label067;
        private Label label23;
        private Label label068;
        private Label label27;

        public frmShowBusinessResult()
        {
            this.InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            base.Close();
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            this.InitData((Year) this.comboBox1.SelectedItem);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void frmShowBusinessResult_Load(object sender, EventArgs e)
        {
            switch (TGlobals.currentActor.RunningYear)
            {
                case Year.第1年:
                    this.comboBox1.Items.Clear();
                    this.comboBox1.Items.Add(Year.第1年);
                    break;

                case Year.第2年:
                    this.comboBox1.Items.Clear();
                    this.comboBox1.Items.Add(Year.第1年);
                    this.comboBox1.Items.Add(Year.第2年);
                    break;

                case Year.第3年:
                    this.comboBox1.Items.Clear();
                    this.comboBox1.Items.Add(Year.第1年);
                    this.comboBox1.Items.Add(Year.第2年);
                    this.comboBox1.Items.Add(Year.第3年);
                    break;

                case Year.第4年:
                    this.comboBox1.Items.Clear();
                    this.comboBox1.Items.Add(Year.第1年);
                    this.comboBox1.Items.Add(Year.第2年);
                    this.comboBox1.Items.Add(Year.第3年);
                    this.comboBox1.Items.Add(Year.第4年);
                    break;

                case Year.第5年:
                    this.comboBox1.Items.Clear();
                    this.comboBox1.Items.Add(Year.第1年);
                    this.comboBox1.Items.Add(Year.第2年);
                    this.comboBox1.Items.Add(Year.第3年);
                    this.comboBox1.Items.Add(Year.第4年);
                    this.comboBox1.Items.Add(Year.第5年);
                    break;

                case Year.第6年:
                    this.comboBox1.Items.Clear();
                    this.comboBox1.Items.Add(Year.第1年);
                    this.comboBox1.Items.Add(Year.第2年);
                    this.comboBox1.Items.Add(Year.第3年);
                    this.comboBox1.Items.Add(Year.第4年);
                    this.comboBox1.Items.Add(Year.第5年);
                    this.comboBox1.Items.Add(Year.第6年);
                    break;

                case Year.第7年:
                    this.comboBox1.Items.Clear();
                    this.comboBox1.Items.Add(Year.第1年);
                    this.comboBox1.Items.Add(Year.第2年);
                    this.comboBox1.Items.Add(Year.第3年);
                    this.comboBox1.Items.Add(Year.第4年);
                    this.comboBox1.Items.Add(Year.第5年);
                    this.comboBox1.Items.Add(Year.第6年);
                    break;

                default:
                    break;
            }
            this.comboBox1.SelectedIndex = this.comboBox1.Items.Count - 1;
        }

        private void InitData(Year year)
        {
            TBusinessConditions currBusinessConditions;
            if ((year == TGlobals.currentActor.RunningYear) && (year != Year.第7年))
            {
                currBusinessConditions = TGlobals.currentActor.CurrBusinessConditions;
                this.tabControl.TabPages.Clear();
                this.tabControl.TabPages.Add(this.tabPage1);
            }
            else
            {
                currBusinessConditions = TGlobals.currentActor.GetBusinessConditions(year);
                this.tabControl.TabPages.Clear();
                this.tabControl.TabPages.Add(this.tabPage1);
                this.tabControl.TabPages.Add(this.tabPage2);
            }
            if (currBusinessConditions != null)
            {
                TOrderSheet promisedOrderSheet = currBusinessConditions.PromisedOrderSheet;
                TOrderSheet notPromisedOrderSheet = currBusinessConditions.NotPromisedOrderSheet;
                TComprehensiveCostSheet comprehensiveCostSheet = currBusinessConditions.ComprehensiveCostSheet;
                TBalanceSheet balanceSheet = currBusinessConditions.BalanceSheet;
                TCashFlowSheet cashFlowSheet = currBusinessConditions.CashFlowSheet;
                TFinancialSheet financialSheet = currBusinessConditions.FinancialSheet;
                TOperatingSheet operatingSheet = currBusinessConditions.OperatingSheet;
                this.dataGridViewCJDHH.Rows.Clear();
                int length = 0;
                int length = 0;
                if (notPromisedOrderSheet.OrderSet != null)
                {
                    length = notPromisedOrderSheet.OrderSet.Length;
                }
                if (promisedOrderSheet.OrderSet != null)
                {
                    length = promisedOrderSheet.OrderSet.Length;
                }
                this.dataGridViewCJDHH.RowCount = length + length;
                if (notPromisedOrderSheet.OrderSet != null)
                {
                    for (int i = 0; i < notPromisedOrderSheet.OrderSet.Length; i++)
                    {
                        this.dataGridViewCJDHH.Rows[i].Cells["编号"].Value = notPromisedOrderSheet.OrderSet[i].OrderID;
                        this.dataGridViewCJDHH.Rows[i].Cells["产品"].Value = notPromisedOrderSheet.OrderSet[i].ProductName;
                        this.dataGridViewCJDHH.Rows[i].Cells["数量"].Value = notPromisedOrderSheet.OrderSet[i].ProductNumber;
                        this.dataGridViewCJDHH.Rows[i].Cells["单价"].Value = notPromisedOrderSheet.OrderSet[i].UnitPrice;
                        this.dataGridViewCJDHH.Rows[i].Cells["金额"].Value = notPromisedOrderSheet.OrderSet[i].Amount;
                        this.dataGridViewCJDHH.Rows[i].Cells["账期"].Value = notPromisedOrderSheet.OrderSet[i].AccountPeriod;
                        this.dataGridViewCJDHH.Rows[i].Cells["ISO"].Value = notPromisedOrderSheet.OrderSet[i].ISOQulify;
                        this.dataGridViewCJDHH.Rows[i].Cells["成本"].Value = notPromisedOrderSheet.OrderSet[i].DirectCost;
                        this.dataGridViewCJDHH.Rows[i].Cells["利润"].Value = notPromisedOrderSheet.OrderSet[i].GrossProfit;
                        this.dataGridViewCJDHH.Rows[i].Cells["违约罚款"].Value = notPromisedOrderSheet.OrderSet[i].BreakPromiseCost;
                        this.dataGridViewCJDHH.Rows[i].Cells["交付"].Value = notPromisedOrderSheet.OrderSet[i].ISJH;
                    }
                }
                if (promisedOrderSheet.OrderSet != null)
                {
                    for (int i = 0; i < promisedOrderSheet.OrderSet.Length; i++)
                    {
                        this.dataGridViewCJDHH.Rows[length + i].Cells["编号"].Value = promisedOrderSheet.OrderSet[i].OrderID;
                        this.dataGridViewCJDHH.Rows[length + i].Cells["产品"].Value = promisedOrderSheet.OrderSet[i].ProductName;
                        this.dataGridViewCJDHH.Rows[length + i].Cells["数量"].Value = promisedOrderSheet.OrderSet[i].ProductNumber;
                        this.dataGridViewCJDHH.Rows[length + i].Cells["单价"].Value = promisedOrderSheet.OrderSet[i].UnitPrice;
                        this.dataGridViewCJDHH.Rows[length + i].Cells["金额"].Value = promisedOrderSheet.OrderSet[i].Amount;
                        this.dataGridViewCJDHH.Rows[length + i].Cells["账期"].Value = promisedOrderSheet.OrderSet[i].AccountPeriod;
                        this.dataGridViewCJDHH.Rows[length + i].Cells["ISO"].Value = promisedOrderSheet.OrderSet[i].ISOQulify;
                        this.dataGridViewCJDHH.Rows[length + i].Cells["成本"].Value = promisedOrderSheet.OrderSet[i].DirectCost;
                        this.dataGridViewCJDHH.Rows[length + i].Cells["利润"].Value = promisedOrderSheet.OrderSet[i].GrossProfit;
                        this.dataGridViewCJDHH.Rows[length + i].Cells["违约罚款"].Value = promisedOrderSheet.OrderSet[i].BreakPromiseCost;
                        this.dataGridViewCJDHH.Rows[length + i].Cells["交付"].Value = promisedOrderSheet.OrderSet[i].ISJH;
                    }
                }
                this.label001.Text = ((promisedOrderSheet.TotalAmount + notPromisedOrderSheet.TotalAmount) - notPromisedOrderSheet.TotalBreakPromiseCost).ToString();
                this.label002.Text = (promisedOrderSheet.TotalDirectCost + notPromisedOrderSheet.TotalDirectCost).ToString();
                this.label003.Text = (promisedOrderSheet.TotalGrossProfit + notPromisedOrderSheet.TotalGrossProfit).ToString();
                this.labelfkhj.Text = notPromisedOrderSheet.TotalBreakPromiseCost.ToString();
                this.label004.Text = comprehensiveCostSheet.Administration.ToString();
                this.label005.Text = comprehensiveCostSheet.Advertisement.ToString();
                this.label006.Text = comprehensiveCostSheet.EquipmentMaintenance.ToString();
                this.label007.Text = comprehensiveCostSheet.RentPlant.ToString();
                this.label008.Text = comprehensiveCostSheet.MarketDevelopment.ToString();
                this.label009.Text = comprehensiveCostSheet.IsoCertification.ToString();
                this.label010.Text = comprehensiveCostSheet.ProductDevelopment.ToString();
                this.label011.Text = comprehensiveCostSheet.Others.ToString();
                this.label012.Text = comprehensiveCostSheet.Total.ToString();
                this.label013.Text = financialSheet.Depreciation.ToString();
                this.label014.Text = financialSheet.Interest.ToString();
                this.label015.Text = financialSheet.Discount.ToString();
                this.label016.Text = financialSheet.Taxes.ToString();
                this.label065.Text = financialSheet.AdditionalRevenue.ToString();
                this.label066.Text = financialSheet.AdditionalExpenditure.ToString();
                this.label021.Text = operatingSheet.Plant.ToString();
                this.label022.Text = operatingSheet.EquipmentAndConstruction.ToString();
                this.label023.Text = operatingSheet.CurrentCash.ToString();
                this.label024.Text = operatingSheet.ReceivableAccounts.ToString();
                this.label025.Text = operatingSheet.AreProducts.ToString();
                this.label026.Text = operatingSheet.FinishedProduct.ToString();
                this.label027.Text = operatingSheet.RawMaterials.ToString();
                this.label028.Text = operatingSheet.LongTermLoans.ToString();
                this.label029.Text = operatingSheet.ShortTermLoans.ToString();
                this.label030.Text = operatingSheet.LoanSharking.ToString();
                this.label031.Text = year.ToString();
                this.label032.Text = cashFlowSheet.Sales.ToString();
                this.label033.Text = cashFlowSheet.DirectCost.ToString();
                this.label034.Text = cashFlowSheet.GrossProfit.ToString();
                this.label035.Text = cashFlowSheet.ComprehensiveCost.ToString();
                this.label036.Text = cashFlowSheet.ProfitBeforeDepreciation.ToString();
                this.label037.Text = cashFlowSheet.Depreciation.ToString();
                this.label038.Text = cashFlowSheet.ProfitBeforeInterestPayments.ToString();
                this.label039.Text = cashFlowSheet.FinancialExpenditure.ToString();
                this.label041.Text = cashFlowSheet.PretaxProfit.ToString();
                this.label042.Text = cashFlowSheet.IncomeTax.ToString();
                this.label043.Text = cashFlowSheet.NetProfit.ToString();
                this.label067.Text = cashFlowSheet.AdditionalRevenue.ToString();
                this.label068.Text = cashFlowSheet.AdditionalExpenditure.ToString();
                this.label044.Text = year.ToString();
                this.label045.Text = balanceSheet.LandAndBuildings.ToString();
                this.label046.Text = balanceSheet.EquipmentAndConstruction.ToString();
                this.label047.Text = balanceSheet.TotalFixedAssets.ToString();
                this.label048.Text = balanceSheet.CurrentCash.ToString();
                this.label049.Text = balanceSheet.ReceivableAccounts.ToString();
                this.label050.Text = balanceSheet.AreProducts.ToString();
                this.label051.Text = balanceSheet.FinishedProduct.ToString();
                this.label052.Text = balanceSheet.RawMaterials.ToString();
                this.label053.Text = balanceSheet.TotalCurrentAssets.ToString();
                this.label054.Text = balanceSheet.TotalAssets.ToString();
                this.label055.Text = year.ToString();
                this.label056.Text = balanceSheet.LongtermLiabilities.ToString();
                this.label057.Text = balanceSheet.shortTermLiabilities.ToString();
                this.label058.Text = balanceSheet.Taxes.ToString();
                this.label059.Text = balanceSheet.TotalLiabilities.ToString();
                this.label060.Text = balanceSheet.CapitalShareholders.ToString();
                this.label061.Text = balanceSheet.RetainedProfits.ToString();
                this.label062.Text = balanceSheet.NetProfit.ToString();
                this.label063.Text = balanceSheet.OwnerRight.ToString();
                this.label064.Text = balanceSheet.TotalLiabilitiesRights.ToString();
            }
        }

        private void InitializeComponent()
        {
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            DataGridViewCellStyle style2 = new DataGridViewCellStyle();
            DataGridViewCellStyle style3 = new DataGridViewCellStyle();
            DataGridViewCellStyle style4 = new DataGridViewCellStyle();
            DataGridViewCellStyle style5 = new DataGridViewCellStyle();
            DataGridViewCellStyle style6 = new DataGridViewCellStyle();
            DataGridViewCellStyle style7 = new DataGridViewCellStyle();
            DataGridViewCellStyle style8 = new DataGridViewCellStyle();
            DataGridViewCellStyle style9 = new DataGridViewCellStyle();
            DataGridViewCellStyle style10 = new DataGridViewCellStyle();
            DataGridViewCellStyle style11 = new DataGridViewCellStyle();
            DataGridViewCellStyle style12 = new DataGridViewCellStyle();
            this.button1 = new Button();
            this.tabControl = new TabControl();
            this.tabPage1 = new TabPage();
            this.label19 = new Label();
            this.label066 = new Label();
            this.label14 = new Label();
            this.label065 = new Label();
            this.label255 = new Label();
            this.label030 = new Label();
            this.label121 = new Label();
            this.label190 = new Label();
            this.label229 = new Label();
            this.label230 = new Label();
            this.label231 = new Label();
            this.label029 = new Label();
            this.label028 = new Label();
            this.label027 = new Label();
            this.label026 = new Label();
            this.label025 = new Label();
            this.label237 = new Label();
            this.label238 = new Label();
            this.label239 = new Label();
            this.label240 = new Label();
            this.label241 = new Label();
            this.label024 = new Label();
            this.label023 = new Label();
            this.label022 = new Label();
            this.label021 = new Label();
            this.label254 = new Label();
            this.groupBox1 = new GroupBox();
            this.labelfkhj = new Label();
            this.label16 = new Label();
            this.label003 = new Label();
            this.label002 = new Label();
            this.label001 = new Label();
            this.label179 = new Label();
            this.label257 = new Label();
            this.label258 = new Label();
            this.dataGridViewCJDHH = new DataGridView();
            this.编号 = new DataGridViewTextBoxColumn();
            this.产品 = new DataGridViewTextBoxColumn();
            this.数量 = new DataGridViewTextBoxColumn();
            this.单价 = new DataGridViewTextBoxColumn();
            this.金额 = new DataGridViewTextBoxColumn();
            this.账期 = new DataGridViewTextBoxColumn();
            this.ISO = new DataGridViewTextBoxColumn();
            this.成本 = new DataGridViewTextBoxColumn();
            this.利润 = new DataGridViewTextBoxColumn();
            this.违约罚款 = new DataGridViewTextBoxColumn();
            this.交付 = new DataGridViewTextBoxColumn();
            this.label203 = new Label();
            this.label204 = new Label();
            this.label205 = new Label();
            this.label214 = new Label();
            this.label215 = new Label();
            this.label016 = new Label();
            this.label015 = new Label();
            this.label014 = new Label();
            this.label013 = new Label();
            this.label228 = new Label();
            this.label151 = new Label();
            this.label152 = new Label();
            this.label153 = new Label();
            this.label162 = new Label();
            this.label163 = new Label();
            this.label012 = new Label();
            this.label011 = new Label();
            this.label010 = new Label();
            this.label009 = new Label();
            this.label008 = new Label();
            this.label122 = new Label();
            this.label123 = new Label();
            this.label124 = new Label();
            this.label125 = new Label();
            this.label136 = new Label();
            this.label007 = new Label();
            this.label006 = new Label();
            this.label005 = new Label();
            this.label004 = new Label();
            this.label150 = new Label();
            this.tabPage2 = new TabPage();
            this.groupBox3 = new GroupBox();
            this.label3 = new Label();
            this.label064 = new Label();
            this.label18 = new Label();
            this.label054 = new Label();
            this.label20 = new Label();
            this.label21 = new Label();
            this.label22 = new Label();
            this.label053 = new Label();
            this.label24 = new Label();
            this.label063 = new Label();
            this.label26 = new Label();
            this.label052 = new Label();
            this.label28 = new Label();
            this.label062 = new Label();
            this.label43 = new Label();
            this.label051 = new Label();
            this.label49 = new Label();
            this.label061 = new Label();
            this.label55 = new Label();
            this.label050 = new Label();
            this.label61 = new Label();
            this.label060 = new Label();
            this.label67 = new Label();
            this.label049 = new Label();
            this.label73 = new Label();
            this.label055 = new Label();
            this.label79 = new Label();
            this.label044 = new Label();
            this.label85 = new Label();
            this.label88 = new Label();
            this.label91 = new Label();
            this.label048 = new Label();
            this.label97 = new Label();
            this.label059 = new Label();
            this.label103 = new Label();
            this.label106 = new Label();
            this.label109 = new Label();
            this.label058 = new Label();
            this.label115 = new Label();
            this.label047 = new Label();
            this.label120 = new Label();
            this.label057 = new Label();
            this.label129 = new Label();
            this.label046 = new Label();
            this.label131 = new Label();
            this.label056 = new Label();
            this.label133 = new Label();
            this.label045 = new Label();
            this.label135 = new Label();
            this.label141 = new Label();
            this.label142 = new Label();
            this.label143 = new Label();
            this.label144 = new Label();
            this.groupBox2 = new GroupBox();
            this.label068 = new Label();
            this.label27 = new Label();
            this.label067 = new Label();
            this.label23 = new Label();
            this.label2 = new Label();
            this.label031 = new Label();
            this.label043 = new Label();
            this.label042 = new Label();
            this.label041 = new Label();
            this.label039 = new Label();
            this.label038 = new Label();
            this.label037 = new Label();
            this.label036 = new Label();
            this.label035 = new Label();
            this.label034 = new Label();
            this.label033 = new Label();
            this.label032 = new Label();
            this.label15 = new Label();
            this.label12 = new Label();
            this.label13 = new Label();
            this.label9 = new Label();
            this.label10 = new Label();
            this.label11 = new Label();
            this.label6 = new Label();
            this.label7 = new Label();
            this.label8 = new Label();
            this.label4 = new Label();
            this.label1 = new Label();
            this.label5 = new Label();
            this.comboBox1 = new ComboBox();
            this.label188 = new Label();
            this.tabControl.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            ((ISupportInitialize) this.dataGridViewCJDHH).BeginInit();
            this.tabPage2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            base.SuspendLayout();
            this.button1.Location = new Point(0x27c, 0x183);
            this.button1.Name = "button1";
            this.button1.Size = new Size(0x4b, 0x17);
            this.button1.TabIndex = 0;
            this.button1.Text = "确定";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new EventHandler(this.button1_Click);
            this.tabControl.Controls.Add(this.tabPage1);
            this.tabControl.Controls.Add(this.tabPage2);
            this.tabControl.Dock = DockStyle.Top;
            this.tabControl.Location = new Point(0, 0);
            this.tabControl.Name = "tabControl";
            this.tabControl.SelectedIndex = 0;
            this.tabControl.Size = new Size(0x2f1, 0x17d);
            this.tabControl.TabIndex = 3;
            this.tabPage1.Controls.Add(this.label19);
            this.tabPage1.Controls.Add(this.label066);
            this.tabPage1.Controls.Add(this.label14);
            this.tabPage1.Controls.Add(this.label065);
            this.tabPage1.Controls.Add(this.label255);
            this.tabPage1.Controls.Add(this.label030);
            this.tabPage1.Controls.Add(this.label121);
            this.tabPage1.Controls.Add(this.label190);
            this.tabPage1.Controls.Add(this.label229);
            this.tabPage1.Controls.Add(this.label230);
            this.tabPage1.Controls.Add(this.label231);
            this.tabPage1.Controls.Add(this.label029);
            this.tabPage1.Controls.Add(this.label028);
            this.tabPage1.Controls.Add(this.label027);
            this.tabPage1.Controls.Add(this.label026);
            this.tabPage1.Controls.Add(this.label025);
            this.tabPage1.Controls.Add(this.label237);
            this.tabPage1.Controls.Add(this.label238);
            this.tabPage1.Controls.Add(this.label239);
            this.tabPage1.Controls.Add(this.label240);
            this.tabPage1.Controls.Add(this.label241);
            this.tabPage1.Controls.Add(this.label024);
            this.tabPage1.Controls.Add(this.label023);
            this.tabPage1.Controls.Add(this.label022);
            this.tabPage1.Controls.Add(this.label021);
            this.tabPage1.Controls.Add(this.label254);
            this.tabPage1.Controls.Add(this.groupBox1);
            this.tabPage1.Controls.Add(this.label203);
            this.tabPage1.Controls.Add(this.label204);
            this.tabPage1.Controls.Add(this.label205);
            this.tabPage1.Controls.Add(this.label214);
            this.tabPage1.Controls.Add(this.label215);
            this.tabPage1.Controls.Add(this.label016);
            this.tabPage1.Controls.Add(this.label015);
            this.tabPage1.Controls.Add(this.label014);
            this.tabPage1.Controls.Add(this.label013);
            this.tabPage1.Controls.Add(this.label228);
            this.tabPage1.Controls.Add(this.label151);
            this.tabPage1.Controls.Add(this.label152);
            this.tabPage1.Controls.Add(this.label153);
            this.tabPage1.Controls.Add(this.label162);
            this.tabPage1.Controls.Add(this.label163);
            this.tabPage1.Controls.Add(this.label012);
            this.tabPage1.Controls.Add(this.label011);
            this.tabPage1.Controls.Add(this.label010);
            this.tabPage1.Controls.Add(this.label009);
            this.tabPage1.Controls.Add(this.label008);
            this.tabPage1.Controls.Add(this.label122);
            this.tabPage1.Controls.Add(this.label123);
            this.tabPage1.Controls.Add(this.label124);
            this.tabPage1.Controls.Add(this.label125);
            this.tabPage1.Controls.Add(this.label136);
            this.tabPage1.Controls.Add(this.label007);
            this.tabPage1.Controls.Add(this.label006);
            this.tabPage1.Controls.Add(this.label005);
            this.tabPage1.Controls.Add(this.label004);
            this.tabPage1.Controls.Add(this.label150);
            this.tabPage1.Location = new Point(4, 0x15);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new Padding(3);
            this.tabPage1.Size = new Size(0x2e9, 0x164);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "经营状况明细表";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.label19.BorderStyle = BorderStyle.FixedSingle;
            this.label19.Location = new Point(0x178, 0x101);
            this.label19.Name = "label19";
            this.label19.Size = new Size(60, 0x15);
            this.label19.TabIndex = 0x109;
            this.label19.Text = "额外支出";
            this.label19.TextAlign = ContentAlignment.MiddleCenter;
            this.label066.BorderStyle = BorderStyle.FixedSingle;
            this.label066.Location = new Point(0x178, 0x115);
            this.label066.Name = "label066";
            this.label066.Size = new Size(60, 0x15);
            this.label066.TabIndex = 0x108;
            this.label066.TextAlign = ContentAlignment.MiddleCenter;
            this.label14.BorderStyle = BorderStyle.FixedSingle;
            this.label14.Location = new Point(0x13d, 0x101);
            this.label14.Name = "label14";
            this.label14.Size = new Size(60, 0x15);
            this.label14.TabIndex = 0x107;
            this.label14.Text = "额外收入";
            this.label14.TextAlign = ContentAlignment.MiddleCenter;
            this.label065.BorderStyle = BorderStyle.FixedSingle;
            this.label065.Location = new Point(0x13d, 0x115);
            this.label065.Name = "label065";
            this.label065.Size = new Size(60, 0x15);
            this.label065.TabIndex = 0x106;
            this.label065.TextAlign = ContentAlignment.MiddleCenter;
            this.label255.BorderStyle = BorderStyle.FixedSingle;
            this.label255.Location = new Point(0x267, 0x12a);
            this.label255.Name = "label255";
            this.label255.Size = new Size(0x3d, 0x15);
            this.label255.TabIndex = 0x105;
            this.label255.Text = "高利贷款";
            this.label255.TextAlign = ContentAlignment.MiddleCenter;
            this.label030.BorderStyle = BorderStyle.FixedSingle;
            this.label030.Location = new Point(0x267, 0x13e);
            this.label030.Name = "label030";
            this.label030.Size = new Size(0x3d, 0x15);
            this.label030.TabIndex = 260;
            this.label030.TextAlign = ContentAlignment.MiddleCenter;
            this.label121.BorderStyle = BorderStyle.FixedSingle;
            this.label121.Location = new Point(0x22b, 0x12a);
            this.label121.Name = "label121";
            this.label121.Size = new Size(0x3d, 0x15);
            this.label121.TabIndex = 0x103;
            this.label121.Text = "短期贷款";
            this.label121.TextAlign = ContentAlignment.MiddleCenter;
            this.label190.BorderStyle = BorderStyle.FixedSingle;
            this.label190.Location = new Point(0x1ef, 0x12a);
            this.label190.Name = "label190";
            this.label190.Size = new Size(0x3d, 0x15);
            this.label190.TabIndex = 0x102;
            this.label190.Text = "长期贷款";
            this.label190.TextAlign = ContentAlignment.MiddleCenter;
            this.label229.BorderStyle = BorderStyle.FixedSingle;
            this.label229.Location = new Point(0x1b3, 0x12a);
            this.label229.Name = "label229";
            this.label229.Size = new Size(0x3d, 0x15);
            this.label229.TabIndex = 0x101;
            this.label229.Text = "原材料";
            this.label229.TextAlign = ContentAlignment.MiddleCenter;
            this.label230.BorderStyle = BorderStyle.FixedSingle;
            this.label230.Location = new Point(0x178, 0x12a);
            this.label230.Name = "label230";
            this.label230.Size = new Size(60, 0x15);
            this.label230.TabIndex = 0x100;
            this.label230.Text = "成品";
            this.label230.TextAlign = ContentAlignment.MiddleCenter;
            this.label231.BorderStyle = BorderStyle.FixedSingle;
            this.label231.Location = new Point(0x13d, 0x12a);
            this.label231.Name = "label231";
            this.label231.Size = new Size(60, 0x15);
            this.label231.TabIndex = 0xff;
            this.label231.Text = "在制品";
            this.label231.TextAlign = ContentAlignment.MiddleCenter;
            this.label029.BorderStyle = BorderStyle.FixedSingle;
            this.label029.Location = new Point(0x22b, 0x13e);
            this.label029.Name = "label029";
            this.label029.Size = new Size(0x3d, 0x15);
            this.label029.TabIndex = 0xfe;
            this.label029.TextAlign = ContentAlignment.MiddleCenter;
            this.label028.BorderStyle = BorderStyle.FixedSingle;
            this.label028.Location = new Point(0x1ef, 0x13e);
            this.label028.Name = "label028";
            this.label028.Size = new Size(0x3d, 0x15);
            this.label028.TabIndex = 0xfd;
            this.label028.TextAlign = ContentAlignment.MiddleCenter;
            this.label027.BorderStyle = BorderStyle.FixedSingle;
            this.label027.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label027.Location = new Point(0x1b3, 0x13e);
            this.label027.Name = "label027";
            this.label027.Size = new Size(0x3d, 0x15);
            this.label027.TabIndex = 0xfc;
            this.label027.TextAlign = ContentAlignment.MiddleCenter;
            this.label026.BorderStyle = BorderStyle.FixedSingle;
            this.label026.Location = new Point(0x178, 0x13e);
            this.label026.Name = "label026";
            this.label026.Size = new Size(60, 0x15);
            this.label026.TabIndex = 0xfb;
            this.label026.TextAlign = ContentAlignment.MiddleCenter;
            this.label025.BorderStyle = BorderStyle.FixedSingle;
            this.label025.Location = new Point(0x13d, 0x13e);
            this.label025.Name = "label025";
            this.label025.Size = new Size(60, 0x15);
            this.label025.TabIndex = 250;
            this.label025.TextAlign = ContentAlignment.MiddleCenter;
            this.label237.BorderStyle = BorderStyle.FixedSingle;
            this.label237.Location = new Point(0x102, 0x12a);
            this.label237.Name = "label237";
            this.label237.Size = new Size(60, 0x15);
            this.label237.TabIndex = 0xf9;
            this.label237.Text = "应收款";
            this.label237.TextAlign = ContentAlignment.MiddleCenter;
            this.label238.BorderStyle = BorderStyle.FixedSingle;
            this.label238.Location = new Point(0xc7, 0x12a);
            this.label238.Name = "label238";
            this.label238.Size = new Size(60, 0x15);
            this.label238.TabIndex = 0xf8;
            this.label238.Text = "现金";
            this.label238.TextAlign = ContentAlignment.MiddleCenter;
            this.label239.BorderStyle = BorderStyle.FixedSingle;
            this.label239.Location = new Point(0x85, 0x12a);
            this.label239.Name = "label239";
            this.label239.Size = new Size(0x43, 0x15);
            this.label239.TabIndex = 0xf7;
            this.label239.Text = "设备及在建";
            this.label239.TextAlign = ContentAlignment.MiddleCenter;
            this.label240.BorderStyle = BorderStyle.FixedSingle;
            this.label240.Location = new Point(0x4a, 0x12a);
            this.label240.Name = "label240";
            this.label240.Size = new Size(60, 0x15);
            this.label240.TabIndex = 0xf6;
            this.label240.Text = "厂房";
            this.label240.TextAlign = ContentAlignment.MiddleCenter;
            this.label241.BorderStyle = BorderStyle.FixedSingle;
            this.label241.Location = new Point(15, 0x12a);
            this.label241.Name = "label241";
            this.label241.Size = new Size(60, 0x15);
            this.label241.TabIndex = 0xf5;
            this.label241.Text = "运营状况";
            this.label241.TextAlign = ContentAlignment.MiddleCenter;
            this.label024.BorderStyle = BorderStyle.FixedSingle;
            this.label024.Location = new Point(0x102, 0x13e);
            this.label024.Name = "label024";
            this.label024.Size = new Size(60, 0x15);
            this.label024.TabIndex = 0xf4;
            this.label024.TextAlign = ContentAlignment.MiddleCenter;
            this.label023.BorderStyle = BorderStyle.FixedSingle;
            this.label023.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label023.Location = new Point(0xc7, 0x13e);
            this.label023.Name = "label023";
            this.label023.Size = new Size(60, 0x15);
            this.label023.TabIndex = 0xf3;
            this.label023.TextAlign = ContentAlignment.MiddleCenter;
            this.label022.BorderStyle = BorderStyle.FixedSingle;
            this.label022.Location = new Point(0x85, 0x13e);
            this.label022.Name = "label022";
            this.label022.Size = new Size(0x43, 0x15);
            this.label022.TabIndex = 0xf2;
            this.label022.TextAlign = ContentAlignment.MiddleCenter;
            this.label021.BorderStyle = BorderStyle.FixedSingle;
            this.label021.Location = new Point(0x4a, 0x13e);
            this.label021.Name = "label021";
            this.label021.Size = new Size(60, 0x15);
            this.label021.TabIndex = 0xf1;
            this.label021.TextAlign = ContentAlignment.MiddleCenter;
            this.label254.BorderStyle = BorderStyle.FixedSingle;
            this.label254.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label254.Location = new Point(15, 0x13e);
            this.label254.Name = "label254";
            this.label254.Size = new Size(60, 0x15);
            this.label254.TabIndex = 240;
            this.label254.Text = "金额";
            this.label254.TextAlign = ContentAlignment.MiddleCenter;
            this.groupBox1.Controls.Add(this.labelfkhj);
            this.groupBox1.Controls.Add(this.label16);
            this.groupBox1.Controls.Add(this.label003);
            this.groupBox1.Controls.Add(this.label002);
            this.groupBox1.Controls.Add(this.label001);
            this.groupBox1.Controls.Add(this.label179);
            this.groupBox1.Controls.Add(this.label257);
            this.groupBox1.Controls.Add(this.label258);
            this.groupBox1.Controls.Add(this.dataGridViewCJDHH);
            this.groupBox1.Dock = DockStyle.Top;
            this.groupBox1.Location = new Point(3, 3);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0x2e3, 0xbd);
            this.groupBox1.TabIndex = 0xef;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "本年订单明细";
            this.labelfkhj.BorderStyle = BorderStyle.FixedSingle;
            this.labelfkhj.Location = new Point(0x285, 0xa4);
            this.labelfkhj.Name = "labelfkhj";
            this.labelfkhj.Size = new Size(0x5b, 0x15);
            this.labelfkhj.TabIndex = 0xf7;
            this.labelfkhj.Text = "22M";
            this.labelfkhj.TextAlign = ContentAlignment.MiddleCenter;
            this.label16.BorderStyle = BorderStyle.FixedSingle;
            this.label16.Location = new Point(0x285, 0x8f);
            this.label16.Name = "label16";
            this.label16.Size = new Size(0x5b, 0x15);
            this.label16.TabIndex = 0xf6;
            this.label16.Text = "罚款合计";
            this.label16.TextAlign = ContentAlignment.MiddleCenter;
            this.label003.BorderStyle = BorderStyle.FixedSingle;
            this.label003.Location = new Point(0x285, 0x7a);
            this.label003.Name = "label003";
            this.label003.Size = new Size(0x5b, 0x15);
            this.label003.TabIndex = 0xf5;
            this.label003.Text = "22M";
            this.label003.TextAlign = ContentAlignment.MiddleCenter;
            this.label002.BorderStyle = BorderStyle.FixedSingle;
            this.label002.Location = new Point(0x285, 80);
            this.label002.Name = "label002";
            this.label002.Size = new Size(0x5b, 0x15);
            this.label002.TabIndex = 0xf4;
            this.label002.Text = "14M";
            this.label002.TextAlign = ContentAlignment.MiddleCenter;
            this.label001.BorderStyle = BorderStyle.FixedSingle;
            this.label001.Location = new Point(0x285, 0x26);
            this.label001.Name = "label001";
            this.label001.Size = new Size(0x5b, 0x15);
            this.label001.TabIndex = 0xf3;
            this.label001.Text = "36M";
            this.label001.TextAlign = ContentAlignment.MiddleCenter;
            this.label179.BorderStyle = BorderStyle.FixedSingle;
            this.label179.Location = new Point(0x285, 0x65);
            this.label179.Name = "label179";
            this.label179.Size = new Size(0x5b, 0x15);
            this.label179.TabIndex = 0xf2;
            this.label179.Text = "毛利合计";
            this.label179.TextAlign = ContentAlignment.MiddleCenter;
            this.label257.BorderStyle = BorderStyle.FixedSingle;
            this.label257.Location = new Point(0x285, 0x3b);
            this.label257.Name = "label257";
            this.label257.Size = new Size(0x5b, 0x15);
            this.label257.TabIndex = 0xf1;
            this.label257.Text = "直接成本合计";
            this.label257.TextAlign = ContentAlignment.MiddleCenter;
            this.label258.BorderStyle = BorderStyle.FixedSingle;
            this.label258.Location = new Point(0x285, 0x11);
            this.label258.Name = "label258";
            this.label258.Size = new Size(0x5b, 0x15);
            this.label258.TabIndex = 240;
            this.label258.Text = "交货订单额合计";
            this.label258.TextAlign = ContentAlignment.MiddleCenter;
            this.dataGridViewCJDHH.AllowUserToAddRows = false;
            this.dataGridViewCJDHH.AllowUserToDeleteRows = false;
            this.dataGridViewCJDHH.AllowUserToResizeRows = false;
            this.dataGridViewCJDHH.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.ColumnHeader;
            this.dataGridViewCJDHH.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            DataGridViewColumn[] dataGridViewColumns = new DataGridViewColumn[] { this.编号, this.产品, this.数量, this.单价, this.金额, this.账期, this.ISO, this.成本, this.利润 };
            dataGridViewColumns[9] = this.违约罚款;
            dataGridViewColumns[10] = this.交付;
            this.dataGridViewCJDHH.Columns.AddRange(dataGridViewColumns);
            style.Alignment = DataGridViewContentAlignment.MiddleCenter;
            style.BackColor = SystemColors.Window;
            style.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            style.ForeColor = SystemColors.ControlText;
            style.SelectionBackColor = SystemColors.Highlight;
            style.SelectionForeColor = SystemColors.HighlightText;
            style.WrapMode = DataGridViewTriState.False;
            this.dataGridViewCJDHH.DefaultCellStyle = style;
            this.dataGridViewCJDHH.Dock = DockStyle.Left;
            this.dataGridViewCJDHH.Location = new Point(3, 0x11);
            this.dataGridViewCJDHH.MultiSelect = false;
            this.dataGridViewCJDHH.Name = "dataGridViewCJDHH";
            this.dataGridViewCJDHH.ReadOnly = true;
            this.dataGridViewCJDHH.RowHeadersVisible = false;
            this.dataGridViewCJDHH.RowTemplate.Height = 0x17;
            this.dataGridViewCJDHH.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dataGridViewCJDHH.Size = new Size(0x27c, 0xa9);
            this.dataGridViewCJDHH.TabIndex = 0xef;
            style2.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.编号.DefaultCellStyle = style2;
            this.编号.HeaderText = "编号";
            this.编号.Name = "编号";
            this.编号.ReadOnly = true;
            this.编号.Resizable = DataGridViewTriState.False;
            this.编号.Width = 0x36;
            style3.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.产品.DefaultCellStyle = style3;
            this.产品.HeaderText = "产品";
            this.产品.Name = "产品";
            this.产品.ReadOnly = true;
            this.产品.Resizable = DataGridViewTriState.False;
            this.产品.Width = 0x36;
            style4.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.数量.DefaultCellStyle = style4;
            this.数量.HeaderText = "数量";
            this.数量.Name = "数量";
            this.数量.ReadOnly = true;
            this.数量.Resizable = DataGridViewTriState.False;
            this.数量.Width = 0x36;
            style5.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.单价.DefaultCellStyle = style5;
            this.单价.HeaderText = "单价";
            this.单价.Name = "单价";
            this.单价.ReadOnly = true;
            this.单价.Resizable = DataGridViewTriState.False;
            this.单价.Width = 0x36;
            style6.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.金额.DefaultCellStyle = style6;
            this.金额.HeaderText = "金额";
            this.金额.Name = "金额";
            this.金额.ReadOnly = true;
            this.金额.Resizable = DataGridViewTriState.False;
            this.金额.Width = 0x36;
            style7.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.账期.DefaultCellStyle = style7;
            this.账期.HeaderText = "账期";
            this.账期.Name = "账期";
            this.账期.ReadOnly = true;
            this.账期.Resizable = DataGridViewTriState.False;
            this.账期.Width = 0x36;
            style8.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.ISO.DefaultCellStyle = style8;
            this.ISO.HeaderText = "ISO";
            this.ISO.Name = "ISO";
            this.ISO.ReadOnly = true;
            this.ISO.Resizable = DataGridViewTriState.False;
            this.ISO.Width = 0x30;
            style9.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.成本.DefaultCellStyle = style9;
            this.成本.HeaderText = "成本";
            this.成本.Name = "成本";
            this.成本.ReadOnly = true;
            this.成本.Resizable = DataGridViewTriState.False;
            this.成本.Width = 0x36;
            style10.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.利润.DefaultCellStyle = style10;
            this.利润.HeaderText = "利润";
            this.利润.Name = "利润";
            this.利润.ReadOnly = true;
            this.利润.Resizable = DataGridViewTriState.False;
            this.利润.Width = 0x36;
            style11.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.违约罚款.DefaultCellStyle = style11;
            this.违约罚款.HeaderText = "违约罚款";
            this.违约罚款.Name = "违约罚款";
            this.违约罚款.ReadOnly = true;
            this.违约罚款.Resizable = DataGridViewTriState.False;
            this.违约罚款.Width = 0x4e;
            style12.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.交付.DefaultCellStyle = style12;
            this.交付.HeaderText = "交付";
            this.交付.Name = "交付";
            this.交付.ReadOnly = true;
            this.交付.Resizable = DataGridViewTriState.False;
            this.交付.Width = 0x36;
            this.label203.BorderStyle = BorderStyle.FixedSingle;
            this.label203.Location = new Point(0x102, 0x101);
            this.label203.Name = "label203";
            this.label203.Size = new Size(60, 0x15);
            this.label203.TabIndex = 0x87;
            this.label203.Text = "税金";
            this.label203.TextAlign = ContentAlignment.MiddleCenter;
            this.label204.BorderStyle = BorderStyle.FixedSingle;
            this.label204.Location = new Point(0xc7, 0x101);
            this.label204.Name = "label204";
            this.label204.Size = new Size(60, 0x15);
            this.label204.TabIndex = 0x86;
            this.label204.Text = "贴现";
            this.label204.TextAlign = ContentAlignment.MiddleCenter;
            this.label205.BorderStyle = BorderStyle.FixedSingle;
            this.label205.Location = new Point(0x85, 0x101);
            this.label205.Name = "label205";
            this.label205.Size = new Size(0x43, 0x15);
            this.label205.TabIndex = 0x85;
            this.label205.Text = "利息";
            this.label205.TextAlign = ContentAlignment.MiddleCenter;
            this.label214.BorderStyle = BorderStyle.FixedSingle;
            this.label214.Location = new Point(0x4a, 0x101);
            this.label214.Name = "label214";
            this.label214.Size = new Size(60, 0x15);
            this.label214.TabIndex = 0x84;
            this.label214.Text = "折旧";
            this.label214.TextAlign = ContentAlignment.MiddleCenter;
            this.label215.BorderStyle = BorderStyle.FixedSingle;
            this.label215.Location = new Point(15, 0x101);
            this.label215.Name = "label215";
            this.label215.Size = new Size(60, 0x15);
            this.label215.TabIndex = 0x83;
            this.label215.Text = "财务支出";
            this.label215.TextAlign = ContentAlignment.MiddleCenter;
            this.label016.BorderStyle = BorderStyle.FixedSingle;
            this.label016.Location = new Point(0x102, 0x115);
            this.label016.Name = "label016";
            this.label016.Size = new Size(60, 0x15);
            this.label016.TabIndex = 130;
            this.label016.TextAlign = ContentAlignment.MiddleCenter;
            this.label015.BorderStyle = BorderStyle.FixedSingle;
            this.label015.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label015.Location = new Point(0xc7, 0x115);
            this.label015.Name = "label015";
            this.label015.Size = new Size(60, 0x15);
            this.label015.TabIndex = 0x81;
            this.label015.TextAlign = ContentAlignment.MiddleCenter;
            this.label014.BorderStyle = BorderStyle.FixedSingle;
            this.label014.Location = new Point(0x85, 0x115);
            this.label014.Name = "label014";
            this.label014.Size = new Size(0x43, 0x15);
            this.label014.TabIndex = 0x80;
            this.label014.TextAlign = ContentAlignment.MiddleCenter;
            this.label013.BorderStyle = BorderStyle.FixedSingle;
            this.label013.Location = new Point(0x4a, 0x115);
            this.label013.Name = "label013";
            this.label013.Size = new Size(60, 0x15);
            this.label013.TabIndex = 0x7f;
            this.label013.TextAlign = ContentAlignment.MiddleCenter;
            this.label228.BorderStyle = BorderStyle.FixedSingle;
            this.label228.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label228.Location = new Point(15, 0x115);
            this.label228.Name = "label228";
            this.label228.Size = new Size(60, 0x15);
            this.label228.TabIndex = 0x7e;
            this.label228.Text = "金额";
            this.label228.TextAlign = ContentAlignment.MiddleCenter;
            this.label151.BorderStyle = BorderStyle.FixedSingle;
            this.label151.Location = new Point(0x22b, 0xd8);
            this.label151.Name = "label151";
            this.label151.Size = new Size(0x3d, 0x15);
            this.label151.TabIndex = 0x68;
            this.label151.Text = "合计";
            this.label151.TextAlign = ContentAlignment.MiddleCenter;
            this.label152.BorderStyle = BorderStyle.FixedSingle;
            this.label152.Location = new Point(0x1ef, 0xd8);
            this.label152.Name = "label152";
            this.label152.Size = new Size(0x3d, 0x15);
            this.label152.TabIndex = 0x67;
            this.label152.Text = "其他";
            this.label152.TextAlign = ContentAlignment.MiddleCenter;
            this.label153.BorderStyle = BorderStyle.FixedSingle;
            this.label153.Location = new Point(0x1b3, 0xd8);
            this.label153.Name = "label153";
            this.label153.Size = new Size(0x3d, 0x15);
            this.label153.TabIndex = 0x66;
            this.label153.Text = "产品研发";
            this.label153.TextAlign = ContentAlignment.MiddleCenter;
            this.label162.BorderStyle = BorderStyle.FixedSingle;
            this.label162.Location = new Point(0x178, 0xd8);
            this.label162.Name = "label162";
            this.label162.Size = new Size(60, 0x15);
            this.label162.TabIndex = 0x65;
            this.label162.Text = "ISO认证";
            this.label162.TextAlign = ContentAlignment.MiddleCenter;
            this.label163.BorderStyle = BorderStyle.FixedSingle;
            this.label163.Location = new Point(0x13d, 0xd8);
            this.label163.Name = "label163";
            this.label163.Size = new Size(60, 0x15);
            this.label163.TabIndex = 100;
            this.label163.Text = "市场开拓";
            this.label163.TextAlign = ContentAlignment.MiddleCenter;
            this.label012.BorderStyle = BorderStyle.FixedSingle;
            this.label012.Location = new Point(0x22b, 0xec);
            this.label012.Name = "label012";
            this.label012.Size = new Size(0x3d, 0x15);
            this.label012.TabIndex = 0x62;
            this.label012.TextAlign = ContentAlignment.MiddleCenter;
            this.label011.BorderStyle = BorderStyle.FixedSingle;
            this.label011.Location = new Point(0x1ef, 0xec);
            this.label011.Name = "label011";
            this.label011.Size = new Size(0x3d, 0x15);
            this.label011.TabIndex = 0x61;
            this.label011.TextAlign = ContentAlignment.MiddleCenter;
            this.label010.BorderStyle = BorderStyle.FixedSingle;
            this.label010.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label010.Location = new Point(0x1b3, 0xec);
            this.label010.Name = "label010";
            this.label010.Size = new Size(0x3d, 0x15);
            this.label010.TabIndex = 0x60;
            this.label010.TextAlign = ContentAlignment.MiddleCenter;
            this.label009.BorderStyle = BorderStyle.FixedSingle;
            this.label009.Location = new Point(0x178, 0xec);
            this.label009.Name = "label009";
            this.label009.Size = new Size(60, 0x15);
            this.label009.TabIndex = 0x5f;
            this.label009.TextAlign = ContentAlignment.MiddleCenter;
            this.label008.BorderStyle = BorderStyle.FixedSingle;
            this.label008.Location = new Point(0x13d, 0xec);
            this.label008.Name = "label008";
            this.label008.Size = new Size(60, 0x15);
            this.label008.TabIndex = 0x5e;
            this.label008.TextAlign = ContentAlignment.MiddleCenter;
            this.label122.BorderStyle = BorderStyle.FixedSingle;
            this.label122.Location = new Point(0x102, 0xd8);
            this.label122.Name = "label122";
            this.label122.Size = new Size(60, 0x15);
            this.label122.TabIndex = 0x5b;
            this.label122.Text = "厂房租金";
            this.label122.TextAlign = ContentAlignment.MiddleCenter;
            this.label123.BorderStyle = BorderStyle.FixedSingle;
            this.label123.Location = new Point(0xc7, 0xd8);
            this.label123.Name = "label123";
            this.label123.Size = new Size(60, 0x15);
            this.label123.TabIndex = 90;
            this.label123.Text = "设备维护";
            this.label123.TextAlign = ContentAlignment.MiddleCenter;
            this.label124.BorderStyle = BorderStyle.FixedSingle;
            this.label124.Location = new Point(0x85, 0xd8);
            this.label124.Name = "label124";
            this.label124.Size = new Size(0x43, 0x15);
            this.label124.TabIndex = 0x59;
            this.label124.Text = "广告投入";
            this.label124.TextAlign = ContentAlignment.MiddleCenter;
            this.label125.BorderStyle = BorderStyle.FixedSingle;
            this.label125.Location = new Point(0x4a, 0xd8);
            this.label125.Name = "label125";
            this.label125.Size = new Size(60, 0x15);
            this.label125.TabIndex = 0x58;
            this.label125.Text = "行政管理";
            this.label125.TextAlign = ContentAlignment.MiddleCenter;
            this.label136.BorderStyle = BorderStyle.FixedSingle;
            this.label136.Location = new Point(15, 0xd8);
            this.label136.Name = "label136";
            this.label136.Size = new Size(60, 0x15);
            this.label136.TabIndex = 0x57;
            this.label136.Text = "综合费用";
            this.label136.TextAlign = ContentAlignment.MiddleCenter;
            this.label007.BorderStyle = BorderStyle.FixedSingle;
            this.label007.Location = new Point(0x102, 0xec);
            this.label007.Name = "label007";
            this.label007.Size = new Size(60, 0x15);
            this.label007.TabIndex = 0x55;
            this.label007.TextAlign = ContentAlignment.MiddleCenter;
            this.label006.BorderStyle = BorderStyle.FixedSingle;
            this.label006.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label006.Location = new Point(0xc7, 0xec);
            this.label006.Name = "label006";
            this.label006.Size = new Size(60, 0x15);
            this.label006.TabIndex = 0x54;
            this.label006.TextAlign = ContentAlignment.MiddleCenter;
            this.label005.BackColor = Color.Transparent;
            this.label005.BorderStyle = BorderStyle.FixedSingle;
            this.label005.Location = new Point(0x85, 0xec);
            this.label005.Name = "label005";
            this.label005.Size = new Size(0x43, 0x15);
            this.label005.TabIndex = 0x53;
            this.label005.TextAlign = ContentAlignment.MiddleCenter;
            this.label004.BackColor = Color.Transparent;
            this.label004.BorderStyle = BorderStyle.FixedSingle;
            this.label004.Location = new Point(0x4a, 0xec);
            this.label004.Name = "label004";
            this.label004.Size = new Size(60, 0x15);
            this.label004.TabIndex = 0x52;
            this.label004.TextAlign = ContentAlignment.MiddleCenter;
            this.label150.BorderStyle = BorderStyle.FixedSingle;
            this.label150.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label150.Location = new Point(15, 0xec);
            this.label150.Name = "label150";
            this.label150.Size = new Size(60, 0x15);
            this.label150.TabIndex = 0x51;
            this.label150.Text = "金额";
            this.label150.TextAlign = ContentAlignment.MiddleCenter;
            this.tabPage2.Controls.Add(this.groupBox3);
            this.tabPage2.Controls.Add(this.groupBox2);
            this.tabPage2.Location = new Point(4, 0x15);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new Padding(3);
            this.tabPage2.Size = new Size(0x2e9, 0x164);
            this.tabPage2.TabIndex = 2;
            this.tabPage2.Text = "财务报表";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.groupBox3.Controls.Add(this.label3);
            this.groupBox3.Controls.Add(this.label064);
            this.groupBox3.Controls.Add(this.label18);
            this.groupBox3.Controls.Add(this.label054);
            this.groupBox3.Controls.Add(this.label20);
            this.groupBox3.Controls.Add(this.label21);
            this.groupBox3.Controls.Add(this.label22);
            this.groupBox3.Controls.Add(this.label053);
            this.groupBox3.Controls.Add(this.label24);
            this.groupBox3.Controls.Add(this.label063);
            this.groupBox3.Controls.Add(this.label26);
            this.groupBox3.Controls.Add(this.label052);
            this.groupBox3.Controls.Add(this.label28);
            this.groupBox3.Controls.Add(this.label062);
            this.groupBox3.Controls.Add(this.label43);
            this.groupBox3.Controls.Add(this.label051);
            this.groupBox3.Controls.Add(this.label49);
            this.groupBox3.Controls.Add(this.label061);
            this.groupBox3.Controls.Add(this.label55);
            this.groupBox3.Controls.Add(this.label050);
            this.groupBox3.Controls.Add(this.label61);
            this.groupBox3.Controls.Add(this.label060);
            this.groupBox3.Controls.Add(this.label67);
            this.groupBox3.Controls.Add(this.label049);
            this.groupBox3.Controls.Add(this.label73);
            this.groupBox3.Controls.Add(this.label055);
            this.groupBox3.Controls.Add(this.label79);
            this.groupBox3.Controls.Add(this.label044);
            this.groupBox3.Controls.Add(this.label85);
            this.groupBox3.Controls.Add(this.label88);
            this.groupBox3.Controls.Add(this.label91);
            this.groupBox3.Controls.Add(this.label048);
            this.groupBox3.Controls.Add(this.label97);
            this.groupBox3.Controls.Add(this.label059);
            this.groupBox3.Controls.Add(this.label103);
            this.groupBox3.Controls.Add(this.label106);
            this.groupBox3.Controls.Add(this.label109);
            this.groupBox3.Controls.Add(this.label058);
            this.groupBox3.Controls.Add(this.label115);
            this.groupBox3.Controls.Add(this.label047);
            this.groupBox3.Controls.Add(this.label120);
            this.groupBox3.Controls.Add(this.label057);
            this.groupBox3.Controls.Add(this.label129);
            this.groupBox3.Controls.Add(this.label046);
            this.groupBox3.Controls.Add(this.label131);
            this.groupBox3.Controls.Add(this.label056);
            this.groupBox3.Controls.Add(this.label133);
            this.groupBox3.Controls.Add(this.label045);
            this.groupBox3.Controls.Add(this.label135);
            this.groupBox3.Controls.Add(this.label141);
            this.groupBox3.Controls.Add(this.label142);
            this.groupBox3.Controls.Add(this.label143);
            this.groupBox3.Controls.Add(this.label144);
            this.groupBox3.Location = new Point(0x146, 11);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(0x17d, 0x153);
            this.groupBox3.TabIndex = 0xab;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "资产负债表";
            this.label3.AutoSize = true;
            this.label3.ForeColor = Color.Black;
            this.label3.Location = new Point(0x126, 0x1a);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x4d, 12);
            this.label3.TabIndex = 0xde;
            this.label3.Text = "单位：百万元";
            this.label064.BorderStyle = BorderStyle.FixedSingle;
            this.label064.Location = new Point(0x130, 0x125);
            this.label064.Name = "label064";
            this.label064.Size = new Size(0x43, 0x15);
            this.label064.TabIndex = 0xdd;
            this.label064.TextAlign = ContentAlignment.MiddleCenter;
            this.label18.BorderStyle = BorderStyle.FixedSingle;
            this.label18.Location = new Point(0xc0, 0x125);
            this.label18.Name = "label18";
            this.label18.Size = new Size(0x71, 0x15);
            this.label18.TabIndex = 220;
            this.label18.Text = "负债和权益总计(=)";
            this.label18.TextAlign = ContentAlignment.MiddleCenter;
            this.label054.BorderStyle = BorderStyle.FixedSingle;
            this.label054.Location = new Point(0x7e, 0x125);
            this.label054.Name = "label054";
            this.label054.Size = new Size(0x43, 0x15);
            this.label054.TabIndex = 0xdb;
            this.label054.TextAlign = ContentAlignment.MiddleCenter;
            this.label20.BorderStyle = BorderStyle.FixedSingle;
            this.label20.Location = new Point(0x13, 0x125);
            this.label20.Name = "label20";
            this.label20.Size = new Size(0x6c, 0x15);
            this.label20.TabIndex = 0xda;
            this.label20.Text = "资产总计(=)";
            this.label20.TextAlign = ContentAlignment.MiddleCenter;
            this.label21.BorderStyle = BorderStyle.FixedSingle;
            this.label21.Location = new Point(0x130, 0x111);
            this.label21.Name = "label21";
            this.label21.Size = new Size(0x43, 0x15);
            this.label21.TabIndex = 0xd9;
            this.label21.TextAlign = ContentAlignment.MiddleCenter;
            this.label22.BorderStyle = BorderStyle.FixedSingle;
            this.label22.Location = new Point(0xc0, 0x111);
            this.label22.Name = "label22";
            this.label22.Size = new Size(0x71, 0x15);
            this.label22.TabIndex = 0xd8;
            this.label22.TextAlign = ContentAlignment.MiddleCenter;
            this.label053.BorderStyle = BorderStyle.FixedSingle;
            this.label053.Location = new Point(0x7e, 0x111);
            this.label053.Name = "label053";
            this.label053.Size = new Size(0x43, 0x15);
            this.label053.TabIndex = 0xd7;
            this.label053.TextAlign = ContentAlignment.MiddleCenter;
            this.label24.BorderStyle = BorderStyle.FixedSingle;
            this.label24.Location = new Point(0x13, 0x111);
            this.label24.Name = "label24";
            this.label24.Size = new Size(0x6c, 0x15);
            this.label24.TabIndex = 0xd6;
            this.label24.Text = "流动资产合计(=)";
            this.label24.TextAlign = ContentAlignment.MiddleCenter;
            this.label063.BorderStyle = BorderStyle.FixedSingle;
            this.label063.Location = new Point(0x130, 0xfd);
            this.label063.Name = "label063";
            this.label063.Size = new Size(0x43, 0x15);
            this.label063.TabIndex = 0xd5;
            this.label063.TextAlign = ContentAlignment.MiddleCenter;
            this.label26.BorderStyle = BorderStyle.FixedSingle;
            this.label26.Location = new Point(0xc0, 0xfd);
            this.label26.Name = "label26";
            this.label26.Size = new Size(0x71, 0x15);
            this.label26.TabIndex = 0xd4;
            this.label26.Text = "所有者权益(=)";
            this.label26.TextAlign = ContentAlignment.MiddleCenter;
            this.label052.BorderStyle = BorderStyle.FixedSingle;
            this.label052.Location = new Point(0x7e, 0xfd);
            this.label052.Name = "label052";
            this.label052.Size = new Size(0x43, 0x15);
            this.label052.TabIndex = 0xd3;
            this.label052.TextAlign = ContentAlignment.MiddleCenter;
            this.label28.BorderStyle = BorderStyle.FixedSingle;
            this.label28.Location = new Point(0x13, 0xfd);
            this.label28.Name = "label28";
            this.label28.Size = new Size(0x6c, 0x15);
            this.label28.TabIndex = 210;
            this.label28.Text = "原料(+)";
            this.label28.TextAlign = ContentAlignment.MiddleCenter;
            this.label062.BorderStyle = BorderStyle.FixedSingle;
            this.label062.Location = new Point(0x130, 0xe9);
            this.label062.Name = "label062";
            this.label062.Size = new Size(0x43, 0x15);
            this.label062.TabIndex = 0xd1;
            this.label062.TextAlign = ContentAlignment.MiddleCenter;
            this.label43.BorderStyle = BorderStyle.FixedSingle;
            this.label43.Location = new Point(0xc0, 0xe9);
            this.label43.Name = "label43";
            this.label43.Size = new Size(0x71, 0x15);
            this.label43.TabIndex = 0xd0;
            this.label43.Text = "年度净利(+)";
            this.label43.TextAlign = ContentAlignment.MiddleCenter;
            this.label051.BorderStyle = BorderStyle.FixedSingle;
            this.label051.Location = new Point(0x7e, 0xe9);
            this.label051.Name = "label051";
            this.label051.Size = new Size(0x43, 0x15);
            this.label051.TabIndex = 0xcf;
            this.label051.TextAlign = ContentAlignment.MiddleCenter;
            this.label49.BorderStyle = BorderStyle.FixedSingle;
            this.label49.Location = new Point(0x13, 0xe9);
            this.label49.Name = "label49";
            this.label49.Size = new Size(0x6c, 0x15);
            this.label49.TabIndex = 0xce;
            this.label49.Text = "成品(+)";
            this.label49.TextAlign = ContentAlignment.MiddleCenter;
            this.label061.BorderStyle = BorderStyle.FixedSingle;
            this.label061.Location = new Point(0x130, 0xd5);
            this.label061.Name = "label061";
            this.label061.Size = new Size(0x43, 0x15);
            this.label061.TabIndex = 0xcd;
            this.label061.TextAlign = ContentAlignment.MiddleCenter;
            this.label55.BorderStyle = BorderStyle.FixedSingle;
            this.label55.Location = new Point(0xc0, 0xd5);
            this.label55.Name = "label55";
            this.label55.Size = new Size(0x71, 0x15);
            this.label55.TabIndex = 0xcc;
            this.label55.Text = "利润留存(+)";
            this.label55.TextAlign = ContentAlignment.MiddleCenter;
            this.label050.BorderStyle = BorderStyle.FixedSingle;
            this.label050.Location = new Point(0x7e, 0xd5);
            this.label050.Name = "label050";
            this.label050.Size = new Size(0x43, 0x15);
            this.label050.TabIndex = 0xcb;
            this.label050.TextAlign = ContentAlignment.MiddleCenter;
            this.label61.BorderStyle = BorderStyle.FixedSingle;
            this.label61.Location = new Point(0x13, 0xd5);
            this.label61.Name = "label61";
            this.label61.Size = new Size(0x6c, 0x15);
            this.label61.TabIndex = 0xca;
            this.label61.Text = "在制品(+)";
            this.label61.TextAlign = ContentAlignment.MiddleCenter;
            this.label060.BorderStyle = BorderStyle.FixedSingle;
            this.label060.Location = new Point(0x130, 0xc1);
            this.label060.Name = "label060";
            this.label060.Size = new Size(0x43, 0x15);
            this.label060.TabIndex = 0xc9;
            this.label060.Text = "永远不变45";
            this.label060.TextAlign = ContentAlignment.MiddleCenter;
            this.label67.BorderStyle = BorderStyle.FixedSingle;
            this.label67.Location = new Point(0xc0, 0xc1);
            this.label67.Name = "label67";
            this.label67.Size = new Size(0x71, 0x15);
            this.label67.TabIndex = 200;
            this.label67.Text = "股东资本(+)";
            this.label67.TextAlign = ContentAlignment.MiddleCenter;
            this.label049.BorderStyle = BorderStyle.FixedSingle;
            this.label049.Location = new Point(0x7e, 0xc1);
            this.label049.Name = "label049";
            this.label049.Size = new Size(0x43, 0x15);
            this.label049.TabIndex = 0xc7;
            this.label049.TextAlign = ContentAlignment.MiddleCenter;
            this.label73.BorderStyle = BorderStyle.FixedSingle;
            this.label73.Location = new Point(0x13, 0xc1);
            this.label73.Name = "label73";
            this.label73.Size = new Size(0x6c, 0x15);
            this.label73.TabIndex = 0xc6;
            this.label73.Text = "应收款(+)";
            this.label73.TextAlign = ContentAlignment.MiddleCenter;
            this.label055.BorderStyle = BorderStyle.FixedSingle;
            this.label055.Location = new Point(0x130, 0x35);
            this.label055.Name = "label055";
            this.label055.Size = new Size(0x43, 0x15);
            this.label055.TabIndex = 0xc5;
            this.label055.Text = "第0年";
            this.label055.TextAlign = ContentAlignment.MiddleCenter;
            this.label79.BorderStyle = BorderStyle.FixedSingle;
            this.label79.Location = new Point(0xc0, 0x35);
            this.label79.Name = "label79";
            this.label79.Size = new Size(0x71, 0x15);
            this.label79.TabIndex = 0xc4;
            this.label79.Text = "负债+权益";
            this.label79.TextAlign = ContentAlignment.MiddleCenter;
            this.label044.BorderStyle = BorderStyle.FixedSingle;
            this.label044.Location = new Point(0x7e, 0x35);
            this.label044.Name = "label044";
            this.label044.Size = new Size(0x43, 0x15);
            this.label044.TabIndex = 0xc3;
            this.label044.Text = "第0年";
            this.label044.TextAlign = ContentAlignment.MiddleCenter;
            this.label85.BorderStyle = BorderStyle.FixedSingle;
            this.label85.Location = new Point(0x13, 0x35);
            this.label85.Name = "label85";
            this.label85.Size = new Size(0x6c, 0x15);
            this.label85.TabIndex = 0xc2;
            this.label85.Text = "资产";
            this.label85.TextAlign = ContentAlignment.MiddleCenter;
            this.label88.BorderStyle = BorderStyle.FixedSingle;
            this.label88.Location = new Point(0x130, 0xad);
            this.label88.Name = "label88";
            this.label88.Size = new Size(0x43, 0x15);
            this.label88.TabIndex = 0xc1;
            this.label88.TextAlign = ContentAlignment.MiddleCenter;
            this.label91.BorderStyle = BorderStyle.FixedSingle;
            this.label91.Font = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.label91.Location = new Point(0xc0, 0xad);
            this.label91.Name = "label91";
            this.label91.Size = new Size(0x71, 0x15);
            this.label91.TabIndex = 0xc0;
            this.label91.Text = "权益";
            this.label91.TextAlign = ContentAlignment.MiddleCenter;
            this.label048.BorderStyle = BorderStyle.FixedSingle;
            this.label048.Location = new Point(0x7e, 0xad);
            this.label048.Name = "label048";
            this.label048.Size = new Size(0x43, 0x15);
            this.label048.TabIndex = 0xbf;
            this.label048.TextAlign = ContentAlignment.MiddleCenter;
            this.label97.BorderStyle = BorderStyle.FixedSingle;
            this.label97.Location = new Point(0x13, 0xad);
            this.label97.Name = "label97";
            this.label97.Size = new Size(0x6c, 0x15);
            this.label97.TabIndex = 190;
            this.label97.Text = "现金(+)";
            this.label97.TextAlign = ContentAlignment.MiddleCenter;
            this.label059.BorderStyle = BorderStyle.FixedSingle;
            this.label059.Location = new Point(0x130, 0x99);
            this.label059.Name = "label059";
            this.label059.Size = new Size(0x43, 0x15);
            this.label059.TabIndex = 0xbd;
            this.label059.TextAlign = ContentAlignment.MiddleCenter;
            this.label103.BorderStyle = BorderStyle.FixedSingle;
            this.label103.Location = new Point(0xc0, 0x99);
            this.label103.Name = "label103";
            this.label103.Size = new Size(0x71, 0x15);
            this.label103.TabIndex = 0xbc;
            this.label103.Text = "负债合计(=)";
            this.label103.TextAlign = ContentAlignment.MiddleCenter;
            this.label106.BorderStyle = BorderStyle.FixedSingle;
            this.label106.Location = new Point(0x7e, 0x99);
            this.label106.Name = "label106";
            this.label106.Size = new Size(0x43, 0x15);
            this.label106.TabIndex = 0xbb;
            this.label106.TextAlign = ContentAlignment.MiddleCenter;
            this.label109.BorderStyle = BorderStyle.FixedSingle;
            this.label109.Font = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.label109.Location = new Point(0x13, 0x99);
            this.label109.Name = "label109";
            this.label109.Size = new Size(0x6c, 0x15);
            this.label109.TabIndex = 0xba;
            this.label109.Text = "流动资产";
            this.label109.TextAlign = ContentAlignment.MiddleCenter;
            this.label058.BorderStyle = BorderStyle.FixedSingle;
            this.label058.Location = new Point(0x130, 0x85);
            this.label058.Name = "label058";
            this.label058.Size = new Size(0x43, 0x15);
            this.label058.TabIndex = 0xb9;
            this.label058.TextAlign = ContentAlignment.MiddleCenter;
            this.label115.BorderStyle = BorderStyle.FixedSingle;
            this.label115.Location = new Point(0xc0, 0x85);
            this.label115.Name = "label115";
            this.label115.Size = new Size(0x71, 0x15);
            this.label115.TabIndex = 0xb8;
            this.label115.Text = "应付税金(+)";
            this.label115.TextAlign = ContentAlignment.MiddleCenter;
            this.label047.BorderStyle = BorderStyle.FixedSingle;
            this.label047.Location = new Point(0x7e, 0x85);
            this.label047.Name = "label047";
            this.label047.Size = new Size(0x43, 0x15);
            this.label047.TabIndex = 0xb7;
            this.label047.TextAlign = ContentAlignment.MiddleCenter;
            this.label120.BorderStyle = BorderStyle.FixedSingle;
            this.label120.Location = new Point(0x13, 0x85);
            this.label120.Name = "label120";
            this.label120.Size = new Size(0x6c, 0x15);
            this.label120.TabIndex = 0xb6;
            this.label120.Text = "固定资产合计(=)";
            this.label120.TextAlign = ContentAlignment.MiddleCenter;
            this.label057.BorderStyle = BorderStyle.FixedSingle;
            this.label057.Location = new Point(0x130, 0x71);
            this.label057.Name = "label057";
            this.label057.Size = new Size(0x43, 0x15);
            this.label057.TabIndex = 0xb5;
            this.label057.TextAlign = ContentAlignment.MiddleCenter;
            this.label129.BorderStyle = BorderStyle.FixedSingle;
            this.label129.Location = new Point(0xc0, 0x71);
            this.label129.Name = "label129";
            this.label129.Size = new Size(0x71, 0x15);
            this.label129.TabIndex = 180;
            this.label129.Text = "短期及高利(+)";
            this.label129.TextAlign = ContentAlignment.MiddleCenter;
            this.label046.BorderStyle = BorderStyle.FixedSingle;
            this.label046.Location = new Point(0x7e, 0x71);
            this.label046.Name = "label046";
            this.label046.Size = new Size(0x43, 0x15);
            this.label046.TabIndex = 0xb3;
            this.label046.TextAlign = ContentAlignment.MiddleCenter;
            this.label131.BorderStyle = BorderStyle.FixedSingle;
            this.label131.Location = new Point(0x13, 0x71);
            this.label131.Name = "label131";
            this.label131.Size = new Size(0x6c, 0x15);
            this.label131.TabIndex = 0xb2;
            this.label131.Text = "设备及在建(+)";
            this.label131.TextAlign = ContentAlignment.MiddleCenter;
            this.label056.BorderStyle = BorderStyle.FixedSingle;
            this.label056.Location = new Point(0x130, 0x5d);
            this.label056.Name = "label056";
            this.label056.Size = new Size(0x43, 0x15);
            this.label056.TabIndex = 0xb1;
            this.label056.TextAlign = ContentAlignment.MiddleCenter;
            this.label133.BorderStyle = BorderStyle.FixedSingle;
            this.label133.Location = new Point(0xc0, 0x5d);
            this.label133.Name = "label133";
            this.label133.Size = new Size(0x71, 0x15);
            this.label133.TabIndex = 0xb0;
            this.label133.Text = "长期负债(+)";
            this.label133.TextAlign = ContentAlignment.MiddleCenter;
            this.label045.BorderStyle = BorderStyle.FixedSingle;
            this.label045.Location = new Point(0x7e, 0x5d);
            this.label045.Name = "label045";
            this.label045.Size = new Size(0x43, 0x15);
            this.label045.TabIndex = 0xaf;
            this.label045.TextAlign = ContentAlignment.MiddleCenter;
            this.label135.BorderStyle = BorderStyle.FixedSingle;
            this.label135.Location = new Point(0x13, 0x5d);
            this.label135.Name = "label135";
            this.label135.Size = new Size(0x6c, 0x15);
            this.label135.TabIndex = 0xae;
            this.label135.Text = "厂房(+)";
            this.label135.TextAlign = ContentAlignment.MiddleCenter;
            this.label141.BorderStyle = BorderStyle.FixedSingle;
            this.label141.Location = new Point(0x130, 0x49);
            this.label141.Name = "label141";
            this.label141.Size = new Size(0x43, 0x15);
            this.label141.TabIndex = 0xad;
            this.label141.TextAlign = ContentAlignment.MiddleCenter;
            this.label142.BorderStyle = BorderStyle.FixedSingle;
            this.label142.Font = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.label142.Location = new Point(0xc0, 0x49);
            this.label142.Name = "label142";
            this.label142.Size = new Size(0x71, 0x15);
            this.label142.TabIndex = 0xac;
            this.label142.Text = "负债";
            this.label142.TextAlign = ContentAlignment.MiddleCenter;
            this.label143.BorderStyle = BorderStyle.FixedSingle;
            this.label143.Location = new Point(0x7e, 0x49);
            this.label143.Name = "label143";
            this.label143.Size = new Size(0x43, 0x15);
            this.label143.TabIndex = 0xab;
            this.label143.TextAlign = ContentAlignment.MiddleCenter;
            this.label144.BorderStyle = BorderStyle.FixedSingle;
            this.label144.Font = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.label144.Location = new Point(0x13, 0x49);
            this.label144.Name = "label144";
            this.label144.Size = new Size(0x6c, 0x15);
            this.label144.TabIndex = 170;
            this.label144.Text = "固定资产";
            this.label144.TextAlign = ContentAlignment.MiddleCenter;
            this.groupBox2.Controls.Add(this.label068);
            this.groupBox2.Controls.Add(this.label27);
            this.groupBox2.Controls.Add(this.label067);
            this.groupBox2.Controls.Add(this.label23);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Controls.Add(this.label031);
            this.groupBox2.Controls.Add(this.label043);
            this.groupBox2.Controls.Add(this.label042);
            this.groupBox2.Controls.Add(this.label041);
            this.groupBox2.Controls.Add(this.label039);
            this.groupBox2.Controls.Add(this.label038);
            this.groupBox2.Controls.Add(this.label037);
            this.groupBox2.Controls.Add(this.label036);
            this.groupBox2.Controls.Add(this.label035);
            this.groupBox2.Controls.Add(this.label034);
            this.groupBox2.Controls.Add(this.label033);
            this.groupBox2.Controls.Add(this.label032);
            this.groupBox2.Controls.Add(this.label15);
            this.groupBox2.Controls.Add(this.label12);
            this.groupBox2.Controls.Add(this.label13);
            this.groupBox2.Controls.Add(this.label9);
            this.groupBox2.Controls.Add(this.label10);
            this.groupBox2.Controls.Add(this.label11);
            this.groupBox2.Controls.Add(this.label6);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Controls.Add(this.label8);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.label1);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Location = new Point(0x1a, 11);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(0xfc, 0x153);
            this.groupBox2.TabIndex = 170;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "损益表";
            this.label068.BorderStyle = BorderStyle.FixedSingle;
            this.label068.Location = new Point(0x80, 0xf2);
            this.label068.Name = "label068";
            this.label068.Size = new Size(0x66, 0x15);
            this.label068.TabIndex = 0x70;
            this.label068.TextAlign = ContentAlignment.MiddleCenter;
            this.label27.BorderStyle = BorderStyle.FixedSingle;
            this.label27.Location = new Point(0x11, 0xf2);
            this.label27.Name = "label27";
            this.label27.Size = new Size(0x70, 0x15);
            this.label27.TabIndex = 0x6f;
            this.label27.Text = "额外支出(-)";
            this.label27.TextAlign = ContentAlignment.MiddleCenter;
            this.label067.BorderStyle = BorderStyle.FixedSingle;
            this.label067.Location = new Point(0x80, 0xde);
            this.label067.Name = "label067";
            this.label067.Size = new Size(0x66, 0x15);
            this.label067.TabIndex = 110;
            this.label067.TextAlign = ContentAlignment.MiddleCenter;
            this.label23.BorderStyle = BorderStyle.FixedSingle;
            this.label23.Location = new Point(0x11, 0xde);
            this.label23.Name = "label23";
            this.label23.Size = new Size(0x70, 0x15);
            this.label23.TabIndex = 0x6d;
            this.label23.Text = "额外收入(+)";
            this.label23.TextAlign = ContentAlignment.MiddleCenter;
            this.label2.AutoSize = true;
            this.label2.ForeColor = Color.Black;
            this.label2.Location = new Point(0x99, 0x11);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x4d, 12);
            this.label2.TabIndex = 0x6c;
            this.label2.Text = "单位：百万元";
            this.label031.BorderStyle = BorderStyle.FixedSingle;
            this.label031.Location = new Point(0x80, 0x2a);
            this.label031.Name = "label031";
            this.label031.Size = new Size(0x66, 0x15);
            this.label031.TabIndex = 0x6b;
            this.label031.Text = "第0年";
            this.label031.TextAlign = ContentAlignment.MiddleCenter;
            this.label043.BorderStyle = BorderStyle.FixedSingle;
            this.label043.Location = new Point(0x80, 0x12e);
            this.label043.Name = "label043";
            this.label043.Size = new Size(0x66, 0x15);
            this.label043.TabIndex = 0x6a;
            this.label043.TextAlign = ContentAlignment.MiddleCenter;
            this.label042.BorderStyle = BorderStyle.FixedSingle;
            this.label042.Location = new Point(0x80, 0x11a);
            this.label042.Name = "label042";
            this.label042.Size = new Size(0x66, 0x15);
            this.label042.TabIndex = 0x69;
            this.label042.TextAlign = ContentAlignment.MiddleCenter;
            this.label041.BorderStyle = BorderStyle.FixedSingle;
            this.label041.Location = new Point(0x80, 0x106);
            this.label041.Name = "label041";
            this.label041.Size = new Size(0x66, 0x15);
            this.label041.TabIndex = 0x68;
            this.label041.TextAlign = ContentAlignment.MiddleCenter;
            this.label039.BorderStyle = BorderStyle.FixedSingle;
            this.label039.Location = new Point(0x80, 0xca);
            this.label039.Name = "label039";
            this.label039.Size = new Size(0x66, 0x15);
            this.label039.TabIndex = 0x66;
            this.label039.TextAlign = ContentAlignment.MiddleCenter;
            this.label038.BorderStyle = BorderStyle.FixedSingle;
            this.label038.Location = new Point(0x80, 0xb6);
            this.label038.Name = "label038";
            this.label038.Size = new Size(0x66, 0x15);
            this.label038.TabIndex = 0x65;
            this.label038.TextAlign = ContentAlignment.MiddleCenter;
            this.label037.BorderStyle = BorderStyle.FixedSingle;
            this.label037.Location = new Point(0x80, 0xa2);
            this.label037.Name = "label037";
            this.label037.Size = new Size(0x66, 0x15);
            this.label037.TabIndex = 100;
            this.label037.TextAlign = ContentAlignment.MiddleCenter;
            this.label036.BorderStyle = BorderStyle.FixedSingle;
            this.label036.Location = new Point(0x80, 0x8e);
            this.label036.Name = "label036";
            this.label036.Size = new Size(0x66, 0x15);
            this.label036.TabIndex = 0x63;
            this.label036.TextAlign = ContentAlignment.MiddleCenter;
            this.label035.BorderStyle = BorderStyle.FixedSingle;
            this.label035.Location = new Point(0x80, 0x7a);
            this.label035.Name = "label035";
            this.label035.Size = new Size(0x66, 0x15);
            this.label035.TabIndex = 0x62;
            this.label035.TextAlign = ContentAlignment.MiddleCenter;
            this.label034.BorderStyle = BorderStyle.FixedSingle;
            this.label034.Location = new Point(0x80, 0x66);
            this.label034.Name = "label034";
            this.label034.Size = new Size(0x66, 0x15);
            this.label034.TabIndex = 0x61;
            this.label034.TextAlign = ContentAlignment.MiddleCenter;
            this.label033.BorderStyle = BorderStyle.FixedSingle;
            this.label033.Location = new Point(0x80, 0x52);
            this.label033.Name = "label033";
            this.label033.Size = new Size(0x66, 0x15);
            this.label033.TabIndex = 0x60;
            this.label033.TextAlign = ContentAlignment.MiddleCenter;
            this.label032.BorderStyle = BorderStyle.FixedSingle;
            this.label032.Location = new Point(0x80, 0x3e);
            this.label032.Name = "label032";
            this.label032.Size = new Size(0x66, 0x15);
            this.label032.TabIndex = 0x5f;
            this.label032.TextAlign = ContentAlignment.MiddleCenter;
            this.label15.BorderStyle = BorderStyle.FixedSingle;
            this.label15.Location = new Point(0x11, 0x12e);
            this.label15.Name = "label15";
            this.label15.Size = new Size(0x70, 0x15);
            this.label15.TabIndex = 0x5e;
            this.label15.Text = "净利润(=)";
            this.label15.TextAlign = ContentAlignment.MiddleCenter;
            this.label12.BorderStyle = BorderStyle.FixedSingle;
            this.label12.Location = new Point(0x11, 0x11a);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x70, 0x15);
            this.label12.TabIndex = 0x5d;
            this.label12.Text = "所得税(-)";
            this.label12.TextAlign = ContentAlignment.MiddleCenter;
            this.label13.BorderStyle = BorderStyle.FixedSingle;
            this.label13.Location = new Point(0x11, 0x106);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x70, 0x15);
            this.label13.TabIndex = 0x5c;
            this.label13.Text = "税前利润(=)";
            this.label13.TextAlign = ContentAlignment.MiddleCenter;
            this.label9.BorderStyle = BorderStyle.FixedSingle;
            this.label9.Location = new Point(0x11, 0xca);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x70, 0x15);
            this.label9.TabIndex = 90;
            this.label9.Text = "利息与贴现(-)";
            this.label9.TextAlign = ContentAlignment.MiddleCenter;
            this.label10.BorderStyle = BorderStyle.FixedSingle;
            this.label10.Location = new Point(0x11, 0xb6);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x70, 0x15);
            this.label10.TabIndex = 0x59;
            this.label10.Text = "支付利息前利润(=)";
            this.label10.TextAlign = ContentAlignment.MiddleCenter;
            this.label11.BorderStyle = BorderStyle.FixedSingle;
            this.label11.Location = new Point(0x11, 0xa2);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x70, 0x15);
            this.label11.TabIndex = 0x58;
            this.label11.Text = "折旧(-)";
            this.label11.TextAlign = ContentAlignment.MiddleCenter;
            this.label6.BorderStyle = BorderStyle.FixedSingle;
            this.label6.Location = new Point(0x11, 0x8e);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x70, 0x15);
            this.label6.TabIndex = 0x57;
            this.label6.Text = "折旧前利润(=)";
            this.label6.TextAlign = ContentAlignment.MiddleCenter;
            this.label7.BorderStyle = BorderStyle.FixedSingle;
            this.label7.Location = new Point(0x11, 0x7a);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x70, 0x15);
            this.label7.TabIndex = 0x56;
            this.label7.Text = "综合费用(-)";
            this.label7.TextAlign = ContentAlignment.MiddleCenter;
            this.label8.BorderStyle = BorderStyle.FixedSingle;
            this.label8.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label8.Location = new Point(0x11, 0x66);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x70, 0x15);
            this.label8.TabIndex = 0x55;
            this.label8.Text = "毛利(=)";
            this.label8.TextAlign = ContentAlignment.MiddleCenter;
            this.label4.BorderStyle = BorderStyle.FixedSingle;
            this.label4.Location = new Point(0x11, 0x52);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x70, 0x15);
            this.label4.TabIndex = 0x54;
            this.label4.Text = "直接成本(-)";
            this.label4.TextAlign = ContentAlignment.MiddleCenter;
            this.label1.BorderStyle = BorderStyle.FixedSingle;
            this.label1.Location = new Point(0x11, 0x3e);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x70, 0x15);
            this.label1.TabIndex = 0x53;
            this.label1.Text = "销售(+)";
            this.label1.TextAlign = ContentAlignment.MiddleCenter;
            this.label5.BorderStyle = BorderStyle.FixedSingle;
            this.label5.Location = new Point(0x11, 0x2a);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x70, 0x15);
            this.label5.TabIndex = 0x52;
            this.label5.TextAlign = ContentAlignment.MiddleCenter;
            this.comboBox1.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox1.FormattingEnabled = true;
            object[] items = new object[] { "第0年", "第1年", "第2年", "第3年" };
            this.comboBox1.Items.AddRange(items);
            this.comboBox1.Location = new Point(60, 390);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new Size(0x79, 20);
            this.comboBox1.TabIndex = 5;
            this.comboBox1.SelectedIndexChanged += new EventHandler(this.comboBox1_SelectedIndexChanged);
            this.label188.AutoSize = true;
            this.label188.Location = new Point(13, 0x189);
            this.label188.Name = "label188";
            this.label188.Size = new Size(0x29, 12);
            this.label188.TabIndex = 6;
            this.label188.Text = "选择：";
            base.AcceptButton = this.button1;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(0x2f1, 0x1a3);
            base.Controls.Add(this.label188);
            base.Controls.Add(this.comboBox1);
            base.Controls.Add(this.tabControl);
            base.Controls.Add(this.button1);
            base.FormBorderStyle = FormBorderStyle.FixedDialog;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmShowBusinessResult";
            base.ShowInTaskbar = false;
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "查看经营结果";
            base.Load += new EventHandler(this.frmShowBusinessResult_Load);
            this.tabControl.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            ((ISupportInitialize) this.dataGridViewCJDHH).EndInit();
            this.tabPage2.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }
    }
}

