namespace ERPChess
{
    using BusinessTier;
    using ERPChess.Properties;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class frmShowTableInfor : Form
    {
        private IContainer components;
        private PictureBox pictureBox1;
        private Button button1;
        private Label label21;
        private Label label034;
        private Label label035;
        private Label label27;
        private Label label039;
        private Label label038;
        private Label label048;
        private Label label037;
        private Label label040;
        private Label label001;
        private Label label012;
        private Label label011;
        private Label label013;
        private Label label014;
        private Label label036;
        private Label label002;
        private Label label015;
        private Label label016;
        private Label label017;
        private Label label018;
        private Label label003;
        private Label label007;
        private Label label006;
        private Label label005;
        private Label label004;
        private Label label010;
        private Label label009;
        private Label label008;
        private Label labelDD;
        private Label label031;
        private Label label032;
        private Label label033;
        private Label label041;
        private Label label042;
        private Label label043;
        private Label label044;
        private Label label045;
        private Label label046;
        private Label label020;
        private Label label024;
        private Label label026;
        private Label label019;
        private Label label021;
        private Label label022;
        private Label label023;
        private Label label025;
        private Label label027;
        private Label label028;
        private Label label029;
        private Label label030;
        private Label label29;
        private Label label1;
        private Label label047;
        private PictureBox pictureBox2;
        private Label label6;
        private PictureBox pictureBox3;

        public frmShowTableInfor()
        {
            this.InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void frmShowTableInfor_Load(object sender, EventArgs e)
        {
            this.label001.Text = !TGlobals.step4 ? " " : TGlobals.currentActor.CurrBusinessConditions.BalanceSheet.Taxes.ToString();
            this.label002.Text = TGlobals.currentActor.CurrBusinessConditions.OperatingSheet.CurrentCash.ToString();
            TRawMaterialOrder theLastOrder = TGlobals.currentActor.RawMaterialStock.TheLastOrder;
            this.label003.Text = theLastOrder.R1.Amount.ToString();
            this.label004.Text = theLastOrder.R2.Amount.ToString();
            this.label005.Text = theLastOrder.R3.Amount.ToString();
            this.label006.Text = theLastOrder.R4.Amount.ToString();
            TRawMaterialOrder statisticsOrder = TGlobals.currentActor.RawMaterialStock.StatisticsOrder;
            this.label007.Text = statisticsOrder.R1.Amount.ToString();
            this.label008.Text = statisticsOrder.R2.Amount.ToString();
            this.label009.Text = statisticsOrder.R3.Amount.ToString();
            this.label010.Text = statisticsOrder.R4.Amount.ToString();
            this.label011.Text = (TGlobals.currentActor.PlantA.PlantAttribute != PlantAttribute.购买) ? "0" : TGlobals.currentActor.PlantA.PurchasePrice.ToString();
            this.label013.Text = (TGlobals.currentActor.PlantB.PlantAttribute != PlantAttribute.购买) ? "0" : TGlobals.currentActor.PlantB.PurchasePrice.ToString();
            this.label014.Text = (TGlobals.currentActor.PlantC.PlantAttribute != PlantAttribute.购买) ? "0" : TGlobals.currentActor.PlantC.PurchasePrice.ToString();
            this.label012.Text = TGlobals.currentActor.CurrBusinessConditions.OperatingSheet.Equipment.ToString();
            this.label015.Text = (TGlobals.currentActor.P1Warehouse.InventoryAmount / 2).ToString();
            this.label016.Text = (TGlobals.currentActor.P2Warehouse.InventoryAmount / 3).ToString();
            this.label017.Text = (TGlobals.currentActor.P3Warehouse.InventoryAmount / 4).ToString();
            this.label018.Text = (TGlobals.currentActor.P4Warehouse.InventoryAmount / 5).ToString();
            this.label019.Text = TGlobals.currentActor.PlantA.PL1.ToString();
            this.label020.Text = TGlobals.currentActor.PlantA.PL2.ToString();
            this.label021.Text = TGlobals.currentActor.PlantA.PL3.ToString();
            this.label022.Text = TGlobals.currentActor.PlantA.PL4.ToString();
            this.label023.Text = TGlobals.currentActor.PlantB.PL5.ToString();
            this.label024.Text = TGlobals.currentActor.PlantB.PL6.ToString();
            this.label025.Text = TGlobals.currentActor.PlantB.PL7.ToString();
            this.label026.Text = TGlobals.currentActor.PlantC.PL8.ToString();
            this.label027.Text = TGlobals.currentActor.CurrBusinessConditions.OperatingSheet.ReceivableAccountsQ1.ToString();
            this.label028.Text = TGlobals.currentActor.CurrBusinessConditions.OperatingSheet.ReceivableAccountsQ2.ToString();
            this.label029.Text = TGlobals.currentActor.CurrBusinessConditions.OperatingSheet.ReceivableAccountsQ3.ToString();
            this.label030.Text = TGlobals.currentActor.CurrBusinessConditions.OperatingSheet.ReceivableAccountsQ4.ToString();
            this.label031.Text = TGlobals.currentActor.YFP2Cost.ToString();
            this.label032.Text = TGlobals.currentActor.YFP3Cost.ToString();
            this.label033.Text = TGlobals.currentActor.YFP4Cost.ToString();
            this.label034.Text = !TGlobals.step14 ? "  " : TGlobals.currentActor.CurrBusinessConditions.ComprehensiveCostSheet.ProductDevelopment.ToString();
            this.label035.Text = !TGlobals.step2 ? "  " : TGlobals.currentActor.CurrBusinessConditions.ComprehensiveCostSheet.Advertisement.ToString();
            this.label036.Text = !TGlobals.step15 ? " " : TGlobals.currentActor.CurrBusinessConditions.ComprehensiveCostSheet.Administration.ToString();
            this.label037.Text = !TGlobals.step5 ? " " : TGlobals.currentActor.CurrBusinessConditions.FinancialSheet.Interest.ToString();
            this.label038.Text = !TGlobals.step50 ? " " : TGlobals.currentActor.CurrBusinessConditions.ComprehensiveCostSheet.EquipmentMaintenance.ToString();
            this.label039.Text = !TGlobals.step51 ? " " : TGlobals.currentActor.CurrBusinessConditions.ComprehensiveCostSheet.RentPlant.ToString();
            this.label040.Text = !TGlobals.step52 ? " " : TGlobals.currentActor.CurrBusinessConditions.FinancialSheet.Depreciation.ToString();
            this.label041.Text = TGlobals.currentActor.JRQYCost.ToString();
            this.label042.Text = TGlobals.currentActor.JRGNCost.ToString();
            this.label043.Text = TGlobals.currentActor.JRYZCost.ToString();
            this.label044.Text = TGlobals.currentActor.JRGJCost.ToString();
            this.label045.Text = TGlobals.currentActor.TZISO9000Cost.ToString();
            this.label046.Text = TGlobals.currentActor.TZISO14000Cost.ToString();
            this.label047.Text = TGlobals.currentActor.CurrBusinessConditions.OperatingSheet.Construction.ToString();
            if (TGlobals.currentActor.CurrBusinessConditions.FinancialSheet.Discount > 0)
            {
                this.label048.Text = TGlobals.currentActor.CurrBusinessConditions.FinancialSheet.Discount.ToString();
            }
            else
            {
                this.label048.Text = " ";
            }
        }

        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(frmShowTableInfor));
            this.pictureBox1 = new PictureBox();
            this.button1 = new Button();
            this.label21 = new Label();
            this.label034 = new Label();
            this.label035 = new Label();
            this.label27 = new Label();
            this.label039 = new Label();
            this.label038 = new Label();
            this.label048 = new Label();
            this.label037 = new Label();
            this.label040 = new Label();
            this.label001 = new Label();
            this.label012 = new Label();
            this.label011 = new Label();
            this.label013 = new Label();
            this.label014 = new Label();
            this.label036 = new Label();
            this.label002 = new Label();
            this.label015 = new Label();
            this.label016 = new Label();
            this.label017 = new Label();
            this.label018 = new Label();
            this.label003 = new Label();
            this.label007 = new Label();
            this.label006 = new Label();
            this.label005 = new Label();
            this.label004 = new Label();
            this.label010 = new Label();
            this.label009 = new Label();
            this.label008 = new Label();
            this.labelDD = new Label();
            this.label031 = new Label();
            this.label032 = new Label();
            this.label033 = new Label();
            this.label041 = new Label();
            this.label042 = new Label();
            this.label043 = new Label();
            this.label044 = new Label();
            this.label045 = new Label();
            this.label046 = new Label();
            this.label020 = new Label();
            this.label024 = new Label();
            this.label026 = new Label();
            this.label019 = new Label();
            this.label021 = new Label();
            this.label022 = new Label();
            this.label023 = new Label();
            this.label025 = new Label();
            this.label027 = new Label();
            this.label028 = new Label();
            this.label029 = new Label();
            this.label030 = new Label();
            this.label29 = new Label();
            this.label1 = new Label();
            this.label047 = new Label();
            this.pictureBox2 = new PictureBox();
            this.label6 = new Label();
            this.pictureBox3 = new PictureBox();
            ((ISupportInitialize) this.pictureBox1).BeginInit();
            ((ISupportInitialize) this.pictureBox2).BeginInit();
            ((ISupportInitialize) this.pictureBox3).BeginInit();
            base.SuspendLayout();
            this.pictureBox1.Dock = DockStyle.Top;
            this.pictureBox1.Image = Resources.Table;
            this.pictureBox1.Location = new Point(0, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new Size(0x32e, 0x252);
            this.pictureBox1.SizeMode = PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            this.button1.DialogResult = DialogResult.OK;
            this.button1.Location = new Point(0x2d7, 600);
            this.button1.Name = "button1";
            this.button1.Size = new Size(0x4b, 0x17);
            this.button1.TabIndex = 1;
            this.button1.Text = "确定";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new EventHandler(this.button1_Click);
            this.label21.BorderStyle = BorderStyle.Fixed3D;
            this.label21.Cursor = Cursors.Hand;
            this.label21.Location = new Point(0x242, 0xdf);
            this.label21.Name = "label21";
            this.label21.Size = new Size(0x2e, 0x16);
            this.label21.TabIndex = 0x16;
            this.label21.Tag = "2";
            this.label21.Text = "查看";
            this.label21.TextAlign = ContentAlignment.MiddleCenter;
            this.label21.Click += new EventHandler(this.label_Click);
            this.label034.BackColor = Color.PaleGreen;
            this.label034.BorderStyle = BorderStyle.FixedSingle;
            this.label034.Font = new Font("宋体", 13f);
            this.label034.Location = new Point(0x307, 0x41);
            this.label034.Name = "label034";
            this.label034.Size = new Size(30, 0x18);
            this.label034.TabIndex = 0x1b;
            this.label034.Tag = "26";
            this.label034.Text = "-1";
            this.label034.TextAlign = ContentAlignment.MiddleCenter;
            this.label035.BackColor = Color.PaleGreen;
            this.label035.BorderStyle = BorderStyle.FixedSingle;
            this.label035.Font = new Font("宋体", 13f);
            this.label035.Location = new Point(0x307, 0x6b);
            this.label035.Name = "label035";
            this.label035.Size = new Size(30, 0x18);
            this.label035.TabIndex = 0x26;
            this.label035.Tag = "26";
            this.label035.Text = "-1";
            this.label035.TextAlign = ContentAlignment.MiddleCenter;
            this.label27.BackColor = Color.PaleGreen;
            this.label27.BorderStyle = BorderStyle.FixedSingle;
            this.label27.Font = new Font("宋体", 13f);
            this.label27.Location = new Point(0x307, 0x161);
            this.label27.Name = "label27";
            this.label27.Size = new Size(30, 0x18);
            this.label27.TabIndex = 0x27;
            this.label27.Tag = "26";
            this.label27.TextAlign = ContentAlignment.MiddleCenter;
            this.label039.BackColor = Color.PaleGreen;
            this.label039.BorderStyle = BorderStyle.FixedSingle;
            this.label039.Font = new Font("宋体", 13f);
            this.label039.Location = new Point(0x307, 0xfe);
            this.label039.Name = "label039";
            this.label039.Size = new Size(30, 0x18);
            this.label039.TabIndex = 40;
            this.label039.Tag = "26";
            this.label039.Text = "-1";
            this.label039.TextAlign = ContentAlignment.MiddleCenter;
            this.label038.BackColor = Color.PaleGreen;
            this.label038.BorderStyle = BorderStyle.FixedSingle;
            this.label038.Font = new Font("宋体", 13f);
            this.label038.Location = new Point(0x307, 0x9d);
            this.label038.Name = "label038";
            this.label038.Size = new Size(30, 0x18);
            this.label038.TabIndex = 0x2a;
            this.label038.Tag = "26";
            this.label038.Text = "-1";
            this.label038.TextAlign = ContentAlignment.MiddleCenter;
            this.label048.BackColor = Color.PaleGreen;
            this.label048.BorderStyle = BorderStyle.FixedSingle;
            this.label048.Font = new Font("宋体", 13f);
            this.label048.Location = new Point(0x307, 500);
            this.label048.Name = "label048";
            this.label048.Size = new Size(30, 0x18);
            this.label048.TabIndex = 0x2b;
            this.label048.Tag = "26";
            this.label048.Text = "-1";
            this.label048.TextAlign = ContentAlignment.MiddleCenter;
            this.label037.BackColor = Color.PaleGreen;
            this.label037.BorderStyle = BorderStyle.FixedSingle;
            this.label037.Font = new Font("宋体", 13f);
            this.label037.Location = new Point(0x307, 0x1c4);
            this.label037.Name = "label037";
            this.label037.Size = new Size(30, 0x18);
            this.label037.TabIndex = 0x2c;
            this.label037.Tag = "26";
            this.label037.Text = "-1";
            this.label037.TextAlign = ContentAlignment.MiddleCenter;
            this.label040.BackColor = Color.PaleGreen;
            this.label040.BorderStyle = BorderStyle.FixedSingle;
            this.label040.Font = new Font("宋体", 13f);
            this.label040.Location = new Point(0x307, 0x191);
            this.label040.Name = "label040";
            this.label040.Size = new Size(30, 0x18);
            this.label040.TabIndex = 0x2d;
            this.label040.Tag = "26";
            this.label040.Text = "-1";
            this.label040.TextAlign = ContentAlignment.MiddleCenter;
            this.label001.BackColor = Color.PaleGreen;
            this.label001.BorderStyle = BorderStyle.FixedSingle;
            this.label001.Font = new Font("宋体", 13f);
            this.label001.Location = new Point(0x307, 550);
            this.label001.Name = "label001";
            this.label001.Size = new Size(30, 0x18);
            this.label001.TabIndex = 0x2e;
            this.label001.Tag = "26";
            this.label001.Text = "-1";
            this.label001.TextAlign = ContentAlignment.MiddleCenter;
            this.label012.BackColor = Color.PaleGreen;
            this.label012.BorderStyle = BorderStyle.FixedSingle;
            this.label012.Font = new Font("宋体", 13f);
            this.label012.Location = new Point(0x2d, 0x3f);
            this.label012.Name = "label012";
            this.label012.Size = new Size(30, 0x18);
            this.label012.TabIndex = 0x2f;
            this.label012.Tag = "26";
            this.label012.Text = "-1";
            this.label012.TextAlign = ContentAlignment.MiddleCenter;
            this.label011.BackColor = Color.PaleGreen;
            this.label011.BorderStyle = BorderStyle.FixedSingle;
            this.label011.Font = new Font("宋体", 13f);
            this.label011.Location = new Point(0x1c8, 150);
            this.label011.Name = "label011";
            this.label011.Size = new Size(30, 0x18);
            this.label011.TabIndex = 0x30;
            this.label011.Tag = "26";
            this.label011.Text = "-1";
            this.label011.TextAlign = ContentAlignment.MiddleCenter;
            this.label013.BackColor = Color.PaleGreen;
            this.label013.BorderStyle = BorderStyle.FixedSingle;
            this.label013.Font = new Font("宋体", 13f);
            this.label013.Location = new Point(0x1c8, 0x16c);
            this.label013.Name = "label013";
            this.label013.Size = new Size(30, 0x18);
            this.label013.TabIndex = 0x31;
            this.label013.Tag = "26";
            this.label013.Text = "-1";
            this.label013.TextAlign = ContentAlignment.MiddleCenter;
            this.label014.BackColor = Color.PaleGreen;
            this.label014.BorderStyle = BorderStyle.FixedSingle;
            this.label014.Font = new Font("宋体", 13f);
            this.label014.Location = new Point(0x1c8, 0x207);
            this.label014.Name = "label014";
            this.label014.Size = new Size(30, 0x18);
            this.label014.TabIndex = 50;
            this.label014.Tag = "26";
            this.label014.Text = "-1";
            this.label014.TextAlign = ContentAlignment.MiddleCenter;
            this.label036.BackColor = Color.PaleGreen;
            this.label036.BorderStyle = BorderStyle.FixedSingle;
            this.label036.Font = new Font("宋体", 13f);
            this.label036.Location = new Point(0x303, 11);
            this.label036.Name = "label036";
            this.label036.Size = new Size(30, 0x18);
            this.label036.TabIndex = 0x33;
            this.label036.Tag = "26";
            this.label036.Text = "-1";
            this.label036.TextAlign = ContentAlignment.MiddleCenter;
            this.label002.BackColor = Color.PaleGreen;
            this.label002.BorderStyle = BorderStyle.FixedSingle;
            this.label002.Font = new Font("宋体", 13f);
            this.label002.Location = new Point(0x297, 0x19b);
            this.label002.Name = "label002";
            this.label002.Size = new Size(60, 0x18);
            this.label002.TabIndex = 0x34;
            this.label002.Tag = "26";
            this.label002.Text = "-1";
            this.label002.TextAlign = ContentAlignment.MiddleCenter;
            this.label015.BackColor = Color.PaleGreen;
            this.label015.BorderStyle = BorderStyle.FixedSingle;
            this.label015.Font = new Font("宋体", 13f);
            this.label015.Location = new Point(0x1ff, 0x41);
            this.label015.Name = "label015";
            this.label015.Size = new Size(30, 0x18);
            this.label015.TabIndex = 0x35;
            this.label015.Tag = "26";
            this.label015.Text = "-1";
            this.label015.TextAlign = ContentAlignment.MiddleCenter;
            this.label016.BackColor = Color.PaleGreen;
            this.label016.BorderStyle = BorderStyle.FixedSingle;
            this.label016.Font = new Font("宋体", 13f);
            this.label016.Location = new Point(0x1ff, 0xd9);
            this.label016.Name = "label016";
            this.label016.Size = new Size(30, 0x18);
            this.label016.TabIndex = 0x36;
            this.label016.Tag = "26";
            this.label016.Text = "-1";
            this.label016.TextAlign = ContentAlignment.MiddleCenter;
            this.label017.BackColor = Color.PaleGreen;
            this.label017.BorderStyle = BorderStyle.FixedSingle;
            this.label017.Font = new Font("宋体", 13f);
            this.label017.Location = new Point(0x1ff, 0x16b);
            this.label017.Name = "label017";
            this.label017.Size = new Size(30, 0x18);
            this.label017.TabIndex = 0x37;
            this.label017.Tag = "26";
            this.label017.Text = "-1";
            this.label017.TextAlign = ContentAlignment.MiddleCenter;
            this.label018.BackColor = Color.PaleGreen;
            this.label018.BorderStyle = BorderStyle.FixedSingle;
            this.label018.Font = new Font("宋体", 13f);
            this.label018.Location = new Point(0x1ff, 0x1f6);
            this.label018.Name = "label018";
            this.label018.Size = new Size(30, 0x18);
            this.label018.TabIndex = 0x38;
            this.label018.Tag = "26";
            this.label018.Text = "-1";
            this.label018.TextAlign = ContentAlignment.MiddleCenter;
            this.label003.BackColor = Color.PaleGreen;
            this.label003.BorderStyle = BorderStyle.FixedSingle;
            this.label003.Font = new Font("宋体", 13f);
            this.label003.Location = new Point(0x87, 0x21f);
            this.label003.Name = "label003";
            this.label003.Size = new Size(30, 0x18);
            this.label003.TabIndex = 0x39;
            this.label003.Tag = "26";
            this.label003.Text = "-1";
            this.label003.TextAlign = ContentAlignment.MiddleCenter;
            this.label007.BackColor = Color.PaleGreen;
            this.label007.BorderStyle = BorderStyle.FixedSingle;
            this.label007.Font = new Font("宋体", 13f);
            this.label007.Location = new Point(0xc0, 0x225);
            this.label007.Name = "label007";
            this.label007.Size = new Size(30, 0x18);
            this.label007.TabIndex = 0x3a;
            this.label007.Tag = "26";
            this.label007.Text = "-1";
            this.label007.TextAlign = ContentAlignment.MiddleCenter;
            this.label006.BackColor = Color.PaleGreen;
            this.label006.BorderStyle = BorderStyle.FixedSingle;
            this.label006.Font = new Font("宋体", 13f);
            this.label006.Location = new Point(0x87, 0x76);
            this.label006.Name = "label006";
            this.label006.Size = new Size(30, 0x18);
            this.label006.TabIndex = 0x3b;
            this.label006.Tag = "26";
            this.label006.Text = "-1";
            this.label006.TextAlign = ContentAlignment.MiddleCenter;
            this.label005.BackColor = Color.PaleGreen;
            this.label005.BorderStyle = BorderStyle.FixedSingle;
            this.label005.Font = new Font("宋体", 13f);
            this.label005.Location = new Point(0x87, 0x107);
            this.label005.Name = "label005";
            this.label005.Size = new Size(30, 0x18);
            this.label005.TabIndex = 60;
            this.label005.Tag = "26";
            this.label005.Text = "-1";
            this.label005.TextAlign = ContentAlignment.MiddleCenter;
            this.label004.BackColor = Color.PaleGreen;
            this.label004.BorderStyle = BorderStyle.FixedSingle;
            this.label004.Font = new Font("宋体", 13f);
            this.label004.Location = new Point(0x87, 0x18e);
            this.label004.Name = "label004";
            this.label004.Size = new Size(30, 0x18);
            this.label004.TabIndex = 0x3d;
            this.label004.Tag = "26";
            this.label004.Text = "-1";
            this.label004.TextAlign = ContentAlignment.MiddleCenter;
            this.label010.BackColor = Color.PaleGreen;
            this.label010.BorderStyle = BorderStyle.FixedSingle;
            this.label010.Font = new Font("宋体", 13f);
            this.label010.Location = new Point(0xc0, 0x80);
            this.label010.Name = "label010";
            this.label010.Size = new Size(30, 0x18);
            this.label010.TabIndex = 0x3e;
            this.label010.Tag = "26";
            this.label010.Text = "-1";
            this.label010.TextAlign = ContentAlignment.MiddleCenter;
            this.label009.BackColor = Color.PaleGreen;
            this.label009.BorderStyle = BorderStyle.FixedSingle;
            this.label009.Font = new Font("宋体", 13f);
            this.label009.Location = new Point(0xc0, 0x10d);
            this.label009.Name = "label009";
            this.label009.Size = new Size(30, 0x18);
            this.label009.TabIndex = 0x3f;
            this.label009.Tag = "26";
            this.label009.Text = "-1";
            this.label009.TextAlign = ContentAlignment.MiddleCenter;
            this.label008.BackColor = Color.PaleGreen;
            this.label008.BorderStyle = BorderStyle.FixedSingle;
            this.label008.Font = new Font("宋体", 13f);
            this.label008.Location = new Point(0xc0, 0x199);
            this.label008.Name = "label008";
            this.label008.Size = new Size(30, 0x18);
            this.label008.TabIndex = 0x40;
            this.label008.Tag = "26";
            this.label008.Text = "-1";
            this.label008.TextAlign = ContentAlignment.MiddleCenter;
            this.labelDD.BorderStyle = BorderStyle.Fixed3D;
            this.labelDD.Cursor = Cursors.Hand;
            this.labelDD.Location = new Point(0x27c, 0xdf);
            this.labelDD.Name = "labelDD";
            this.labelDD.Size = new Size(0x2d, 0x16);
            this.labelDD.TabIndex = 0x41;
            this.labelDD.Tag = "1";
            this.labelDD.Text = "查看";
            this.labelDD.TextAlign = ContentAlignment.MiddleCenter;
            this.labelDD.Click += new EventHandler(this.label_Click);
            this.label031.BackColor = Color.PaleGreen;
            this.label031.BorderStyle = BorderStyle.FixedSingle;
            this.label031.Font = new Font("宋体", 13f);
            this.label031.Location = new Point(0x10, 0x10a);
            this.label031.Name = "label031";
            this.label031.Size = new Size(30, 0x18);
            this.label031.TabIndex = 0x44;
            this.label031.Tag = "26";
            this.label031.Text = "-1";
            this.label031.TextAlign = ContentAlignment.MiddleCenter;
            this.label032.BackColor = Color.PaleGreen;
            this.label032.BorderStyle = BorderStyle.FixedSingle;
            this.label032.Font = new Font("宋体", 13f);
            this.label032.Location = new Point(12, 0x19c);
            this.label032.Name = "label032";
            this.label032.Size = new Size(30, 0x18);
            this.label032.TabIndex = 0x45;
            this.label032.Tag = "26";
            this.label032.Text = "-1";
            this.label032.TextAlign = ContentAlignment.MiddleCenter;
            this.label033.BackColor = Color.PaleGreen;
            this.label033.BorderStyle = BorderStyle.FixedSingle;
            this.label033.Font = new Font("宋体", 13f);
            this.label033.Location = new Point(12, 0x217);
            this.label033.Name = "label033";
            this.label033.Size = new Size(30, 0x18);
            this.label033.TabIndex = 70;
            this.label033.Tag = "26";
            this.label033.Text = "-1";
            this.label033.TextAlign = ContentAlignment.MiddleCenter;
            this.label041.BackColor = Color.PaleGreen;
            this.label041.BorderStyle = BorderStyle.FixedSingle;
            this.label041.Font = new Font("宋体", 13f);
            this.label041.Location = new Point(0x2d6, 0x23);
            this.label041.Name = "label041";
            this.label041.Size = new Size(0x13, 0x16);
            this.label041.TabIndex = 0x47;
            this.label041.Tag = "26";
            this.label041.Text = "-1";
            this.label041.TextAlign = ContentAlignment.MiddleCenter;
            this.label042.BackColor = Color.PaleGreen;
            this.label042.BorderStyle = BorderStyle.FixedSingle;
            this.label042.Font = new Font("宋体", 13f);
            this.label042.Location = new Point(0x2d6, 0x3a);
            this.label042.Name = "label042";
            this.label042.Size = new Size(0x13, 0x16);
            this.label042.TabIndex = 0x48;
            this.label042.Tag = "26";
            this.label042.Text = "-1";
            this.label042.TextAlign = ContentAlignment.MiddleCenter;
            this.label043.BackColor = Color.PaleGreen;
            this.label043.BorderStyle = BorderStyle.FixedSingle;
            this.label043.Font = new Font("宋体", 13f);
            this.label043.Location = new Point(0x2d6, 0x52);
            this.label043.Name = "label043";
            this.label043.Size = new Size(0x13, 0x16);
            this.label043.TabIndex = 0x49;
            this.label043.Tag = "26";
            this.label043.Text = "-1";
            this.label043.TextAlign = ContentAlignment.MiddleCenter;
            this.label044.BackColor = Color.PaleGreen;
            this.label044.BorderStyle = BorderStyle.FixedSingle;
            this.label044.Font = new Font("宋体", 13f);
            this.label044.Location = new Point(0x2d6, 0x6a);
            this.label044.Name = "label044";
            this.label044.Size = new Size(0x13, 0x16);
            this.label044.TabIndex = 0x4a;
            this.label044.Tag = "26";
            this.label044.Text = "-1";
            this.label044.TextAlign = ContentAlignment.MiddleCenter;
            this.label045.BackColor = Color.PaleGreen;
            this.label045.BorderStyle = BorderStyle.FixedSingle;
            this.label045.Font = new Font("宋体", 13f);
            this.label045.Location = new Point(0x2e0, 0x8d);
            this.label045.Name = "label045";
            this.label045.Size = new Size(0x13, 0x16);
            this.label045.TabIndex = 0x4b;
            this.label045.Tag = "26";
            this.label045.Text = "-1";
            this.label045.TextAlign = ContentAlignment.MiddleCenter;
            this.label046.BackColor = Color.PaleGreen;
            this.label046.BorderStyle = BorderStyle.FixedSingle;
            this.label046.Font = new Font("宋体", 13f);
            this.label046.Location = new Point(0x2e0, 0xad);
            this.label046.Name = "label046";
            this.label046.Size = new Size(0x13, 0x16);
            this.label046.TabIndex = 0x4c;
            this.label046.Tag = "26";
            this.label046.Text = "-1";
            this.label046.TextAlign = ContentAlignment.MiddleCenter;
            this.label020.Location = new Point(300, 0x5b);
            this.label020.Name = "label020";
            this.label020.Size = new Size(0x7a, 0x2d);
            this.label020.TabIndex = 0x4d;
            this.label020.Tag = "3";
            this.label020.Text = "查看";
            this.label024.Location = new Point(300, 0x156);
            this.label024.Name = "label024";
            this.label024.Size = new Size(0x7a, 0x2d);
            this.label024.TabIndex = 0x4e;
            this.label024.Tag = "7";
            this.label024.Text = "查看";
            this.label026.Location = new Point(300, 0x1f0);
            this.label026.Name = "label026";
            this.label026.Size = new Size(0x7a, 0x2d);
            this.label026.TabIndex = 0x4f;
            this.label026.Tag = "9";
            this.label026.Text = "查看";
            this.label019.Location = new Point(300, 0x24);
            this.label019.Name = "label019";
            this.label019.Size = new Size(0x7a, 0x2d);
            this.label019.TabIndex = 80;
            this.label019.Tag = "21";
            this.label019.Text = "查看";
            this.label021.Location = new Point(300, 0x99);
            this.label021.Name = "label021";
            this.label021.Size = new Size(0x7a, 0x2d);
            this.label021.TabIndex = 0x51;
            this.label021.Tag = "4";
            this.label021.Text = "查看";
            this.label022.Location = new Point(300, 0xd0);
            this.label022.Name = "label022";
            this.label022.Size = new Size(0x7a, 0x2d);
            this.label022.TabIndex = 0x52;
            this.label022.Tag = "5";
            this.label022.Text = "查看";
            this.label023.Location = new Point(300, 0x11f);
            this.label023.Name = "label023";
            this.label023.Size = new Size(0x7a, 0x2d);
            this.label023.TabIndex = 0x53;
            this.label023.Tag = "6";
            this.label023.Text = "查看";
            this.label025.Location = new Point(300, 0x18e);
            this.label025.Name = "label025";
            this.label025.Size = new Size(0x7a, 0x2d);
            this.label025.TabIndex = 0x54;
            this.label025.Tag = "8";
            this.label025.Text = "查看";
            this.label027.BackColor = Color.PaleGreen;
            this.label027.BorderStyle = BorderStyle.FixedSingle;
            this.label027.Font = new Font("宋体", 13f);
            this.label027.Location = new Point(0x291, 0x1db);
            this.label027.Name = "label027";
            this.label027.Size = new Size(60, 0x15);
            this.label027.TabIndex = 0x58;
            this.label027.Tag = "26";
            this.label027.Text = "-1";
            this.label027.TextAlign = ContentAlignment.MiddleCenter;
            this.label028.BackColor = Color.PaleGreen;
            this.label028.BorderStyle = BorderStyle.FixedSingle;
            this.label028.Font = new Font("宋体", 13f);
            this.label028.Location = new Point(0x291, 0x1f3);
            this.label028.Name = "label028";
            this.label028.Size = new Size(60, 0x15);
            this.label028.TabIndex = 0x59;
            this.label028.Tag = "26";
            this.label028.Text = "-1";
            this.label028.TextAlign = ContentAlignment.MiddleCenter;
            this.label029.BackColor = Color.PaleGreen;
            this.label029.BorderStyle = BorderStyle.FixedSingle;
            this.label029.Font = new Font("宋体", 13f);
            this.label029.Location = new Point(0x292, 0x20c);
            this.label029.Name = "label029";
            this.label029.Size = new Size(60, 0x15);
            this.label029.TabIndex = 90;
            this.label029.Tag = "26";
            this.label029.Text = "-1";
            this.label029.TextAlign = ContentAlignment.MiddleCenter;
            this.label030.BackColor = Color.PaleGreen;
            this.label030.BorderStyle = BorderStyle.FixedSingle;
            this.label030.Font = new Font("宋体", 13f);
            this.label030.Location = new Point(0x292, 0x222);
            this.label030.Name = "label030";
            this.label030.Size = new Size(60, 0x15);
            this.label030.TabIndex = 0x5b;
            this.label030.Tag = "26";
            this.label030.Text = "-1";
            this.label030.TextAlign = ContentAlignment.MiddleCenter;
            this.label29.BackColor = Color.PaleGreen;
            this.label29.BorderStyle = BorderStyle.FixedSingle;
            this.label29.Font = new Font("宋体", 13f);
            this.label29.Location = new Point(0x307, 0xce);
            this.label29.Name = "label29";
            this.label29.Size = new Size(30, 0x18);
            this.label29.TabIndex = 0x29;
            this.label29.Tag = "26";
            this.label29.TextAlign = ContentAlignment.MiddleCenter;
            this.label1.BackColor = Color.PaleGreen;
            this.label1.BorderStyle = BorderStyle.FixedSingle;
            this.label1.Font = new Font("宋体", 13f);
            this.label1.Location = new Point(0x307, 0x131);
            this.label1.Name = "label1";
            this.label1.Size = new Size(30, 0x18);
            this.label1.TabIndex = 0x5c;
            this.label1.Tag = "26";
            this.label1.TextAlign = ContentAlignment.MiddleCenter;
            this.label047.BackColor = Color.PaleGreen;
            this.label047.BorderStyle = BorderStyle.FixedSingle;
            this.label047.Font = new Font("宋体", 13f);
            this.label047.Location = new Point(0x2d, 0x7a);
            this.label047.Name = "label047";
            this.label047.Size = new Size(30, 0x18);
            this.label047.TabIndex = 0x5e;
            this.label047.Tag = "26";
            this.label047.TextAlign = ContentAlignment.MiddleCenter;
            this.pictureBox2.Image = (Image) manager.GetObject("pictureBox2.Image");
            this.pictureBox2.Location = new Point(0x2ac, 0xf3);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new Size(0x39, 0x81);
            this.pictureBox2.SizeMode = PictureBoxSizeMode.StretchImage;
            this.pictureBox2.TabIndex = 0x66;
            this.pictureBox2.TabStop = false;
            this.label6.BorderStyle = BorderStyle.Fixed3D;
            this.label6.Cursor = Cursors.Hand;
            this.label6.Location = new Point(0x2af, 0xdf);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x2d, 0x16);
            this.label6.TabIndex = 0x67;
            this.label6.Tag = "3";
            this.label6.Text = "查看";
            this.label6.TextAlign = ContentAlignment.MiddleCenter;
            this.label6.Click += new EventHandler(this.label_Click);
            this.pictureBox3.Image = Resources.zj1;
            this.pictureBox3.Location = new Point(4, 7);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new Size(0x59, 0x9c);
            this.pictureBox3.SizeMode = PictureBoxSizeMode.StretchImage;
            this.pictureBox3.TabIndex = 0x68;
            this.pictureBox3.TabStop = false;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(0x32e, 0x27b);
            base.Controls.Add(this.label047);
            base.Controls.Add(this.label012);
            base.Controls.Add(this.pictureBox3);
            base.Controls.Add(this.label6);
            base.Controls.Add(this.pictureBox2);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.label030);
            base.Controls.Add(this.label029);
            base.Controls.Add(this.label028);
            base.Controls.Add(this.label027);
            base.Controls.Add(this.label025);
            base.Controls.Add(this.label023);
            base.Controls.Add(this.label022);
            base.Controls.Add(this.label021);
            base.Controls.Add(this.label019);
            base.Controls.Add(this.label026);
            base.Controls.Add(this.label024);
            base.Controls.Add(this.label020);
            base.Controls.Add(this.label046);
            base.Controls.Add(this.label045);
            base.Controls.Add(this.label044);
            base.Controls.Add(this.label043);
            base.Controls.Add(this.label042);
            base.Controls.Add(this.label041);
            base.Controls.Add(this.label033);
            base.Controls.Add(this.label032);
            base.Controls.Add(this.label031);
            base.Controls.Add(this.labelDD);
            base.Controls.Add(this.label008);
            base.Controls.Add(this.label009);
            base.Controls.Add(this.label010);
            base.Controls.Add(this.label004);
            base.Controls.Add(this.label005);
            base.Controls.Add(this.label006);
            base.Controls.Add(this.label007);
            base.Controls.Add(this.label003);
            base.Controls.Add(this.label018);
            base.Controls.Add(this.label017);
            base.Controls.Add(this.label016);
            base.Controls.Add(this.label015);
            base.Controls.Add(this.label002);
            base.Controls.Add(this.label036);
            base.Controls.Add(this.label014);
            base.Controls.Add(this.label013);
            base.Controls.Add(this.label011);
            base.Controls.Add(this.label001);
            base.Controls.Add(this.label040);
            base.Controls.Add(this.label037);
            base.Controls.Add(this.label048);
            base.Controls.Add(this.label038);
            base.Controls.Add(this.label29);
            base.Controls.Add(this.label039);
            base.Controls.Add(this.label27);
            base.Controls.Add(this.label035);
            base.Controls.Add(this.label034);
            base.Controls.Add(this.label21);
            base.Controls.Add(this.button1);
            base.Controls.Add(this.pictureBox1);
            base.FormBorderStyle = FormBorderStyle.FixedDialog;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmShowTableInfor";
            base.ShowInTaskbar = false;
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "查看台面信息";
            base.Load += new EventHandler(this.frmShowTableInfor_Load);
            ((ISupportInitialize) this.pictureBox1).EndInit();
            ((ISupportInitialize) this.pictureBox2).EndInit();
            ((ISupportInitialize) this.pictureBox3).EndInit();
            base.ResumeLayout(false);
        }

        private void label_Click(object sender, EventArgs e)
        {
            switch (Convert.ToInt16(((Label) sender).Tag))
            {
                case 1:
                    new frmShowShortTermLoans().ShowDialog();
                    return;

                case 2:
                    new frmShowLongTermLoans().ShowDialog();
                    return;

                case 3:
                    new frmShowGLD().ShowDialog();
                    return;
            }
        }
    }
}

