namespace ERPChess
{
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;
    using ZedGraph;

    public class frmXNNGHHY : Form
    {
        private IContainer components;
        private Button buttonOK;
        private Button buttonCancel;
        private TabControl tabControl1;
        private TabPage tabPage1;
        private TabPage tabPage2;
        private TabControl tabControl2;
        private TabPage tabPage3;
        private SplitContainer splitContainer1;
        private TabPage tabPage4;
        private TabPage tabPage5;
        private TabPage tabPage6;
        private TabPage tabPage7;
        private SplitContainer splitContainer2;
        private SplitContainer splitContainer3;
        private SplitContainer splitContainer4;
        private SplitContainer splitContainer5;
        private RichTextBox richTextBox1;
        private RichTextBox richTextBox2;
        private RichTextBox richTextBox3;
        private RichTextBox richTextBox4;
        private RichTextBox richTextBox5;
        private RichTextBox richTextBox6;
        private ZedGraphControl zedGraphBD;
        private ZedGraphControl zedGraphQY;
        private ZedGraphControl zedGraphGN;
        private ZedGraphControl zedGraphYZ;
        private ZedGraphControl zedGraphGJ;

        public frmXNNGHHY()
        {
            this.InitializeComponent();
        }

        private void buttonCancel_Click(object sender, EventArgs e)
        {
            base.Close();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void frmXNNGHHY_Load(object sender, EventArgs e)
        {
            GraphPane graphPane = this.zedGraphBD.GraphPane;
            GraphPane pane = this.zedGraphQY.GraphPane;
            GraphPane pane3 = this.zedGraphGN.GraphPane;
            GraphPane pane4 = this.zedGraphYZ.GraphPane;
            GraphPane pane5 = this.zedGraphGJ.GraphPane;
            graphPane.Title.Text = "本地市场预测";
            pane.Title.Text = "区域市场预测";
            pane3.Title.Text = "国内市场预测";
            pane4.Title.Text = "亚洲市场预测";
            pane5.Title.Text = "国际市场预测";
            graphPane.XAxis.Title.Text = "价格(M)";
            pane.XAxis.Title.Text = "价格(M)";
            pane3.XAxis.Title.Text = "价格(M)";
            pane4.XAxis.Title.Text = "价格(M)";
            pane5.XAxis.Title.Text = "价格(M)";
            graphPane.YAxis.Title.Text = "市场预期";
            pane.YAxis.Title.Text = "市场预期";
            pane3.YAxis.Title.Text = "市场预期";
            pane4.YAxis.Title.Text = "市场预期";
            pane5.YAxis.Title.Text = "市场预期";
            string[] strArray = new string[] { "P1: 5.3—3.3—3.0", "P2: 5.9—9.5—5.0", "P3 :7.5—10.0—11", "P4 :8—10—12.5" };
            string[] strArray2 = new string[] { "P1: 5.0—4.5—5.0", "P2: 6.0—8.5—5.5", "P3: 8.0—9.0—10", "P4: 8.5—10.5—11.5" };
            string[] strArray3 = new string[] { "P1: 4.5—5.5—3.5", "P2: 7.5—9.0—4.5", "P3: 8.0—10—11.5", "P4: 8.0—10—12" };
            string[] strArray4 = new string[] { "P1: 4.5—5.0—3.5", "P2: 7.0—5.0", "P3: 7.5—11—12.5", "P4: 9.5—10.5—13" };
            string[] strArray5 = new string[] { "P1: 5.0—6.5—4.5", "P2: 7.0—8.0—9.0", "P3: 8.0—10", "P4: 7.5—8.5—11" };
            PointPairList points = new PointPairList();
            PointPairList list2 = new PointPairList();
            PointPairList list3 = new PointPairList();
            PointPairList list4 = new PointPairList();
            PointPairList list5 = new PointPairList();
            PointPairList list6 = new PointPairList();
            PointPairList list7 = new PointPairList();
            PointPairList list8 = new PointPairList();
            PointPairList list9 = new PointPairList();
            PointPairList list10 = new PointPairList();
            PointPairList list11 = new PointPairList();
            PointPairList list12 = new PointPairList();
            PointPairList list13 = new PointPairList();
            PointPairList list14 = new PointPairList();
            PointPairList list15 = new PointPairList();
            PointPairList list16 = new PointPairList();
            PointPairList list17 = new PointPairList();
            PointPairList list18 = new PointPairList();
            PointPairList list19 = new PointPairList();
            PointPairList list20 = new PointPairList();
            PointPairList list21 = new PointPairList();
            PointPairList list22 = new PointPairList();
            PointPairList list23 = new PointPairList();
            PointPairList list24 = new PointPairList();
            PointPairList list25 = new PointPairList();
            PointPairList list26 = new PointPairList();
            PointPairList list27 = new PointPairList();
            PointPairList list28 = new PointPairList();
            PointPairList list29 = new PointPairList();
            PointPairList list30 = new PointPairList();
            points.Add((double) 1.0, (double) 20.0);
            list2.Add((double) 1.0, (double) 21.0);
            list3.Add((double) 1.0, (double) 18.0);
            list4.Add((double) 1.0, (double) 16.0);
            list5.Add((double) 1.0, (double) 12.0);
            list6.Add((double) 1.0, (double) 8.0);
            points.Add((double) 2.0, (double) 0.0);
            list2.Add((double) 2.0, (double) 0.0);
            list3.Add((double) 2.0, (double) 13.0);
            list4.Add((double) 2.0, (double) 14.0);
            list5.Add((double) 2.0, (double) 14.0);
            list6.Add((double) 2.0, (double) 12.0);
            points.Add((double) 3.0, (double) 0.0);
            list2.Add((double) 3.0, (double) 0.0);
            list3.Add((double) 3.0, (double) 5.0);
            list4.Add((double) 3.0, (double) 6.0);
            list5.Add((double) 3.0, (double) 10.0);
            list6.Add((double) 3.0, (double) 16.0);
            points.Add((double) 4.0, (double) 0.0);
            list2.Add((double) 4.0, (double) 0.0);
            list3.Add((double) 4.0, (double) 0.0);
            list4.Add((double) 4.0, (double) 5.0);
            list5.Add((double) 4.0, (double) 7.0);
            list6.Add((double) 4.0, (double) 9.0);
            list7.Add((double) 1.0, (double) 15.0);
            list8.Add((double) 1.0, (double) 19.0);
            list9.Add((double) 1.0, (double) 4.0);
            list10.Add((double) 1.0, (double) 4.0);
            list11.Add((double) 1.0, (double) 3.0);
            list12.Add((double) 1.0, (double) 3.0);
            list7.Add((double) 2.0, (double) 0.0);
            list8.Add((double) 2.0, (double) 0.0);
            list9.Add((double) 2.0, (double) 10.0);
            list10.Add((double) 2.0, (double) 9.0);
            list11.Add((double) 2.0, (double) 7.0);
            list12.Add((double) 2.0, (double) 5.0);
            list7.Add((double) 3.0, (double) 0.0);
            list8.Add((double) 3.0, (double) 0.0);
            list9.Add((double) 3.0, (double) 5.0);
            list10.Add((double) 3.0, (double) 6.0);
            list11.Add((double) 3.0, (double) 7.0);
            list12.Add((double) 3.0, (double) 7.0);
            list7.Add((double) 4.0, (double) 0.0);
            list8.Add((double) 4.0, (double) 0.0);
            list9.Add((double) 4.0, (double) 0.0);
            list10.Add((double) 4.0, (double) 4.0);
            list11.Add((double) 4.0, (double) 4.0);
            list12.Add((double) 4.0, (double) 7.0);
            list13.Add((double) 1.0, (double) 12.0);
            list14.Add((double) 1.0, (double) 13.0);
            list15.Add((double) 1.0, (double) 13.0);
            list16.Add((double) 1.0, (double) 14.0);
            list17.Add((double) 1.0, (double) 9.0);
            list18.Add((double) 1.0, (double) 6.0);
            list13.Add((double) 2.0, (double) 0.0);
            list14.Add((double) 2.0, (double) 0.0);
            list15.Add((double) 2.0, (double) 11.0);
            list16.Add((double) 2.0, (double) 12.0);
            list17.Add((double) 2.0, (double) 11.0);
            list18.Add((double) 2.0, (double) 9.0);
            list13.Add((double) 3.0, (double) 0.0);
            list14.Add((double) 3.0, (double) 0.0);
            list15.Add((double) 3.0, (double) 5.0);
            list16.Add((double) 3.0, (double) 6.0);
            list17.Add((double) 3.0, (double) 7.0);
            list18.Add((double) 3.0, (double) 10.0);
            list13.Add((double) 4.0, (double) 0.0);
            list14.Add((double) 4.0, (double) 0.0);
            list15.Add((double) 4.0, (double) 0.0);
            list16.Add((double) 4.0, (double) 0.0);
            list17.Add((double) 4.0, (double) 3.0);
            list18.Add((double) 4.0, (double) 4.0);
            list19.Add((double) 1.0, (double) 12.0);
            list20.Add((double) 1.0, (double) 13.0);
            list21.Add((double) 1.0, (double) 14.0);
            list22.Add((double) 1.0, (double) 15.0);
            list23.Add((double) 1.0, (double) 9.0);
            list24.Add((double) 1.0, (double) 6.0);
            list19.Add((double) 2.0, (double) 0.0);
            list20.Add((double) 2.0, (double) 0.0);
            list21.Add((double) 2.0, (double) 12.0);
            list22.Add((double) 2.0, (double) 13.0);
            list23.Add((double) 2.0, (double) 11.0);
            list24.Add((double) 2.0, (double) 9.0);
            list19.Add((double) 3.0, (double) 0.0);
            list20.Add((double) 3.0, (double) 0.0);
            list21.Add((double) 3.0, (double) 5.0);
            list22.Add((double) 3.0, (double) 6.0);
            list23.Add((double) 3.0, (double) 9.0);
            list24.Add((double) 3.0, (double) 10.0);
            list19.Add((double) 4.0, (double) 0.0);
            list20.Add((double) 4.0, (double) 0.0);
            list21.Add((double) 4.0, (double) 0.0);
            list22.Add((double) 4.0, (double) 0.0);
            list23.Add((double) 4.0, (double) 3.0);
            list24.Add((double) 4.0, (double) 4.0);
            list25.Add((double) 1.0, (double) 14.0);
            list26.Add((double) 1.0, (double) 16.0);
            list27.Add((double) 1.0, (double) 17.0);
            list28.Add((double) 1.0, (double) 18.0);
            list29.Add((double) 1.0, (double) 18.0);
            list30.Add((double) 1.0, (double) 15.0);
            list25.Add((double) 2.0, (double) 0.0);
            list26.Add((double) 2.0, (double) 0.0);
            list27.Add((double) 2.0, (double) 5.0);
            list28.Add((double) 2.0, (double) 6.0);
            list29.Add((double) 2.0, (double) 4.0);
            list30.Add((double) 2.0, (double) 8.0);
            list25.Add((double) 3.0, (double) 0.0);
            list26.Add((double) 3.0, (double) 0.0);
            list27.Add((double) 3.0, (double) 1.0);
            list28.Add((double) 3.0, (double) 2.0);
            list29.Add((double) 3.0, (double) 0.0);
            list30.Add((double) 3.0, (double) 4.0);
            list25.Add((double) 4.0, (double) 0.0);
            list26.Add((double) 4.0, (double) 0.0);
            list27.Add((double) 4.0, (double) 0.0);
            list28.Add((double) 4.0, (double) 3.0);
            list29.Add((double) 4.0, (double) 4.0);
            list30.Add((double) 4.0, (double) 5.0);
            graphPane.AddBar("第1年", points, Color.Blue);
            graphPane.AddBar("第2年", list2, Color.Red);
            graphPane.AddBar("第3年", list3, Color.Yellow);
            graphPane.AddBar("第4年", list4, Color.Green);
            graphPane.AddBar("第5年", list5, Color.Brown);
            graphPane.AddBar("第6年", list6, Color.Beige);
            pane.AddBar("第1年", list7, Color.Blue);
            pane.AddBar("第2年", list8, Color.Red);
            pane.AddBar("第3年", list9, Color.Yellow);
            pane.AddBar("第4年", list10, Color.Green);
            pane.AddBar("第5年", list11, Color.Brown);
            pane.AddBar("第6年", list12, Color.Beige);
            pane3.AddBar("第1年", list13, Color.Blue);
            pane3.AddBar("第2年", list14, Color.Red);
            pane3.AddBar("第3年", list15, Color.Yellow);
            pane3.AddBar("第4年", list16, Color.Green);
            pane3.AddBar("第5年", list17, Color.Brown);
            pane3.AddBar("第6年", list18, Color.Beige);
            pane4.AddBar("第1年", list19, Color.Blue);
            pane4.AddBar("第2年", list20, Color.Red);
            pane4.AddBar("第3年", list21, Color.Yellow);
            pane4.AddBar("第4年", list22, Color.Green);
            pane4.AddBar("第5年", list23, Color.Brown);
            pane4.AddBar("第6年", list24, Color.Beige);
            pane5.AddBar("第1年", list25, Color.Blue);
            pane5.AddBar("第2年", list26, Color.Red);
            pane5.AddBar("第3年", list27, Color.Yellow);
            pane5.AddBar("第4年", list28, Color.Green);
            pane5.AddBar("第5年", list29, Color.Brown);
            pane5.AddBar("第6年", list30, Color.Beige);
            graphPane.XAxis.MajorTic.IsBetweenLabels = true;
            pane.XAxis.MajorTic.IsBetweenLabels = true;
            pane3.XAxis.MajorTic.IsBetweenLabels = true;
            pane4.XAxis.MajorTic.IsBetweenLabels = true;
            pane5.XAxis.MajorTic.IsBetweenLabels = true;
            graphPane.XAxis.Scale.TextLabels = strArray;
            pane.XAxis.Scale.TextLabels = strArray2;
            pane3.XAxis.Scale.TextLabels = strArray3;
            pane4.XAxis.Scale.TextLabels = strArray4;
            pane5.XAxis.Scale.TextLabels = strArray5;
            graphPane.XAxis.Type = AxisType.Text;
            pane.XAxis.Type = AxisType.Text;
            pane3.XAxis.Type = AxisType.Text;
            pane4.XAxis.Type = AxisType.Text;
            pane5.XAxis.Type = AxisType.Text;
            graphPane.Chart.Fill = new Fill(Color.White, Color.FromArgb(0xff, 0xff, 0xa6), 45f);
            pane.Chart.Fill = new Fill(Color.White, Color.FromArgb(0xff, 0xff, 0xa6), 45f);
            pane3.Chart.Fill = new Fill(Color.White, Color.FromArgb(0xff, 0xff, 0xa6), 45f);
            pane4.Chart.Fill = new Fill(Color.White, Color.FromArgb(0xff, 0xff, 0xa6), 45f);
            pane5.Chart.Fill = new Fill(Color.White, Color.FromArgb(0xff, 0xff, 0xa6), 45f);
            BarItem.CreateBarLabels(graphPane, false, "f0");
            BarItem.CreateBarLabels(pane, false, "f0");
            BarItem.CreateBarLabels(pane3, false, "f0");
            BarItem.CreateBarLabels(pane4, false, "f0");
            BarItem.CreateBarLabels(pane5, false, "f0");
            graphPane.AxisChange();
            pane.AxisChange();
            pane3.AxisChange();
            pane4.AxisChange();
            pane5.AxisChange();
        }

        private void InitializeComponent()
        {
            this.components = new Container();
            ComponentResourceManager manager = new ComponentResourceManager(typeof(frmXNNGHHY));
            this.buttonOK = new Button();
            this.buttonCancel = new Button();
            this.tabControl1 = new TabControl();
            this.tabPage1 = new TabPage();
            this.richTextBox1 = new RichTextBox();
            this.tabPage2 = new TabPage();
            this.tabControl2 = new TabControl();
            this.tabPage3 = new TabPage();
            this.splitContainer1 = new SplitContainer();
            this.richTextBox2 = new RichTextBox();
            this.zedGraphBD = new ZedGraphControl();
            this.tabPage4 = new TabPage();
            this.splitContainer2 = new SplitContainer();
            this.richTextBox3 = new RichTextBox();
            this.zedGraphQY = new ZedGraphControl();
            this.tabPage5 = new TabPage();
            this.splitContainer3 = new SplitContainer();
            this.richTextBox4 = new RichTextBox();
            this.zedGraphGN = new ZedGraphControl();
            this.tabPage6 = new TabPage();
            this.splitContainer4 = new SplitContainer();
            this.richTextBox5 = new RichTextBox();
            this.zedGraphYZ = new ZedGraphControl();
            this.tabPage7 = new TabPage();
            this.splitContainer5 = new SplitContainer();
            this.richTextBox6 = new RichTextBox();
            this.zedGraphGJ = new ZedGraphControl();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.tabControl2.SuspendLayout();
            this.tabPage3.SuspendLayout();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            this.tabPage4.SuspendLayout();
            this.splitContainer2.Panel1.SuspendLayout();
            this.splitContainer2.Panel2.SuspendLayout();
            this.splitContainer2.SuspendLayout();
            this.tabPage5.SuspendLayout();
            this.splitContainer3.Panel1.SuspendLayout();
            this.splitContainer3.Panel2.SuspendLayout();
            this.splitContainer3.SuspendLayout();
            this.tabPage6.SuspendLayout();
            this.splitContainer4.Panel1.SuspendLayout();
            this.splitContainer4.Panel2.SuspendLayout();
            this.splitContainer4.SuspendLayout();
            this.tabPage7.SuspendLayout();
            this.splitContainer5.Panel1.SuspendLayout();
            this.splitContainer5.Panel2.SuspendLayout();
            this.splitContainer5.SuspendLayout();
            base.SuspendLayout();
            this.buttonOK.DialogResult = DialogResult.OK;
            this.buttonOK.Location = new Point(0x221, 0x165);
            this.buttonOK.Name = "buttonOK";
            this.buttonOK.Size = new Size(0x4b, 0x17);
            this.buttonOK.TabIndex = 0;
            this.buttonOK.Text = "完成";
            this.buttonOK.UseVisualStyleBackColor = true;
            this.buttonCancel.DialogResult = DialogResult.Cancel;
            this.buttonCancel.Location = new Point(630, 0x165);
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.Size = new Size(0x4b, 0x17);
            this.buttonCancel.TabIndex = 1;
            this.buttonCancel.Text = "取消";
            this.buttonCancel.UseVisualStyleBackColor = true;
            this.buttonCancel.Click += new EventHandler(this.buttonCancel_Click);
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Dock = DockStyle.Top;
            this.tabControl1.Location = new Point(0, 0);
            this.tabControl1.Multiline = true;
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new Size(0x2cb, 0x15f);
            this.tabControl1.TabIndex = 2;
            this.tabPage1.Controls.Add(this.richTextBox1);
            this.tabPage1.Location = new Point(4, 0x15);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new Padding(3);
            this.tabPage1.Size = new Size(0x2c3, 0x146);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "商业新闻";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.richTextBox1.BackColor = SystemColors.Window;
            this.richTextBox1.BorderStyle = BorderStyle.FixedSingle;
            this.richTextBox1.Dock = DockStyle.Fill;
            this.richTextBox1.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.richTextBox1.Location = new Point(3, 3);
            this.richTextBox1.Name = "richTextBox1";
            this.richTextBox1.ReadOnly = true;
            this.richTextBox1.Size = new Size(0x2bd, 320);
            this.richTextBox1.TabIndex = 0;
            this.richTextBox1.Text = manager.GetString("richTextBox1.Text");
            this.tabPage2.Controls.Add(this.tabControl2);
            this.tabPage2.Location = new Point(4, 0x15);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new Padding(3);
            this.tabPage2.Size = new Size(0x2c3, 0x146);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "近期预测";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.tabControl2.Alignment = TabAlignment.Bottom;
            this.tabControl2.Controls.Add(this.tabPage3);
            this.tabControl2.Controls.Add(this.tabPage4);
            this.tabControl2.Controls.Add(this.tabPage5);
            this.tabControl2.Controls.Add(this.tabPage6);
            this.tabControl2.Controls.Add(this.tabPage7);
            this.tabControl2.Dock = DockStyle.Fill;
            this.tabControl2.Location = new Point(3, 3);
            this.tabControl2.Name = "tabControl2";
            this.tabControl2.SelectedIndex = 0;
            this.tabControl2.Size = new Size(0x2bd, 320);
            this.tabControl2.TabIndex = 2;
            this.tabPage3.Controls.Add(this.splitContainer1);
            this.tabPage3.Location = new Point(4, 4);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new Padding(3);
            this.tabPage3.Size = new Size(0x2b5, 0x127);
            this.tabPage3.TabIndex = 0;
            this.tabPage3.Text = "本地市场";
            this.tabPage3.UseVisualStyleBackColor = true;
            this.splitContainer1.Dock = DockStyle.Fill;
            this.splitContainer1.Location = new Point(3, 3);
            this.splitContainer1.Name = "splitContainer1";
            this.splitContainer1.Panel1.Controls.Add(this.richTextBox2);
            this.splitContainer1.Panel2.Controls.Add(this.zedGraphBD);
            this.splitContainer1.Size = new Size(0x2af, 0x121);
            this.splitContainer1.SplitterDistance = 0x9d;
            this.splitContainer1.TabIndex = 0;
            this.richTextBox2.BackColor = SystemColors.Window;
            this.richTextBox2.BorderStyle = BorderStyle.FixedSingle;
            this.richTextBox2.Dock = DockStyle.Fill;
            this.richTextBox2.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.richTextBox2.Location = new Point(0, 0);
            this.richTextBox2.Name = "richTextBox2";
            this.richTextBox2.ReadOnly = true;
            this.richTextBox2.Size = new Size(0x9d, 0x121);
            this.richTextBox2.TabIndex = 0;
            this.richTextBox2.Text = "本地：\n\n本地市场将会持续发展，但是其中P1产品的需求有可能减少。\n\nP2产品的前景广阔，不过该项目至少需要1-2年开发测试才能成功。";
            this.zedGraphBD.Dock = DockStyle.Fill;
            this.zedGraphBD.IsEnableHZoom = false;
            this.zedGraphBD.IsEnableVZoom = false;
            this.zedGraphBD.Location = new Point(0, 0);
            this.zedGraphBD.Name = "zedGraphBD";
            this.zedGraphBD.ScrollGrace = 0.0;
            this.zedGraphBD.ScrollMaxX = 0.0;
            this.zedGraphBD.ScrollMaxY = 0.0;
            this.zedGraphBD.ScrollMaxY2 = 0.0;
            this.zedGraphBD.ScrollMinX = 0.0;
            this.zedGraphBD.ScrollMinY = 0.0;
            this.zedGraphBD.ScrollMinY2 = 0.0;
            this.zedGraphBD.Size = new Size(0x20e, 0x121);
            this.zedGraphBD.TabIndex = 0;
            this.tabPage4.Controls.Add(this.splitContainer2);
            this.tabPage4.Location = new Point(4, 4);
            this.tabPage4.Name = "tabPage4";
            this.tabPage4.Padding = new Padding(3);
            this.tabPage4.Size = new Size(0x2b5, 0x127);
            this.tabPage4.TabIndex = 1;
            this.tabPage4.Text = "区域市场";
            this.tabPage4.UseVisualStyleBackColor = true;
            this.splitContainer2.Dock = DockStyle.Fill;
            this.splitContainer2.Location = new Point(3, 3);
            this.splitContainer2.Name = "splitContainer2";
            this.splitContainer2.Panel1.Controls.Add(this.richTextBox3);
            this.splitContainer2.Panel2.Controls.Add(this.zedGraphQY);
            this.splitContainer2.Size = new Size(0x2af, 0x121);
            this.splitContainer2.SplitterDistance = 0x9d;
            this.splitContainer2.TabIndex = 1;
            this.richTextBox3.BackColor = SystemColors.Window;
            this.richTextBox3.BorderStyle = BorderStyle.FixedSingle;
            this.richTextBox3.Dock = DockStyle.Fill;
            this.richTextBox3.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.richTextBox3.Location = new Point(0, 0);
            this.richTextBox3.Name = "richTextBox3";
            this.richTextBox3.ReadOnly = true;
            this.richTextBox3.Size = new Size(0x9d, 0x121);
            this.richTextBox3.TabIndex = 1;
            this.richTextBox3.Text = "区域：\n\n区域市场不如本地市场那样广阔——仅需少量的低技术产品如P1产品及P2产品。\n\nP3产品市场则有很大的不确定性。但是普遍认为P4产品将会有很大需求。";
            this.zedGraphQY.Dock = DockStyle.Fill;
            this.zedGraphQY.IsEnableHZoom = false;
            this.zedGraphQY.IsEnableVZoom = false;
            this.zedGraphQY.Location = new Point(0, 0);
            this.zedGraphQY.Name = "zedGraphQY";
            this.zedGraphQY.ScrollGrace = 0.0;
            this.zedGraphQY.ScrollMaxX = 0.0;
            this.zedGraphQY.ScrollMaxY = 0.0;
            this.zedGraphQY.ScrollMaxY2 = 0.0;
            this.zedGraphQY.ScrollMinX = 0.0;
            this.zedGraphQY.ScrollMinY = 0.0;
            this.zedGraphQY.ScrollMinY2 = 0.0;
            this.zedGraphQY.Size = new Size(0x20e, 0x121);
            this.zedGraphQY.TabIndex = 1;
            this.tabPage5.Controls.Add(this.splitContainer3);
            this.tabPage5.Location = new Point(4, 4);
            this.tabPage5.Name = "tabPage5";
            this.tabPage5.Padding = new Padding(3);
            this.tabPage5.Size = new Size(0x2b5, 0x127);
            this.tabPage5.TabIndex = 2;
            this.tabPage5.Text = "国内市场";
            this.tabPage5.UseVisualStyleBackColor = true;
            this.splitContainer3.Dock = DockStyle.Fill;
            this.splitContainer3.Location = new Point(3, 3);
            this.splitContainer3.Name = "splitContainer3";
            this.splitContainer3.Panel1.Controls.Add(this.richTextBox4);
            this.splitContainer3.Panel2.Controls.Add(this.zedGraphGN);
            this.splitContainer3.Size = new Size(0x2af, 0x121);
            this.splitContainer3.SplitterDistance = 0x9d;
            this.splitContainer3.TabIndex = 1;
            this.richTextBox4.BackColor = SystemColors.Window;
            this.richTextBox4.BorderStyle = BorderStyle.FixedSingle;
            this.richTextBox4.Dock = DockStyle.Fill;
            this.richTextBox4.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.richTextBox4.Location = new Point(0, 0);
            this.richTextBox4.Name = "richTextBox4";
            this.richTextBox4.ReadOnly = true;
            this.richTextBox4.Size = new Size(0x9d, 0x121);
            this.richTextBox4.TabIndex = 2;
            this.richTextBox4.Text = "国内：\n\n国内市场需求量有可能和本地市场差不多——低技术产品在接下来几年里需求量很大，而近几年里估计也有销售P3产品的可能，P4产品的前景则不太明朗。";
            this.zedGraphGN.Dock = DockStyle.Fill;
            this.zedGraphGN.IsEnableHZoom = false;
            this.zedGraphGN.IsEnableVZoom = false;
            this.zedGraphGN.Location = new Point(0, 0);
            this.zedGraphGN.Name = "zedGraphGN";
            this.zedGraphGN.ScrollGrace = 0.0;
            this.zedGraphGN.ScrollMaxX = 0.0;
            this.zedGraphGN.ScrollMaxY = 0.0;
            this.zedGraphGN.ScrollMaxY2 = 0.0;
            this.zedGraphGN.ScrollMinX = 0.0;
            this.zedGraphGN.ScrollMinY = 0.0;
            this.zedGraphGN.ScrollMinY2 = 0.0;
            this.zedGraphGN.Size = new Size(0x20e, 0x121);
            this.zedGraphGN.TabIndex = 1;
            this.tabPage6.Controls.Add(this.splitContainer4);
            this.tabPage6.Location = new Point(4, 4);
            this.tabPage6.Name = "tabPage6";
            this.tabPage6.Padding = new Padding(3);
            this.tabPage6.Size = new Size(0x2b5, 0x127);
            this.tabPage6.TabIndex = 3;
            this.tabPage6.Text = "亚洲市场";
            this.tabPage6.UseVisualStyleBackColor = true;
            this.splitContainer4.Dock = DockStyle.Fill;
            this.splitContainer4.Location = new Point(3, 3);
            this.splitContainer4.Name = "splitContainer4";
            this.splitContainer4.Panel1.Controls.Add(this.richTextBox5);
            this.splitContainer4.Panel2.Controls.Add(this.zedGraphYZ);
            this.splitContainer4.Size = new Size(0x2af, 0x121);
            this.splitContainer4.SplitterDistance = 0x9d;
            this.splitContainer4.TabIndex = 1;
            this.richTextBox5.BackColor = SystemColors.Window;
            this.richTextBox5.BorderStyle = BorderStyle.FixedSingle;
            this.richTextBox5.Dock = DockStyle.Fill;
            this.richTextBox5.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.richTextBox5.Location = new Point(0, 0);
            this.richTextBox5.Name = "richTextBox5";
            this.richTextBox5.ReadOnly = true;
            this.richTextBox5.Size = new Size(0x9d, 0x121);
            this.richTextBox5.TabIndex = 3;
            this.richTextBox5.Text = "亚洲：\n\n在这个市场上竞争很激烈。所有产品的市场需求都很大——但是低技术产品的价格会比本地市场的价格低。经过简短推广后，高技术产品价格会比较高。\n\n很难对P4产品的市场进行预测。";
            this.zedGraphYZ.Dock = DockStyle.Fill;
            this.zedGraphYZ.IsEnableHZoom = false;
            this.zedGraphYZ.IsEnableVZoom = false;
            this.zedGraphYZ.Location = new Point(0, 0);
            this.zedGraphYZ.Name = "zedGraphYZ";
            this.zedGraphYZ.ScrollGrace = 0.0;
            this.zedGraphYZ.ScrollMaxX = 0.0;
            this.zedGraphYZ.ScrollMaxY = 0.0;
            this.zedGraphYZ.ScrollMaxY2 = 0.0;
            this.zedGraphYZ.ScrollMinX = 0.0;
            this.zedGraphYZ.ScrollMinY = 0.0;
            this.zedGraphYZ.ScrollMinY2 = 0.0;
            this.zedGraphYZ.Size = new Size(0x20e, 0x121);
            this.zedGraphYZ.TabIndex = 1;
            this.tabPage7.Controls.Add(this.splitContainer5);
            this.tabPage7.Location = new Point(4, 4);
            this.tabPage7.Name = "tabPage7";
            this.tabPage7.Padding = new Padding(3);
            this.tabPage7.Size = new Size(0x2b5, 0x127);
            this.tabPage7.TabIndex = 4;
            this.tabPage7.Text = "国际市场";
            this.tabPage7.UseVisualStyleBackColor = true;
            this.splitContainer5.Dock = DockStyle.Fill;
            this.splitContainer5.Location = new Point(3, 3);
            this.splitContainer5.Name = "splitContainer5";
            this.splitContainer5.Panel1.Controls.Add(this.richTextBox6);
            this.splitContainer5.Panel2.Controls.Add(this.zedGraphGJ);
            this.splitContainer5.Size = new Size(0x2af, 0x121);
            this.splitContainer5.SplitterDistance = 0x9d;
            this.splitContainer5.TabIndex = 1;
            this.richTextBox6.BackColor = SystemColors.Window;
            this.richTextBox6.BorderStyle = BorderStyle.FixedSingle;
            this.richTextBox6.Dock = DockStyle.Fill;
            this.richTextBox6.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.richTextBox6.Location = new Point(0, 0);
            this.richTextBox6.Name = "richTextBox6";
            this.richTextBox6.ReadOnly = true;
            this.richTextBox6.Size = new Size(0x9d, 0x121);
            this.richTextBox6.TabIndex = 4;
            this.richTextBox6.Text = "国际：\n\n国际市场绝对是以低技术产品为主。\n\n对P1产品及P2产品将会有很多需求，这个市场在近几年会非常有吸引力。针对P3产品估计存在某些需求，但价格可能会很低，P4产品市场则不乐观，一方面是因为需求量小，另一方面是因为价格。";
            this.zedGraphGJ.Dock = DockStyle.Fill;
            this.zedGraphGJ.IsEnableHZoom = false;
            this.zedGraphGJ.IsEnableVZoom = false;
            this.zedGraphGJ.Location = new Point(0, 0);
            this.zedGraphGJ.Name = "zedGraphGJ";
            this.zedGraphGJ.ScrollGrace = 0.0;
            this.zedGraphGJ.ScrollMaxX = 0.0;
            this.zedGraphGJ.ScrollMaxY = 0.0;
            this.zedGraphGJ.ScrollMaxY2 = 0.0;
            this.zedGraphGJ.ScrollMinX = 0.0;
            this.zedGraphGJ.ScrollMinY = 0.0;
            this.zedGraphGJ.ScrollMinY2 = 0.0;
            this.zedGraphGJ.Size = new Size(0x20e, 0x121);
            this.zedGraphGJ.TabIndex = 1;
            base.AcceptButton = this.buttonOK;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.CancelButton = this.buttonCancel;
            base.ClientSize = new Size(0x2cb, 0x188);
            base.Controls.Add(this.tabControl1);
            base.Controls.Add(this.buttonCancel);
            base.Controls.Add(this.buttonOK);
            base.FormBorderStyle = FormBorderStyle.FixedDialog;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmXNNGHHY";
            base.ShowInTaskbar = false;
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "frmXNNGHHY";
            base.Load += new EventHandler(this.frmXNNGHHY_Load);
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage2.ResumeLayout(false);
            this.tabControl2.ResumeLayout(false);
            this.tabPage3.ResumeLayout(false);
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.ResumeLayout(false);
            this.tabPage4.ResumeLayout(false);
            this.splitContainer2.Panel1.ResumeLayout(false);
            this.splitContainer2.Panel2.ResumeLayout(false);
            this.splitContainer2.ResumeLayout(false);
            this.tabPage5.ResumeLayout(false);
            this.splitContainer3.Panel1.ResumeLayout(false);
            this.splitContainer3.Panel2.ResumeLayout(false);
            this.splitContainer3.ResumeLayout(false);
            this.tabPage6.ResumeLayout(false);
            this.splitContainer4.Panel1.ResumeLayout(false);
            this.splitContainer4.Panel2.ResumeLayout(false);
            this.splitContainer4.ResumeLayout(false);
            this.tabPage7.ResumeLayout(false);
            this.splitContainer5.Panel1.ResumeLayout(false);
            this.splitContainer5.Panel2.ResumeLayout(false);
            this.splitContainer5.ResumeLayout(false);
            base.ResumeLayout(false);
        }
    }
}

