namespace ERPChess
{
    using BusinessTier;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class frmYCLRK : Form
    {
        private IContainer components;
        private Button buttonOK;
        private Button buttonCancel;
        private GroupBox groupBox2;
        private RichTextBox richTextBox2;
        private GroupBox groupBox1;
        private Label label004;
        private Label label003;
        private Label label002;
        private Label label001;
        private Label label21;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label16;
        private Label label7;
        private Label label6;
        private Label label3;
        private Label label2;
        private Label label5;
        private GroupBox groupBox3;
        private Label label012;
        private Label label011;
        private Label label010;
        private Label label009;
        private Label label10;
        private Label label008;
        private Label label007;
        private Label label006;
        private Label label005;
        private Label label25;
        private Label label26;
        private Label label27;
        private Label label28;
        private Label label29;
        private Label label30;

        public frmYCLRK()
        {
            this.InitializeComponent();
        }

        private void buttonCancel_Click(object sender, EventArgs e)
        {
            base.Close();
        }

        private void buttonOK_Click(object sender, EventArgs e)
        {
            TRawMaterialOrder theLastOrder = TGlobals.currentActor.RawMaterialStock.TheLastOrder;
            int num = ((theLastOrder.R1.TotalPrice + theLastOrder.R2.TotalPrice) + theLastOrder.R3.TotalPrice) + theLastOrder.R4.TotalPrice;
            TGlobals.currentActor.CurrBusinessConditions.OperatingSheet.CurrentCash -= num;
            TGlobals.currentActor.CurrBusinessConditions.OperatingSheet.RawMaterials += num;
            TGlobals.currentActor.RawMaterialStock.IntoStock();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void frmYCLRK_Load(object sender, EventArgs e)
        {
            TRawMaterialOrder theLastOrder = TGlobals.currentActor.RawMaterialStock.TheLastOrder;
            this.label001.Text = theLastOrder.R1.Amount.ToString();
            this.label002.Text = theLastOrder.R2.Amount.ToString();
            this.label003.Text = theLastOrder.R3.Amount.ToString();
            this.label004.Text = theLastOrder.R4.Amount.ToString();
            TRawMaterialOrder statisticsOrder = TGlobals.currentActor.RawMaterialStock.StatisticsOrder;
            this.label005.Text = statisticsOrder.R1.Amount.ToString();
            this.label006.Text = statisticsOrder.R2.Amount.ToString();
            this.label007.Text = statisticsOrder.R3.Amount.ToString();
            this.label008.Text = statisticsOrder.R4.Amount.ToString();
            this.label009.Text = statisticsOrder.R1.TotalPrice.ToString();
            this.label010.Text = statisticsOrder.R2.TotalPrice.ToString();
            this.label011.Text = statisticsOrder.R3.TotalPrice.ToString();
            this.label012.Text = statisticsOrder.R4.TotalPrice.ToString();
        }

        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(frmYCLRK));
            this.buttonOK = new Button();
            this.buttonCancel = new Button();
            this.groupBox2 = new GroupBox();
            this.richTextBox2 = new RichTextBox();
            this.groupBox1 = new GroupBox();
            this.label004 = new Label();
            this.label003 = new Label();
            this.label002 = new Label();
            this.label001 = new Label();
            this.label21 = new Label();
            this.label12 = new Label();
            this.label13 = new Label();
            this.label14 = new Label();
            this.label15 = new Label();
            this.label16 = new Label();
            this.label7 = new Label();
            this.label6 = new Label();
            this.label3 = new Label();
            this.label2 = new Label();
            this.label5 = new Label();
            this.groupBox3 = new GroupBox();
            this.label012 = new Label();
            this.label011 = new Label();
            this.label010 = new Label();
            this.label009 = new Label();
            this.label10 = new Label();
            this.label008 = new Label();
            this.label007 = new Label();
            this.label006 = new Label();
            this.label005 = new Label();
            this.label25 = new Label();
            this.label26 = new Label();
            this.label27 = new Label();
            this.label28 = new Label();
            this.label29 = new Label();
            this.label30 = new Label();
            this.groupBox2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox3.SuspendLayout();
            base.SuspendLayout();
            this.buttonOK.DialogResult = DialogResult.OK;
            this.buttonOK.Location = new Point(0x167, 0x150);
            this.buttonOK.Name = "buttonOK";
            this.buttonOK.Size = new Size(0x4b, 0x17);
            this.buttonOK.TabIndex = 0;
            this.buttonOK.Text = "确定";
            this.buttonOK.UseVisualStyleBackColor = true;
            this.buttonOK.Click += new EventHandler(this.buttonOK_Click);
            this.buttonCancel.DialogResult = DialogResult.Cancel;
            this.buttonCancel.Location = new Point(0x1bb, 0x150);
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.Size = new Size(0x4b, 0x17);
            this.buttonCancel.TabIndex = 1;
            this.buttonCancel.Text = "取消";
            this.buttonCancel.UseVisualStyleBackColor = true;
            this.buttonCancel.Click += new EventHandler(this.buttonCancel_Click);
            this.groupBox2.Controls.Add(this.richTextBox2);
            this.groupBox2.Location = new Point(12, 0x91);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(0x1fa, 0xb9);
            this.groupBox2.TabIndex = 5;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "说明";
            this.richTextBox2.BackColor = SystemColors.Window;
            this.richTextBox2.BorderStyle = BorderStyle.None;
            this.richTextBox2.Dock = DockStyle.Fill;
            this.richTextBox2.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.richTextBox2.Location = new Point(3, 0x11);
            this.richTextBox2.Name = "richTextBox2";
            this.richTextBox2.ReadOnly = true;
            this.richTextBox2.Size = new Size(500, 0xa5);
            this.richTextBox2.TabIndex = 4;
            this.richTextBox2.Text = manager.GetString("richTextBox2.Text");
            this.groupBox1.Controls.Add(this.label004);
            this.groupBox1.Controls.Add(this.label003);
            this.groupBox1.Controls.Add(this.label002);
            this.groupBox1.Controls.Add(this.label001);
            this.groupBox1.Controls.Add(this.label21);
            this.groupBox1.Controls.Add(this.label12);
            this.groupBox1.Controls.Add(this.label13);
            this.groupBox1.Controls.Add(this.label14);
            this.groupBox1.Controls.Add(this.label15);
            this.groupBox1.Controls.Add(this.label16);
            this.groupBox1.Controls.Add(this.label7);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Location = new Point(12, 12);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0xef, 0x7f);
            this.groupBox1.TabIndex = 0x43;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "上期原材料订单";
            this.label004.BorderStyle = BorderStyle.FixedSingle;
            this.label004.Location = new Point(0x9a, 0x61);
            this.label004.Name = "label004";
            this.label004.Size = new Size(0x4b, 0x15);
            this.label004.TabIndex = 0x51;
            this.label004.Text = "-1";
            this.label004.TextAlign = ContentAlignment.MiddleCenter;
            this.label003.BorderStyle = BorderStyle.FixedSingle;
            this.label003.Location = new Point(0x9a, 0x4d);
            this.label003.Name = "label003";
            this.label003.Size = new Size(0x4b, 0x15);
            this.label003.TabIndex = 80;
            this.label003.Text = "-1";
            this.label003.TextAlign = ContentAlignment.MiddleCenter;
            this.label002.BorderStyle = BorderStyle.FixedSingle;
            this.label002.Location = new Point(0x9a, 0x39);
            this.label002.Name = "label002";
            this.label002.Size = new Size(0x4b, 0x15);
            this.label002.TabIndex = 0x4f;
            this.label002.Text = "-1";
            this.label002.TextAlign = ContentAlignment.MiddleCenter;
            this.label001.BorderStyle = BorderStyle.FixedSingle;
            this.label001.Location = new Point(0x9a, 0x25);
            this.label001.Name = "label001";
            this.label001.Size = new Size(0x4b, 0x15);
            this.label001.TabIndex = 0x4e;
            this.label001.Text = "-1";
            this.label001.TextAlign = ContentAlignment.MiddleCenter;
            this.label21.BorderStyle = BorderStyle.FixedSingle;
            this.label21.Location = new Point(0x9a, 0x11);
            this.label21.Name = "label21";
            this.label21.Size = new Size(0x4b, 0x15);
            this.label21.TabIndex = 0x4d;
            this.label21.Text = "订购量";
            this.label21.TextAlign = ContentAlignment.MiddleCenter;
            this.label12.BorderStyle = BorderStyle.FixedSingle;
            this.label12.Location = new Point(80, 0x61);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x4b, 0x15);
            this.label12.TabIndex = 0x4c;
            this.label12.Text = "1M";
            this.label12.TextAlign = ContentAlignment.MiddleCenter;
            this.label13.BorderStyle = BorderStyle.FixedSingle;
            this.label13.Location = new Point(80, 0x4d);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x4b, 0x15);
            this.label13.TabIndex = 0x4b;
            this.label13.Text = "1M";
            this.label13.TextAlign = ContentAlignment.MiddleCenter;
            this.label14.BorderStyle = BorderStyle.FixedSingle;
            this.label14.Location = new Point(80, 0x39);
            this.label14.Name = "label14";
            this.label14.Size = new Size(0x4b, 0x15);
            this.label14.TabIndex = 0x4a;
            this.label14.Text = "1M";
            this.label14.TextAlign = ContentAlignment.MiddleCenter;
            this.label15.BorderStyle = BorderStyle.FixedSingle;
            this.label15.Location = new Point(80, 0x25);
            this.label15.Name = "label15";
            this.label15.Size = new Size(0x4b, 0x15);
            this.label15.TabIndex = 0x49;
            this.label15.Text = "1M";
            this.label15.TextAlign = ContentAlignment.MiddleCenter;
            this.label16.BorderStyle = BorderStyle.FixedSingle;
            this.label16.Location = new Point(80, 0x11);
            this.label16.Name = "label16";
            this.label16.Size = new Size(0x4b, 0x15);
            this.label16.TabIndex = 0x48;
            this.label16.Text = "价格";
            this.label16.TextAlign = ContentAlignment.MiddleCenter;
            this.label7.BorderStyle = BorderStyle.FixedSingle;
            this.label7.Location = new Point(6, 0x61);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x4b, 0x15);
            this.label7.TabIndex = 0x47;
            this.label7.Text = "R4";
            this.label7.TextAlign = ContentAlignment.MiddleCenter;
            this.label6.BorderStyle = BorderStyle.FixedSingle;
            this.label6.Location = new Point(6, 0x4d);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x4b, 0x15);
            this.label6.TabIndex = 70;
            this.label6.Text = "R3";
            this.label6.TextAlign = ContentAlignment.MiddleCenter;
            this.label3.BorderStyle = BorderStyle.FixedSingle;
            this.label3.Location = new Point(6, 0x39);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x4b, 0x15);
            this.label3.TabIndex = 0x45;
            this.label3.Text = "R2";
            this.label3.TextAlign = ContentAlignment.MiddleCenter;
            this.label2.BorderStyle = BorderStyle.FixedSingle;
            this.label2.Location = new Point(6, 0x25);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x4b, 0x15);
            this.label2.TabIndex = 0x44;
            this.label2.Text = "R1";
            this.label2.TextAlign = ContentAlignment.MiddleCenter;
            this.label5.BorderStyle = BorderStyle.FixedSingle;
            this.label5.Location = new Point(6, 0x11);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x4b, 0x15);
            this.label5.TabIndex = 0x43;
            this.label5.Text = "原料";
            this.label5.TextAlign = ContentAlignment.MiddleCenter;
            this.groupBox3.Controls.Add(this.label012);
            this.groupBox3.Controls.Add(this.label011);
            this.groupBox3.Controls.Add(this.label010);
            this.groupBox3.Controls.Add(this.label009);
            this.groupBox3.Controls.Add(this.label10);
            this.groupBox3.Controls.Add(this.label008);
            this.groupBox3.Controls.Add(this.label007);
            this.groupBox3.Controls.Add(this.label006);
            this.groupBox3.Controls.Add(this.label005);
            this.groupBox3.Controls.Add(this.label25);
            this.groupBox3.Controls.Add(this.label26);
            this.groupBox3.Controls.Add(this.label27);
            this.groupBox3.Controls.Add(this.label28);
            this.groupBox3.Controls.Add(this.label29);
            this.groupBox3.Controls.Add(this.label30);
            this.groupBox3.Location = new Point(0x117, 12);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(0xef, 0x7f);
            this.groupBox3.TabIndex = 0x52;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "当前原材料库存";
            this.label012.BorderStyle = BorderStyle.FixedSingle;
            this.label012.Location = new Point(0x9a, 0x61);
            this.label012.Name = "label012";
            this.label012.Size = new Size(0x4b, 0x15);
            this.label012.TabIndex = 0x51;
            this.label012.Text = "-1";
            this.label012.TextAlign = ContentAlignment.MiddleCenter;
            this.label011.BorderStyle = BorderStyle.FixedSingle;
            this.label011.Location = new Point(0x9a, 0x4d);
            this.label011.Name = "label011";
            this.label011.Size = new Size(0x4b, 0x15);
            this.label011.TabIndex = 80;
            this.label011.Text = "-1";
            this.label011.TextAlign = ContentAlignment.MiddleCenter;
            this.label010.BorderStyle = BorderStyle.FixedSingle;
            this.label010.Location = new Point(0x9a, 0x39);
            this.label010.Name = "label010";
            this.label010.Size = new Size(0x4b, 0x15);
            this.label010.TabIndex = 0x4f;
            this.label010.Text = "-1";
            this.label010.TextAlign = ContentAlignment.MiddleCenter;
            this.label009.BorderStyle = BorderStyle.FixedSingle;
            this.label009.Location = new Point(0x9a, 0x25);
            this.label009.Name = "label009";
            this.label009.Size = new Size(0x4b, 0x15);
            this.label009.TabIndex = 0x4e;
            this.label009.Text = "-1";
            this.label009.TextAlign = ContentAlignment.MiddleCenter;
            this.label10.BorderStyle = BorderStyle.FixedSingle;
            this.label10.Location = new Point(0x9a, 0x11);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x4b, 0x15);
            this.label10.TabIndex = 0x4d;
            this.label10.Text = "总金额";
            this.label10.TextAlign = ContentAlignment.MiddleCenter;
            this.label008.BorderStyle = BorderStyle.FixedSingle;
            this.label008.Location = new Point(80, 0x61);
            this.label008.Name = "label008";
            this.label008.Size = new Size(0x4b, 0x15);
            this.label008.TabIndex = 0x4c;
            this.label008.Text = "-1";
            this.label008.TextAlign = ContentAlignment.MiddleCenter;
            this.label007.BorderStyle = BorderStyle.FixedSingle;
            this.label007.Location = new Point(80, 0x4d);
            this.label007.Name = "label007";
            this.label007.Size = new Size(0x4b, 0x15);
            this.label007.TabIndex = 0x4b;
            this.label007.Text = "-1";
            this.label007.TextAlign = ContentAlignment.MiddleCenter;
            this.label006.BorderStyle = BorderStyle.FixedSingle;
            this.label006.Location = new Point(80, 0x39);
            this.label006.Name = "label006";
            this.label006.Size = new Size(0x4b, 0x15);
            this.label006.TabIndex = 0x4a;
            this.label006.Text = "-1";
            this.label006.TextAlign = ContentAlignment.MiddleCenter;
            this.label005.BorderStyle = BorderStyle.FixedSingle;
            this.label005.Location = new Point(80, 0x25);
            this.label005.Name = "label005";
            this.label005.Size = new Size(0x4b, 0x15);
            this.label005.TabIndex = 0x49;
            this.label005.Text = "-1";
            this.label005.TextAlign = ContentAlignment.MiddleCenter;
            this.label25.BorderStyle = BorderStyle.FixedSingle;
            this.label25.Location = new Point(80, 0x11);
            this.label25.Name = "label25";
            this.label25.Size = new Size(0x4b, 0x15);
            this.label25.TabIndex = 0x48;
            this.label25.Text = "数量";
            this.label25.TextAlign = ContentAlignment.MiddleCenter;
            this.label26.BorderStyle = BorderStyle.FixedSingle;
            this.label26.Location = new Point(6, 0x61);
            this.label26.Name = "label26";
            this.label26.Size = new Size(0x4b, 0x15);
            this.label26.TabIndex = 0x47;
            this.label26.Text = "R4";
            this.label26.TextAlign = ContentAlignment.MiddleCenter;
            this.label27.BorderStyle = BorderStyle.FixedSingle;
            this.label27.Location = new Point(6, 0x4d);
            this.label27.Name = "label27";
            this.label27.Size = new Size(0x4b, 0x15);
            this.label27.TabIndex = 70;
            this.label27.Text = "R3";
            this.label27.TextAlign = ContentAlignment.MiddleCenter;
            this.label28.BorderStyle = BorderStyle.FixedSingle;
            this.label28.Location = new Point(6, 0x39);
            this.label28.Name = "label28";
            this.label28.Size = new Size(0x4b, 0x15);
            this.label28.TabIndex = 0x45;
            this.label28.Text = "R2";
            this.label28.TextAlign = ContentAlignment.MiddleCenter;
            this.label29.BorderStyle = BorderStyle.FixedSingle;
            this.label29.Location = new Point(6, 0x25);
            this.label29.Name = "label29";
            this.label29.Size = new Size(0x4b, 0x15);
            this.label29.TabIndex = 0x44;
            this.label29.Text = "R1";
            this.label29.TextAlign = ContentAlignment.MiddleCenter;
            this.label30.BorderStyle = BorderStyle.FixedSingle;
            this.label30.Location = new Point(6, 0x11);
            this.label30.Name = "label30";
            this.label30.Size = new Size(0x4b, 0x15);
            this.label30.TabIndex = 0x43;
            this.label30.Text = "原料";
            this.label30.TextAlign = ContentAlignment.MiddleCenter;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.CancelButton = this.buttonCancel;
            base.ClientSize = new Size(0x21e, 0x16f);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.buttonCancel);
            base.Controls.Add(this.buttonOK);
            base.FormBorderStyle = FormBorderStyle.FixedDialog;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmYCLRK";
            base.ShowInTaskbar = false;
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "frmYCLRK";
            base.Load += new EventHandler(this.frmYCLRK_Load);
            this.groupBox2.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            base.ResumeLayout(false);
        }
    }
}

